// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package account

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bumpCodeAttempts = `-- name: BumpCodeAttempts :exec
UPDATE account_email_codes SET attempts = attempts + 1 WHERE id = $1
`

func (q *Queries) BumpCodeAttempts(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, bumpCodeAttempts, id)
	return err
}

const consumeCode = `-- name: ConsumeCode :exec
UPDATE account_email_codes SET consumed_at = $1 WHERE id = $2
`

type ConsumeCodeParams struct {
	Now pgtype.Timestamptz `json:"now"`
	ID  pgtype.UUID        `json:"id"`
}

func (q *Queries) ConsumeCode(ctx context.Context, arg ConsumeCodeParams) error {
	_, err := q.db.Exec(ctx, consumeCode, arg.Now, arg.ID)
	return err
}

const countAddressesByAccount = `-- name: CountAddressesByAccount :one
SELECT count(*)::bigint
FROM account_addresses
WHERE account_id = $1
`

func (q *Queries) CountAddressesByAccount(ctx context.Context, accountID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAddressesByAccount, accountID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countCodesSince = `-- name: CountCodesSince :one
SELECT count(*)::bigint
FROM account_email_codes
WHERE address_hash = $1 AND issued_at >= $2
`

type CountCodesSinceParams struct {
	AddressHash string             `json:"address_hash"`
	Since       pgtype.Timestamptz `json:"since"`
}

func (q *Queries) CountCodesSince(ctx context.Context, arg CountCodesSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCodesSince, arg.AddressHash, arg.Since)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteAccountAddresses = `-- name: DeleteAccountAddresses :exec
DELETE FROM account_addresses WHERE account_id = $1
`

func (q *Queries) DeleteAccountAddresses(ctx context.Context, accountID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAccountAddresses, accountID)
	return err
}

const deleteAccountBindings = `-- name: DeleteAccountBindings :exec
DELETE FROM account_contributor_bindings WHERE account_id = $1
`

func (q *Queries) DeleteAccountBindings(ctx context.Context, accountID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAccountBindings, accountID)
	return err
}

const deleteAccountProviders = `-- name: DeleteAccountProviders :exec
DELETE FROM account_provider_links WHERE account_id = $1
`

func (q *Queries) DeleteAccountProviders(ctx context.Context, accountID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAccountProviders, accountID)
	return err
}

const deleteBinding = `-- name: DeleteBinding :exec
DELETE FROM account_contributor_bindings
WHERE account_id = $1 AND contributor_id = $2
`

type DeleteBindingParams struct {
	AccountID     pgtype.UUID `json:"account_id"`
	ContributorID string      `json:"contributor_id"`
}

func (q *Queries) DeleteBinding(ctx context.Context, arg DeleteBindingParams) error {
	_, err := q.db.Exec(ctx, deleteBinding, arg.AccountID, arg.ContributorID)
	return err
}

const deleteProviderLink = `-- name: DeleteProviderLink :exec
DELETE FROM account_provider_links
WHERE account_id = $1 AND provider = $2
`

type DeleteProviderLinkParams struct {
	AccountID pgtype.UUID `json:"account_id"`
	Provider  string      `json:"provider"`
}

func (q *Queries) DeleteProviderLink(ctx context.Context, arg DeleteProviderLinkParams) error {
	_, err := q.db.Exec(ctx, deleteProviderLink, arg.AccountID, arg.Provider)
	return err
}

const findAccountByAddress = `-- name: FindAccountByAddress :one
SELECT a.id, a.alias, a.status, a.created_at
FROM accounts a
JOIN account_addresses l ON l.account_id = a.id
WHERE l.address_hash = $1
`

func (q *Queries) FindAccountByAddress(ctx context.Context, addressHash string) (Account, error) {
	row := q.db.QueryRow(ctx, findAccountByAddress, addressHash)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Alias,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const findBindingOwner = `-- name: FindBindingOwner :one
SELECT account_id, contributor_id, key_fingerprint, bound_at
FROM account_contributor_bindings
WHERE contributor_id = $1
`

func (q *Queries) FindBindingOwner(ctx context.Context, contributorID string) (AccountContributorBinding, error) {
	row := q.db.QueryRow(ctx, findBindingOwner, contributorID)
	var i AccountContributorBinding
	err := row.Scan(
		&i.AccountID,
		&i.ContributorID,
		&i.KeyFingerprint,
		&i.BoundAt,
	)
	return i, err
}

const findKeyCredentialByLookup = `-- name: FindKeyCredentialByLookup :one
SELECT account_id, username_hash, key_lookup, key_salt, key_hash, created_at
FROM account_key_credentials
WHERE key_lookup = $1
`

func (q *Queries) FindKeyCredentialByLookup(ctx context.Context, keyLookup string) (AccountKeyCredential, error) {
	row := q.db.QueryRow(ctx, findKeyCredentialByLookup, keyLookup)
	var i AccountKeyCredential
	err := row.Scan(
		&i.AccountID,
		&i.UsernameHash,
		&i.KeyLookup,
		&i.KeySalt,
		&i.KeyHash,
		&i.CreatedAt,
	)
	return i, err
}

const findKeyCredentialByUsername = `-- name: FindKeyCredentialByUsername :one
SELECT account_id, username_hash, key_lookup, key_salt, key_hash, created_at
FROM account_key_credentials
WHERE username_hash = $1
`

func (q *Queries) FindKeyCredentialByUsername(ctx context.Context, usernameHash string) (AccountKeyCredential, error) {
	row := q.db.QueryRow(ctx, findKeyCredentialByUsername, usernameHash)
	var i AccountKeyCredential
	err := row.Scan(
		&i.AccountID,
		&i.UsernameHash,
		&i.KeyLookup,
		&i.KeySalt,
		&i.KeyHash,
		&i.CreatedAt,
	)
	return i, err
}

const findProviderOwner = `-- name: FindProviderOwner :one
SELECT account_id, provider, issuer, subject, email, linked_at
FROM account_provider_links
WHERE provider = $1 AND subject = $2
`

type FindProviderOwnerParams struct {
	Provider string `json:"provider"`
	Subject  string `json:"subject"`
}

func (q *Queries) FindProviderOwner(ctx context.Context, arg FindProviderOwnerParams) (AccountProviderLink, error) {
	row := q.db.QueryRow(ctx, findProviderOwner, arg.Provider, arg.Subject)
	var i AccountProviderLink
	err := row.Scan(
		&i.AccountID,
		&i.Provider,
		&i.Issuer,
		&i.Subject,
		&i.Email,
		&i.LinkedAt,
	)
	return i, err
}

const getAccountByID = `-- name: GetAccountByID :one

SELECT id, alias, status, created_at
FROM accounts
WHERE id = $1
`

// Provider links and OIDC nonces (P13-T03B). Only salt-free opaque
// subjects persist; email is display/relay only and never a merge key.
func (q *Queries) GetAccountByID(ctx context.Context, id pgtype.UUID) (Account, error) {
	row := q.db.QueryRow(ctx, getAccountByID, id)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Alias,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getBinding = `-- name: GetBinding :one

SELECT account_id, contributor_id, key_fingerprint, bound_at
FROM account_contributor_bindings
WHERE account_id = $1 AND contributor_id = $2
`

type GetBindingParams struct {
	AccountID     pgtype.UUID `json:"account_id"`
	ContributorID string      `json:"contributor_id"`
}

// Contributor bindings and link audit (P13-T04B). One contributor binds
// at most one account; the application refuses stolen-ID binds and the
// UNIQUE guard closes the concurrent race.
func (q *Queries) GetBinding(ctx context.Context, arg GetBindingParams) (AccountContributorBinding, error) {
	row := q.db.QueryRow(ctx, getBinding, arg.AccountID, arg.ContributorID)
	var i AccountContributorBinding
	err := row.Scan(
		&i.AccountID,
		&i.ContributorID,
		&i.KeyFingerprint,
		&i.BoundAt,
	)
	return i, err
}

const getFamily = `-- name: GetFamily :one
SELECT id, account_id, refresh_salt, refresh_hash, access_salt,
    access_hash, access_expires, issued_at, revoked_at
FROM account_session_families
WHERE id = $1
`

func (q *Queries) GetFamily(ctx context.Context, id pgtype.UUID) (AccountSessionFamily, error) {
	row := q.db.QueryRow(ctx, getFamily, id)
	var i AccountSessionFamily
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.RefreshSalt,
		&i.RefreshHash,
		&i.AccessSalt,
		&i.AccessHash,
		&i.AccessExpires,
		&i.IssuedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getProviderLink = `-- name: GetProviderLink :one
SELECT account_id, provider, issuer, subject, email, linked_at
FROM account_provider_links
WHERE account_id = $1 AND provider = $2
`

type GetProviderLinkParams struct {
	AccountID pgtype.UUID `json:"account_id"`
	Provider  string      `json:"provider"`
}

func (q *Queries) GetProviderLink(ctx context.Context, arg GetProviderLinkParams) (AccountProviderLink, error) {
	row := q.db.QueryRow(ctx, getProviderLink, arg.AccountID, arg.Provider)
	var i AccountProviderLink
	err := row.Scan(
		&i.AccountID,
		&i.Provider,
		&i.Issuer,
		&i.Subject,
		&i.Email,
		&i.LinkedAt,
	)
	return i, err
}

const insertAccount = `-- name: InsertAccount :exec

INSERT INTO accounts (id, alias, status, created_at)
VALUES ($1, $2, $3, $4)
`

type InsertAccountParams struct {
	ID        pgtype.UUID        `json:"id"`
	Alias     string             `json:"alias"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// Owned by account. Code verifiers and session families for FREE email
// signup/login (P13-T02B). Only salted hashes persist; plaintext codes and
// tokens never reach these statements.
func (q *Queries) InsertAccount(ctx context.Context, arg InsertAccountParams) error {
	_, err := q.db.Exec(ctx, insertAccount,
		arg.ID,
		arg.Alias,
		arg.Status,
		arg.CreatedAt,
	)
	return err
}

const insertAddress = `-- name: InsertAddress :exec
INSERT INTO account_addresses (address_hash, account_id, linked_at)
VALUES ($1, $2, $3)
ON CONFLICT (address_hash) DO NOTHING
`

type InsertAddressParams struct {
	AddressHash string             `json:"address_hash"`
	AccountID   pgtype.UUID        `json:"account_id"`
	LinkedAt    pgtype.Timestamptz `json:"linked_at"`
}

func (q *Queries) InsertAddress(ctx context.Context, arg InsertAddressParams) error {
	_, err := q.db.Exec(ctx, insertAddress, arg.AddressHash, arg.AccountID, arg.LinkedAt)
	return err
}

const insertBinding = `-- name: InsertBinding :exec
INSERT INTO account_contributor_bindings
    (account_id, contributor_id, key_fingerprint, bound_at)
VALUES ($1, $2, $3, $4)
`

type InsertBindingParams struct {
	AccountID      pgtype.UUID        `json:"account_id"`
	ContributorID  string             `json:"contributor_id"`
	KeyFingerprint string             `json:"key_fingerprint"`
	BoundAt        pgtype.Timestamptz `json:"bound_at"`
}

func (q *Queries) InsertBinding(ctx context.Context, arg InsertBindingParams) error {
	_, err := q.db.Exec(ctx, insertBinding,
		arg.AccountID,
		arg.ContributorID,
		arg.KeyFingerprint,
		arg.BoundAt,
	)
	return err
}

const insertBindingAudit = `-- name: InsertBindingAudit :exec
INSERT INTO account_binding_audit
    (id, account_id, contributor_id, action, occurred_at)
VALUES ($1, $2, $3, $4, $5)
`

type InsertBindingAuditParams struct {
	ID            pgtype.UUID        `json:"id"`
	AccountID     pgtype.UUID        `json:"account_id"`
	ContributorID string             `json:"contributor_id"`
	Action        string             `json:"action"`
	OccurredAt    pgtype.Timestamptz `json:"occurred_at"`
}

func (q *Queries) InsertBindingAudit(ctx context.Context, arg InsertBindingAuditParams) error {
	_, err := q.db.Exec(ctx, insertBindingAudit,
		arg.ID,
		arg.AccountID,
		arg.ContributorID,
		arg.Action,
		arg.OccurredAt,
	)
	return err
}

const insertCode = `-- name: InsertCode :exec
INSERT INTO account_email_codes
    (id, address_hash, salt, hash, issued_at, attempts, consumed_at)
VALUES ($1, $2, $3, $4, $5, 0, NULL)
`

type InsertCodeParams struct {
	ID          pgtype.UUID        `json:"id"`
	AddressHash string             `json:"address_hash"`
	Salt        string             `json:"salt"`
	Hash        string             `json:"hash"`
	IssuedAt    pgtype.Timestamptz `json:"issued_at"`
}

func (q *Queries) InsertCode(ctx context.Context, arg InsertCodeParams) error {
	_, err := q.db.Exec(ctx, insertCode,
		arg.ID,
		arg.AddressHash,
		arg.Salt,
		arg.Hash,
		arg.IssuedAt,
	)
	return err
}

const insertFamily = `-- name: InsertFamily :exec
INSERT INTO account_session_families
    (id, account_id, refresh_salt, refresh_hash, access_salt, access_hash,
     access_expires, issued_at, revoked_at)
VALUES ($1, $2, $3, $4, $5,
    $6, $7, $8, NULL)
`

type InsertFamilyParams struct {
	ID            pgtype.UUID        `json:"id"`
	AccountID     pgtype.UUID        `json:"account_id"`
	RefreshSalt   string             `json:"refresh_salt"`
	RefreshHash   string             `json:"refresh_hash"`
	AccessSalt    string             `json:"access_salt"`
	AccessHash    string             `json:"access_hash"`
	AccessExpires pgtype.Timestamptz `json:"access_expires"`
	IssuedAt      pgtype.Timestamptz `json:"issued_at"`
}

func (q *Queries) InsertFamily(ctx context.Context, arg InsertFamilyParams) error {
	_, err := q.db.Exec(ctx, insertFamily,
		arg.ID,
		arg.AccountID,
		arg.RefreshSalt,
		arg.RefreshHash,
		arg.AccessSalt,
		arg.AccessHash,
		arg.AccessExpires,
		arg.IssuedAt,
	)
	return err
}

const insertKeyCredential = `-- name: InsertKeyCredential :exec

INSERT INTO account_key_credentials
    (account_id, username_hash, key_lookup, key_salt, key_hash, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertKeyCredentialParams struct {
	AccountID    pgtype.UUID `json:"account_id"`
	UsernameHash string      `json:"username_hash"`
	KeyLookup    string      `json:"key_lookup"`
	KeySalt      string      `json:"key_salt"`
	KeyHash      string      `json:"key_hash"`
	CreatedAt    int64       `json:"created_at"`
}

// Key-account credentials: unique username and key lookups; the salted
// verifier authenticates after the lookup finds the candidate row.
func (q *Queries) InsertKeyCredential(ctx context.Context, arg InsertKeyCredentialParams) error {
	_, err := q.db.Exec(ctx, insertKeyCredential,
		arg.AccountID,
		arg.UsernameHash,
		arg.KeyLookup,
		arg.KeySalt,
		arg.KeyHash,
		arg.CreatedAt,
	)
	return err
}

const insertNonce = `-- name: InsertNonce :one
INSERT INTO account_oidc_nonces (nonce, consumed_at)
VALUES ($1, $2)
ON CONFLICT (nonce) DO NOTHING
RETURNING nonce
`

type InsertNonceParams struct {
	Nonce      string             `json:"nonce"`
	ConsumedAt pgtype.Timestamptz `json:"consumed_at"`
}

func (q *Queries) InsertNonce(ctx context.Context, arg InsertNonceParams) (string, error) {
	row := q.db.QueryRow(ctx, insertNonce, arg.Nonce, arg.ConsumedAt)
	var nonce string
	err := row.Scan(&nonce)
	return nonce, err
}

const insertProviderLink = `-- name: InsertProviderLink :exec
INSERT INTO account_provider_links
    (account_id, provider, issuer, subject, email, linked_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertProviderLinkParams struct {
	AccountID pgtype.UUID        `json:"account_id"`
	Provider  string             `json:"provider"`
	Issuer    string             `json:"issuer"`
	Subject   string             `json:"subject"`
	Email     string             `json:"email"`
	LinkedAt  pgtype.Timestamptz `json:"linked_at"`
}

func (q *Queries) InsertProviderLink(ctx context.Context, arg InsertProviderLinkParams) error {
	_, err := q.db.Exec(ctx, insertProviderLink,
		arg.AccountID,
		arg.Provider,
		arg.Issuer,
		arg.Subject,
		arg.Email,
		arg.LinkedAt,
	)
	return err
}

const latestCode = `-- name: LatestCode :one
SELECT id, address_hash, salt, hash, issued_at, attempts, consumed_at
FROM account_email_codes
WHERE address_hash = $1
ORDER BY issued_at DESC
LIMIT 1
`

func (q *Queries) LatestCode(ctx context.Context, addressHash string) (AccountEmailCode, error) {
	row := q.db.QueryRow(ctx, latestCode, addressHash)
	var i AccountEmailCode
	err := row.Scan(
		&i.ID,
		&i.AddressHash,
		&i.Salt,
		&i.Hash,
		&i.IssuedAt,
		&i.Attempts,
		&i.ConsumedAt,
	)
	return i, err
}

const listBindingAudit = `-- name: ListBindingAudit :many
SELECT id, account_id, contributor_id, action, occurred_at
FROM account_binding_audit
WHERE account_id = $1
ORDER BY occurred_at, id
`

func (q *Queries) ListBindingAudit(ctx context.Context, accountID pgtype.UUID) ([]AccountBindingAudit, error) {
	rows, err := q.db.Query(ctx, listBindingAudit, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AccountBindingAudit
	for rows.Next() {
		var i AccountBindingAudit
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.ContributorID,
			&i.Action,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listBindings = `-- name: ListBindings :many
SELECT account_id, contributor_id, key_fingerprint, bound_at
FROM account_contributor_bindings
WHERE account_id = $1
ORDER BY contributor_id
`

func (q *Queries) ListBindings(ctx context.Context, accountID pgtype.UUID) ([]AccountContributorBinding, error) {
	rows, err := q.db.Query(ctx, listBindings, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AccountContributorBinding
	for rows.Next() {
		var i AccountContributorBinding
		if err := rows.Scan(
			&i.AccountID,
			&i.ContributorID,
			&i.KeyFingerprint,
			&i.BoundAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProviderLinks = `-- name: ListProviderLinks :many
SELECT account_id, provider, issuer, subject, email, linked_at
FROM account_provider_links
WHERE account_id = $1
ORDER BY provider
`

func (q *Queries) ListProviderLinks(ctx context.Context, accountID pgtype.UUID) ([]AccountProviderLink, error) {
	rows, err := q.db.Query(ctx, listProviderLinks, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AccountProviderLink
	for rows.Next() {
		var i AccountProviderLink
		if err := rows.Scan(
			&i.AccountID,
			&i.Provider,
			&i.Issuer,
			&i.Subject,
			&i.Email,
			&i.LinkedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockAddressCodes = `-- name: LockAddressCodes :many

SELECT id, address_hash, salt, hash, issued_at, attempts, consumed_at
FROM account_email_codes
WHERE address_hash = $1
ORDER BY issued_at DESC, id DESC
FOR UPDATE
`

// Consume lanes lock every code row of the address newest-first; the Go
// side matches by hash (stable id tiebreak), so same-second issuance never
// misattributes a guess to the wrong row.
func (q *Queries) LockAddressCodes(ctx context.Context, addressHash string) ([]AccountEmailCode, error) {
	rows, err := q.db.Query(ctx, lockAddressCodes, addressHash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AccountEmailCode
	for rows.Next() {
		var i AccountEmailCode
		if err := rows.Scan(
			&i.ID,
			&i.AddressHash,
			&i.Salt,
			&i.Hash,
			&i.IssuedAt,
			&i.Attempts,
			&i.ConsumedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockFamily = `-- name: LockFamily :one
SELECT id, account_id, refresh_salt, refresh_hash, access_salt,
    access_hash, access_expires, issued_at, revoked_at
FROM account_session_families
WHERE id = $1
FOR UPDATE
`

func (q *Queries) LockFamily(ctx context.Context, id pgtype.UUID) (AccountSessionFamily, error) {
	row := q.db.QueryRow(ctx, lockFamily, id)
	var i AccountSessionFamily
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.RefreshSalt,
		&i.RefreshHash,
		&i.AccessSalt,
		&i.AccessHash,
		&i.AccessExpires,
		&i.IssuedAt,
		&i.RevokedAt,
	)
	return i, err
}

const lockLatestCode = `-- name: LockLatestCode :one
SELECT id, address_hash, salt, hash, issued_at, attempts, consumed_at
FROM account_email_codes
WHERE address_hash = $1
ORDER BY issued_at DESC
LIMIT 1
FOR UPDATE
`

func (q *Queries) LockLatestCode(ctx context.Context, addressHash string) (AccountEmailCode, error) {
	row := q.db.QueryRow(ctx, lockLatestCode, addressHash)
	var i AccountEmailCode
	err := row.Scan(
		&i.ID,
		&i.AddressHash,
		&i.Salt,
		&i.Hash,
		&i.IssuedAt,
		&i.Attempts,
		&i.ConsumedAt,
	)
	return i, err
}

const revokeAccountFamilies = `-- name: RevokeAccountFamilies :exec
UPDATE account_session_families SET revoked_at = $1
WHERE account_id = $2 AND revoked_at IS NULL
`

type RevokeAccountFamiliesParams struct {
	Now       pgtype.Timestamptz `json:"now"`
	AccountID pgtype.UUID        `json:"account_id"`
}

func (q *Queries) RevokeAccountFamilies(ctx context.Context, arg RevokeAccountFamiliesParams) error {
	_, err := q.db.Exec(ctx, revokeAccountFamilies, arg.Now, arg.AccountID)
	return err
}

const revokeFamily = `-- name: RevokeFamily :exec
UPDATE account_session_families SET revoked_at = $1 WHERE id = $2
`

type RevokeFamilyParams struct {
	Now pgtype.Timestamptz `json:"now"`
	ID  pgtype.UUID        `json:"id"`
}

func (q *Queries) RevokeFamily(ctx context.Context, arg RevokeFamilyParams) error {
	_, err := q.db.Exec(ctx, revokeFamily, arg.Now, arg.ID)
	return err
}

const rotateFamily = `-- name: RotateFamily :exec
UPDATE account_session_families
SET refresh_salt = $1, refresh_hash = $2,
    access_salt = $3, access_hash = $4,
    access_expires = $5
WHERE id = $6
`

type RotateFamilyParams struct {
	RefreshSalt   string             `json:"refresh_salt"`
	RefreshHash   string             `json:"refresh_hash"`
	AccessSalt    string             `json:"access_salt"`
	AccessHash    string             `json:"access_hash"`
	AccessExpires pgtype.Timestamptz `json:"access_expires"`
	ID            pgtype.UUID        `json:"id"`
}

func (q *Queries) RotateFamily(ctx context.Context, arg RotateFamilyParams) error {
	_, err := q.db.Exec(ctx, rotateFamily,
		arg.RefreshSalt,
		arg.RefreshHash,
		arg.AccessSalt,
		arg.AccessHash,
		arg.AccessExpires,
		arg.ID,
	)
	return err
}

const setAccountStatus = `-- name: SetAccountStatus :exec

UPDATE accounts SET status = $1 WHERE id = $2
`

type SetAccountStatusParams struct {
	Status string      `json:"status"`
	ID     pgtype.UUID `json:"id"`
}

// Account status lifecycle (P13-T04A). Suspension and deletion revoke
// sessions via RevokeAccountFamilies in the same transaction; deletion
// additionally drops address and provider bindings while the account
// row stays as an audit record.
func (q *Queries) SetAccountStatus(ctx context.Context, arg SetAccountStatusParams) error {
	_, err := q.db.Exec(ctx, setAccountStatus, arg.Status, arg.ID)
	return err
}

const updateBinding = `-- name: UpdateBinding :exec
UPDATE account_contributor_bindings
SET key_fingerprint = $1, bound_at = $2
WHERE account_id = $3 AND contributor_id = $4
`

type UpdateBindingParams struct {
	KeyFingerprint string             `json:"key_fingerprint"`
	BoundAt        pgtype.Timestamptz `json:"bound_at"`
	AccountID      pgtype.UUID        `json:"account_id"`
	ContributorID  string             `json:"contributor_id"`
}

func (q *Queries) UpdateBinding(ctx context.Context, arg UpdateBindingParams) error {
	_, err := q.db.Exec(ctx, updateBinding,
		arg.KeyFingerprint,
		arg.BoundAt,
		arg.AccountID,
		arg.ContributorID,
	)
	return err
}

const updateProviderLink = `-- name: UpdateProviderLink :exec
UPDATE account_provider_links
SET issuer = $1, subject = $2, email = $3,
    linked_at = $4
WHERE account_id = $5 AND provider = $6
`

type UpdateProviderLinkParams struct {
	Issuer    string             `json:"issuer"`
	Subject   string             `json:"subject"`
	Email     string             `json:"email"`
	LinkedAt  pgtype.Timestamptz `json:"linked_at"`
	AccountID pgtype.UUID        `json:"account_id"`
	Provider  string             `json:"provider"`
}

func (q *Queries) UpdateProviderLink(ctx context.Context, arg UpdateProviderLinkParams) error {
	_, err := q.db.Exec(ctx, updateProviderLink,
		arg.Issuer,
		arg.Subject,
		arg.Email,
		arg.LinkedAt,
		arg.AccountID,
		arg.Provider,
	)
	return err
}
