// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package account

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bumpCodeAttempts = `-- name: BumpCodeAttempts :exec
UPDATE account_email_codes SET attempts = attempts + 1 WHERE id = $1
`

func (q *Queries) BumpCodeAttempts(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, bumpCodeAttempts, id)
	return err
}

const consumeCode = `-- name: ConsumeCode :exec
UPDATE account_email_codes SET consumed_at = $1 WHERE id = $2
`

type ConsumeCodeParams struct {
	Now pgtype.Timestamptz `json:"now"`
	ID  pgtype.UUID        `json:"id"`
}

func (q *Queries) ConsumeCode(ctx context.Context, arg ConsumeCodeParams) error {
	_, err := q.db.Exec(ctx, consumeCode, arg.Now, arg.ID)
	return err
}

const countCodesSince = `-- name: CountCodesSince :one
SELECT count(*)::bigint
FROM account_email_codes
WHERE address_hash = $1 AND issued_at >= $2
`

type CountCodesSinceParams struct {
	AddressHash string             `json:"address_hash"`
	Since       pgtype.Timestamptz `json:"since"`
}

func (q *Queries) CountCodesSince(ctx context.Context, arg CountCodesSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countCodesSince, arg.AddressHash, arg.Since)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const findAccountByAddress = `-- name: FindAccountByAddress :one
SELECT a.id, a.alias, a.status, a.created_at
FROM accounts a
JOIN account_addresses l ON l.account_id = a.id
WHERE l.address_hash = $1
`

func (q *Queries) FindAccountByAddress(ctx context.Context, addressHash string) (Account, error) {
	row := q.db.QueryRow(ctx, findAccountByAddress, addressHash)
	var i Account
	err := row.Scan(
		&i.ID,
		&i.Alias,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getFamily = `-- name: GetFamily :one
SELECT id, account_id, refresh_salt, refresh_hash, access_salt,
    access_hash, access_expires, issued_at, revoked_at
FROM account_session_families
WHERE id = $1
`

func (q *Queries) GetFamily(ctx context.Context, id pgtype.UUID) (AccountSessionFamily, error) {
	row := q.db.QueryRow(ctx, getFamily, id)
	var i AccountSessionFamily
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.RefreshSalt,
		&i.RefreshHash,
		&i.AccessSalt,
		&i.AccessHash,
		&i.AccessExpires,
		&i.IssuedAt,
		&i.RevokedAt,
	)
	return i, err
}

const insertAccount = `-- name: InsertAccount :exec

INSERT INTO accounts (id, alias, status, created_at)
VALUES ($1, $2, $3, $4)
`

type InsertAccountParams struct {
	ID        pgtype.UUID        `json:"id"`
	Alias     string             `json:"alias"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// Owned by account. Code verifiers and session families for FREE email
// signup/login (P13-T02B). Only salted hashes persist; plaintext codes and
// tokens never reach these statements.
func (q *Queries) InsertAccount(ctx context.Context, arg InsertAccountParams) error {
	_, err := q.db.Exec(ctx, insertAccount,
		arg.ID,
		arg.Alias,
		arg.Status,
		arg.CreatedAt,
	)
	return err
}

const insertAddress = `-- name: InsertAddress :exec
INSERT INTO account_addresses (address_hash, account_id, linked_at)
VALUES ($1, $2, $3)
ON CONFLICT (address_hash) DO NOTHING
`

type InsertAddressParams struct {
	AddressHash string             `json:"address_hash"`
	AccountID   pgtype.UUID        `json:"account_id"`
	LinkedAt    pgtype.Timestamptz `json:"linked_at"`
}

func (q *Queries) InsertAddress(ctx context.Context, arg InsertAddressParams) error {
	_, err := q.db.Exec(ctx, insertAddress, arg.AddressHash, arg.AccountID, arg.LinkedAt)
	return err
}

const insertCode = `-- name: InsertCode :exec
INSERT INTO account_email_codes
    (id, address_hash, salt, hash, issued_at, attempts, consumed_at)
VALUES ($1, $2, $3, $4, $5, 0, NULL)
`

type InsertCodeParams struct {
	ID          pgtype.UUID        `json:"id"`
	AddressHash string             `json:"address_hash"`
	Salt        string             `json:"salt"`
	Hash        string             `json:"hash"`
	IssuedAt    pgtype.Timestamptz `json:"issued_at"`
}

func (q *Queries) InsertCode(ctx context.Context, arg InsertCodeParams) error {
	_, err := q.db.Exec(ctx, insertCode,
		arg.ID,
		arg.AddressHash,
		arg.Salt,
		arg.Hash,
		arg.IssuedAt,
	)
	return err
}

const insertFamily = `-- name: InsertFamily :exec
INSERT INTO account_session_families
    (id, account_id, refresh_salt, refresh_hash, access_salt, access_hash,
     access_expires, issued_at, revoked_at)
VALUES ($1, $2, $3, $4, $5,
    $6, $7, $8, NULL)
`

type InsertFamilyParams struct {
	ID            pgtype.UUID        `json:"id"`
	AccountID     pgtype.UUID        `json:"account_id"`
	RefreshSalt   string             `json:"refresh_salt"`
	RefreshHash   string             `json:"refresh_hash"`
	AccessSalt    string             `json:"access_salt"`
	AccessHash    string             `json:"access_hash"`
	AccessExpires pgtype.Timestamptz `json:"access_expires"`
	IssuedAt      pgtype.Timestamptz `json:"issued_at"`
}

func (q *Queries) InsertFamily(ctx context.Context, arg InsertFamilyParams) error {
	_, err := q.db.Exec(ctx, insertFamily,
		arg.ID,
		arg.AccountID,
		arg.RefreshSalt,
		arg.RefreshHash,
		arg.AccessSalt,
		arg.AccessHash,
		arg.AccessExpires,
		arg.IssuedAt,
	)
	return err
}

const latestCode = `-- name: LatestCode :one
SELECT id, address_hash, salt, hash, issued_at, attempts, consumed_at
FROM account_email_codes
WHERE address_hash = $1
ORDER BY issued_at DESC
LIMIT 1
`

func (q *Queries) LatestCode(ctx context.Context, addressHash string) (AccountEmailCode, error) {
	row := q.db.QueryRow(ctx, latestCode, addressHash)
	var i AccountEmailCode
	err := row.Scan(
		&i.ID,
		&i.AddressHash,
		&i.Salt,
		&i.Hash,
		&i.IssuedAt,
		&i.Attempts,
		&i.ConsumedAt,
	)
	return i, err
}

const lockAddressCodes = `-- name: LockAddressCodes :many

SELECT id, address_hash, salt, hash, issued_at, attempts, consumed_at
FROM account_email_codes
WHERE address_hash = $1
ORDER BY issued_at DESC, id DESC
FOR UPDATE
`

// Consume lanes lock every code row of the address newest-first; the Go
// side matches by hash (stable id tiebreak), so same-second issuance never
// misattributes a guess to the wrong row.
func (q *Queries) LockAddressCodes(ctx context.Context, addressHash string) ([]AccountEmailCode, error) {
	rows, err := q.db.Query(ctx, lockAddressCodes, addressHash)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AccountEmailCode
	for rows.Next() {
		var i AccountEmailCode
		if err := rows.Scan(
			&i.ID,
			&i.AddressHash,
			&i.Salt,
			&i.Hash,
			&i.IssuedAt,
			&i.Attempts,
			&i.ConsumedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockFamily = `-- name: LockFamily :one
SELECT id, account_id, refresh_salt, refresh_hash, access_salt,
    access_hash, access_expires, issued_at, revoked_at
FROM account_session_families
WHERE id = $1
FOR UPDATE
`

func (q *Queries) LockFamily(ctx context.Context, id pgtype.UUID) (AccountSessionFamily, error) {
	row := q.db.QueryRow(ctx, lockFamily, id)
	var i AccountSessionFamily
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.RefreshSalt,
		&i.RefreshHash,
		&i.AccessSalt,
		&i.AccessHash,
		&i.AccessExpires,
		&i.IssuedAt,
		&i.RevokedAt,
	)
	return i, err
}

const lockLatestCode = `-- name: LockLatestCode :one
SELECT id, address_hash, salt, hash, issued_at, attempts, consumed_at
FROM account_email_codes
WHERE address_hash = $1
ORDER BY issued_at DESC
LIMIT 1
FOR UPDATE
`

func (q *Queries) LockLatestCode(ctx context.Context, addressHash string) (AccountEmailCode, error) {
	row := q.db.QueryRow(ctx, lockLatestCode, addressHash)
	var i AccountEmailCode
	err := row.Scan(
		&i.ID,
		&i.AddressHash,
		&i.Salt,
		&i.Hash,
		&i.IssuedAt,
		&i.Attempts,
		&i.ConsumedAt,
	)
	return i, err
}

const revokeAccountFamilies = `-- name: RevokeAccountFamilies :exec
UPDATE account_session_families SET revoked_at = $1
WHERE account_id = $2 AND revoked_at IS NULL
`

type RevokeAccountFamiliesParams struct {
	Now       pgtype.Timestamptz `json:"now"`
	AccountID pgtype.UUID        `json:"account_id"`
}

func (q *Queries) RevokeAccountFamilies(ctx context.Context, arg RevokeAccountFamiliesParams) error {
	_, err := q.db.Exec(ctx, revokeAccountFamilies, arg.Now, arg.AccountID)
	return err
}

const revokeFamily = `-- name: RevokeFamily :exec
UPDATE account_session_families SET revoked_at = $1 WHERE id = $2
`

type RevokeFamilyParams struct {
	Now pgtype.Timestamptz `json:"now"`
	ID  pgtype.UUID        `json:"id"`
}

func (q *Queries) RevokeFamily(ctx context.Context, arg RevokeFamilyParams) error {
	_, err := q.db.Exec(ctx, revokeFamily, arg.Now, arg.ID)
	return err
}

const rotateFamily = `-- name: RotateFamily :exec
UPDATE account_session_families
SET refresh_salt = $1, refresh_hash = $2,
    access_salt = $3, access_hash = $4,
    access_expires = $5
WHERE id = $6
`

type RotateFamilyParams struct {
	RefreshSalt   string             `json:"refresh_salt"`
	RefreshHash   string             `json:"refresh_hash"`
	AccessSalt    string             `json:"access_salt"`
	AccessHash    string             `json:"access_hash"`
	AccessExpires pgtype.Timestamptz `json:"access_expires"`
	ID            pgtype.UUID        `json:"id"`
}

func (q *Queries) RotateFamily(ctx context.Context, arg RotateFamilyParams) error {
	_, err := q.db.Exec(ctx, rotateFamily,
		arg.RefreshSalt,
		arg.RefreshHash,
		arg.AccessSalt,
		arg.AccessHash,
		arg.AccessExpires,
		arg.ID,
	)
	return err
}
