// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package account

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID        pgtype.UUID        `json:"id"`
	Alias     string             `json:"alias"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type AccountAddress struct {
	AddressHash string             `json:"address_hash"`
	AccountID   pgtype.UUID        `json:"account_id"`
	LinkedAt    pgtype.Timestamptz `json:"linked_at"`
}

type AccountBindingAudit struct {
	ID            pgtype.UUID        `json:"id"`
	AccountID     pgtype.UUID        `json:"account_id"`
	ContributorID string             `json:"contributor_id"`
	Action        string             `json:"action"`
	OccurredAt    pgtype.Timestamptz `json:"occurred_at"`
}

type AccountContributorBinding struct {
	AccountID      pgtype.UUID        `json:"account_id"`
	ContributorID  string             `json:"contributor_id"`
	KeyFingerprint string             `json:"key_fingerprint"`
	BoundAt        pgtype.Timestamptz `json:"bound_at"`
}

type AccountEmailCode struct {
	ID          pgtype.UUID        `json:"id"`
	AddressHash string             `json:"address_hash"`
	Salt        string             `json:"salt"`
	Hash        string             `json:"hash"`
	IssuedAt    pgtype.Timestamptz `json:"issued_at"`
	Attempts    int32              `json:"attempts"`
	ConsumedAt  pgtype.Timestamptz `json:"consumed_at"`
}

type AccountOidcNonce struct {
	Nonce      string             `json:"nonce"`
	ConsumedAt pgtype.Timestamptz `json:"consumed_at"`
}

type AccountProviderLink struct {
	AccountID pgtype.UUID        `json:"account_id"`
	Provider  string             `json:"provider"`
	Issuer    string             `json:"issuer"`
	Subject   string             `json:"subject"`
	Email     string             `json:"email"`
	LinkedAt  pgtype.Timestamptz `json:"linked_at"`
}

type AccountSessionFamily struct {
	ID            pgtype.UUID        `json:"id"`
	AccountID     pgtype.UUID        `json:"account_id"`
	RefreshSalt   string             `json:"refresh_salt"`
	RefreshHash   string             `json:"refresh_hash"`
	AccessSalt    string             `json:"access_salt"`
	AccessHash    string             `json:"access_hash"`
	AccessExpires pgtype.Timestamptz `json:"access_expires"`
	IssuedAt      pgtype.Timestamptz `json:"issued_at"`
	RevokedAt     pgtype.Timestamptz `json:"revoked_at"`
}
