// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: claims.sql

package stationprofile

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activeDeclaration = `-- name: ActiveDeclaration :one
SELECT id, claim_id, version, nonce_digest, expected_digest, declaration, state, attempts, expires_at, consumed_at, created_at
FROM claim_declarations
WHERE claim_id = $1 AND state = 'active'
ORDER BY version DESC
LIMIT 1
`

func (q *Queries) ActiveDeclaration(ctx context.Context, claimID pgtype.UUID) (ClaimDeclaration, error) {
	row := q.db.QueryRow(ctx, activeDeclaration, claimID)
	var i ClaimDeclaration
	err := row.Scan(
		&i.ID,
		&i.ClaimID,
		&i.Version,
		&i.NonceDigest,
		&i.ExpectedDigest,
		&i.Declaration,
		&i.State,
		&i.Attempts,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const bumpDeclarationAttempts = `-- name: BumpDeclarationAttempts :one
UPDATE claim_declarations
SET attempts = attempts + 1
WHERE id = $1 AND state = 'active'
RETURNING id, attempts
`

type BumpDeclarationAttemptsRow struct {
	ID       pgtype.UUID `json:"id"`
	Attempts int32       `json:"attempts"`
}

func (q *Queries) BumpDeclarationAttempts(ctx context.Context, id pgtype.UUID) (BumpDeclarationAttemptsRow, error) {
	row := q.db.QueryRow(ctx, bumpDeclarationAttempts, id)
	var i BumpDeclarationAttemptsRow
	err := row.Scan(&i.ID, &i.Attempts)
	return i, err
}

const consumeDeclaration = `-- name: ConsumeDeclaration :execrows
UPDATE claim_declarations
SET state = 'consumed', consumed_at = now()
WHERE id = $1 AND state = 'active'
`

func (q *Queries) ConsumeDeclaration(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, consumeDeclaration, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countOpenClaims = `-- name: CountOpenClaims :one
SELECT count(*) FROM profile_claims
WHERE account_id = $1 AND state NOT IN ('approved', 'denied', 'cancelled', 'expired')
`

func (q *Queries) CountOpenClaims(ctx context.Context, accountID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countOpenClaims, accountID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createClaim = `-- name: CreateClaim :one

INSERT INTO profile_claims (id, account_id, station_id, operator_cnpj, operator_source, role, scopes, policy_version, state, client_key)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, 'draft', $9)
ON CONFLICT (account_id, client_key) WHERE client_key <> '' DO NOTHING
RETURNING id, account_id, station_id, operator_cnpj, operator_source, role, scopes, policy_version, state, client_key, created_at, updated_at
`

type CreateClaimParams struct {
	ID             pgtype.UUID `json:"id"`
	AccountID      pgtype.UUID `json:"account_id"`
	StationID      pgtype.UUID `json:"station_id"`
	OperatorCnpj   string      `json:"operator_cnpj"`
	OperatorSource string      `json:"operator_source"`
	Role           string      `json:"role"`
	Scopes         string      `json:"scopes"`
	PolicyVersion  string      `json:"policy_version"`
	ClientKey      string      `json:"client_key"`
}

// Owned by stationprofile (claims, P30-T03). Account-bound private
// requests with server-bound declarations. Competing claims stay
// private rows; idempotency converges per owner key; only one active
// declaration per claim (reissue supersedes in one guarded update).
func (q *Queries) CreateClaim(ctx context.Context, arg CreateClaimParams) (ProfileClaim, error) {
	row := q.db.QueryRow(ctx, createClaim,
		arg.ID,
		arg.AccountID,
		arg.StationID,
		arg.OperatorCnpj,
		arg.OperatorSource,
		arg.Role,
		arg.Scopes,
		arg.PolicyVersion,
		arg.ClientKey,
	)
	var i ProfileClaim
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.StationID,
		&i.OperatorCnpj,
		&i.OperatorSource,
		&i.Role,
		&i.Scopes,
		&i.PolicyVersion,
		&i.State,
		&i.ClientKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDeclaration = `-- name: CreateDeclaration :one
INSERT INTO claim_declarations (id, claim_id, version, nonce_digest, expected_digest, declaration, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, claim_id, version, nonce_digest, expected_digest, declaration, state, attempts, expires_at, consumed_at, created_at
`

type CreateDeclarationParams struct {
	ID             pgtype.UUID        `json:"id"`
	ClaimID        pgtype.UUID        `json:"claim_id"`
	Version        int32              `json:"version"`
	NonceDigest    string             `json:"nonce_digest"`
	ExpectedDigest string             `json:"expected_digest"`
	Declaration    string             `json:"declaration"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateDeclaration(ctx context.Context, arg CreateDeclarationParams) (ClaimDeclaration, error) {
	row := q.db.QueryRow(ctx, createDeclaration,
		arg.ID,
		arg.ClaimID,
		arg.Version,
		arg.NonceDigest,
		arg.ExpectedDigest,
		arg.Declaration,
		arg.ExpiresAt,
	)
	var i ClaimDeclaration
	err := row.Scan(
		&i.ID,
		&i.ClaimID,
		&i.Version,
		&i.NonceDigest,
		&i.ExpectedDigest,
		&i.Declaration,
		&i.State,
		&i.Attempts,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const expireDeclaration = `-- name: ExpireDeclaration :execrows
UPDATE claim_declarations
SET state = 'expired'
WHERE id = $1 AND state = 'active'
`

func (q *Queries) ExpireDeclaration(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, expireDeclaration, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getClaim = `-- name: GetClaim :one
SELECT id, account_id, station_id, operator_cnpj, operator_source, role, scopes, policy_version, state, client_key, created_at, updated_at
FROM profile_claims
WHERE id = $1
`

func (q *Queries) GetClaim(ctx context.Context, id pgtype.UUID) (ProfileClaim, error) {
	row := q.db.QueryRow(ctx, getClaim, id)
	var i ProfileClaim
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.StationID,
		&i.OperatorCnpj,
		&i.OperatorSource,
		&i.Role,
		&i.Scopes,
		&i.PolicyVersion,
		&i.State,
		&i.ClientKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getClaimByKey = `-- name: GetClaimByKey :one
SELECT id, account_id, station_id, operator_cnpj, operator_source, role, scopes, policy_version, state, client_key, created_at, updated_at
FROM profile_claims
WHERE account_id = $1 AND client_key = $2 AND client_key <> ''
`

type GetClaimByKeyParams struct {
	AccountID pgtype.UUID `json:"account_id"`
	ClientKey string      `json:"client_key"`
}

func (q *Queries) GetClaimByKey(ctx context.Context, arg GetClaimByKeyParams) (ProfileClaim, error) {
	row := q.db.QueryRow(ctx, getClaimByKey, arg.AccountID, arg.ClientKey)
	var i ProfileClaim
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.StationID,
		&i.OperatorCnpj,
		&i.OperatorSource,
		&i.Role,
		&i.Scopes,
		&i.PolicyVersion,
		&i.State,
		&i.ClientKey,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDeclaration = `-- name: GetDeclaration :one
SELECT id, claim_id, version, nonce_digest, expected_digest, declaration, state, attempts, expires_at, consumed_at, created_at
FROM claim_declarations
WHERE id = $1
`

func (q *Queries) GetDeclaration(ctx context.Context, id pgtype.UUID) (ClaimDeclaration, error) {
	row := q.db.QueryRow(ctx, getDeclaration, id)
	var i ClaimDeclaration
	err := row.Scan(
		&i.ID,
		&i.ClaimID,
		&i.Version,
		&i.NonceDigest,
		&i.ExpectedDigest,
		&i.Declaration,
		&i.State,
		&i.Attempts,
		&i.ExpiresAt,
		&i.ConsumedAt,
		&i.CreatedAt,
	)
	return i, err
}

const listOwnedClaims = `-- name: ListOwnedClaims :many
SELECT id, account_id, station_id, operator_cnpj, operator_source, role, scopes, policy_version, state, client_key, created_at, updated_at
FROM profile_claims
WHERE account_id = $1
ORDER BY created_at DESC
LIMIT $3::int OFFSET $2::int
`

type ListOwnedClaimsParams struct {
	AccountID  pgtype.UUID `json:"account_id"`
	PageOffset int32       `json:"page_offset"`
	PageLimit  int32       `json:"page_limit"`
}

func (q *Queries) ListOwnedClaims(ctx context.Context, arg ListOwnedClaimsParams) ([]ProfileClaim, error) {
	rows, err := q.db.Query(ctx, listOwnedClaims, arg.AccountID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProfileClaim
	for rows.Next() {
		var i ProfileClaim
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.StationID,
			&i.OperatorCnpj,
			&i.OperatorSource,
			&i.Role,
			&i.Scopes,
			&i.PolicyVersion,
			&i.State,
			&i.ClientKey,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setClaimReviewState = `-- name: SetClaimReviewState :execrows
UPDATE profile_claims
SET state = $1, updated_at = now()
WHERE id = $2 AND state IN ('draft', 'awaiting_proof', 'checking', 'needs_information', 'in_review')
`

type SetClaimReviewStateParams struct {
	State string      `json:"state"`
	ID    pgtype.UUID `json:"id"`
}

func (q *Queries) SetClaimReviewState(ctx context.Context, arg SetClaimReviewStateParams) (int64, error) {
	result, err := q.db.Exec(ctx, setClaimReviewState, arg.State, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setClaimState = `-- name: SetClaimState :execrows
UPDATE profile_claims
SET state = $1, updated_at = now()
WHERE id = $2 AND state = $3
`

type SetClaimStateParams struct {
	State         string      `json:"state"`
	ID            pgtype.UUID `json:"id"`
	ExpectedState string      `json:"expected_state"`
}

func (q *Queries) SetClaimState(ctx context.Context, arg SetClaimStateParams) (int64, error) {
	result, err := q.db.Exec(ctx, setClaimState, arg.State, arg.ID, arg.ExpectedState)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const supersedeDeclarations = `-- name: SupersedeDeclarations :execrows
UPDATE claim_declarations
SET state = 'superseded'
WHERE claim_id = $1 AND state = 'active'
`

func (q *Queries) SupersedeDeclarations(ctx context.Context, claimID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, supersedeDeclarations, claimID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
