// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: grants.sql

package stationprofile

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activeGrant = `-- name: ActiveGrant :one
SELECT id, account_id, station_id, operator_cnpj, role, scopes, version, status, claim_id, decision_id, valid_from, valid_to
FROM representation_grants
WHERE account_id = $1 AND station_id = $2 AND status = 'active'
`

type ActiveGrantParams struct {
	AccountID pgtype.UUID `json:"account_id"`
	StationID pgtype.UUID `json:"station_id"`
}

func (q *Queries) ActiveGrant(ctx context.Context, arg ActiveGrantParams) (RepresentationGrant, error) {
	row := q.db.QueryRow(ctx, activeGrant, arg.AccountID, arg.StationID)
	var i RepresentationGrant
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.StationID,
		&i.OperatorCnpj,
		&i.Role,
		&i.Scopes,
		&i.Version,
		&i.Status,
		&i.ClaimID,
		&i.DecisionID,
		&i.ValidFrom,
		&i.ValidTo,
	)
	return i, err
}

const createClaimDecision = `-- name: CreateClaimDecision :one

INSERT INTO claim_decisions (id, claim_id, reviewer, decision, reason, policy_version, proof_version, operator_cnpj, scopes)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, claim_id, reviewer, decision, reason, policy_version, proof_version, operator_cnpj, scopes, decided_at
`

type CreateClaimDecisionParams struct {
	ID            pgtype.UUID `json:"id"`
	ClaimID       pgtype.UUID `json:"claim_id"`
	Reviewer      string      `json:"reviewer"`
	Decision      string      `json:"decision"`
	Reason        string      `json:"reason"`
	PolicyVersion string      `json:"policy_version"`
	ProofVersion  int32       `json:"proof_version"`
	OperatorCnpj  string      `json:"operator_cnpj"`
	Scopes        string      `json:"scopes"`
}

// Owned by stationprofile (review and grants, P31-T03). Audited
// decisions plus narrowly scoped capability. Concurrent approvals
// converge on the active-grant guard; reviewer/self, stale-operator
// and dead-account cases fail before any write.
func (q *Queries) CreateClaimDecision(ctx context.Context, arg CreateClaimDecisionParams) (ClaimDecision, error) {
	row := q.db.QueryRow(ctx, createClaimDecision,
		arg.ID,
		arg.ClaimID,
		arg.Reviewer,
		arg.Decision,
		arg.Reason,
		arg.PolicyVersion,
		arg.ProofVersion,
		arg.OperatorCnpj,
		arg.Scopes,
	)
	var i ClaimDecision
	err := row.Scan(
		&i.ID,
		&i.ClaimID,
		&i.Reviewer,
		&i.Decision,
		&i.Reason,
		&i.PolicyVersion,
		&i.ProofVersion,
		&i.OperatorCnpj,
		&i.Scopes,
		&i.DecidedAt,
	)
	return i, err
}

const createGrant = `-- name: CreateGrant :one
INSERT INTO representation_grants (id, account_id, station_id, operator_cnpj, role, scopes, version, claim_id, decision_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (account_id, station_id) WHERE status = 'active' DO NOTHING
RETURNING id, account_id, station_id, operator_cnpj, role, scopes, version, status, claim_id, decision_id, valid_from, valid_to
`

type CreateGrantParams struct {
	ID           pgtype.UUID `json:"id"`
	AccountID    pgtype.UUID `json:"account_id"`
	StationID    pgtype.UUID `json:"station_id"`
	OperatorCnpj string      `json:"operator_cnpj"`
	Role         string      `json:"role"`
	Scopes       string      `json:"scopes"`
	Version      int32       `json:"version"`
	ClaimID      pgtype.UUID `json:"claim_id"`
	DecisionID   pgtype.UUID `json:"decision_id"`
}

func (q *Queries) CreateGrant(ctx context.Context, arg CreateGrantParams) (RepresentationGrant, error) {
	row := q.db.QueryRow(ctx, createGrant,
		arg.ID,
		arg.AccountID,
		arg.StationID,
		arg.OperatorCnpj,
		arg.Role,
		arg.Scopes,
		arg.Version,
		arg.ClaimID,
		arg.DecisionID,
	)
	var i RepresentationGrant
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.StationID,
		&i.OperatorCnpj,
		&i.Role,
		&i.Scopes,
		&i.Version,
		&i.Status,
		&i.ClaimID,
		&i.DecisionID,
		&i.ValidFrom,
		&i.ValidTo,
	)
	return i, err
}
