// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package stationprofile

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ClaimDeclaration struct {
	ID             pgtype.UUID        `json:"id"`
	ClaimID        pgtype.UUID        `json:"claim_id"`
	Version        int32              `json:"version"`
	NonceDigest    string             `json:"nonce_digest"`
	ExpectedDigest string             `json:"expected_digest"`
	Declaration    string             `json:"declaration"`
	State          string             `json:"state"`
	Attempts       int32              `json:"attempts"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt     pgtype.Timestamptz `json:"consumed_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type DirectoryIdentifier struct {
	ID               pgtype.UUID        `json:"id"`
	StationID        pgtype.UUID        `json:"station_id"`
	Kind             string             `json:"kind"`
	NormalizedValue  string             `json:"normalized_value"`
	ValidFrom        pgtype.Timestamptz `json:"valid_from"`
	ValidTo          pgtype.Timestamptz `json:"valid_to"`
	SourceRevisionID pgtype.Text        `json:"source_revision_id"`
}

type DirectoryLocationRevision struct {
	ID              pgtype.UUID        `json:"id"`
	StationID       pgtype.UUID        `json:"station_id"`
	Point           interface{}        `json:"point"`
	Quality         string             `json:"quality"`
	Provider        string             `json:"provider"`
	SourceReference string             `json:"source_reference"`
	ObtainedAt      pgtype.Timestamptz `json:"obtained_at"`
	SupersedesID    pgtype.UUID        `json:"supersedes_id"`
}

type DirectoryStation struct {
	ID                pgtype.UUID        `json:"id"`
	DisplayName       string             `json:"display_name"`
	Address           []byte             `json:"address"`
	MunicipalityCode  pgtype.Text        `json:"municipality_code"`
	State             pgtype.Text        `json:"state"`
	Status            string             `json:"status"`
	CurrentPoint      interface{}        `json:"current_point"`
	CurrentQuality    pgtype.Text        `json:"current_quality"`
	CurrentRevisionID pgtype.UUID        `json:"current_revision_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type ProfileClaim struct {
	ID             pgtype.UUID        `json:"id"`
	AccountID      pgtype.UUID        `json:"account_id"`
	StationID      pgtype.UUID        `json:"station_id"`
	OperatorCnpj   string             `json:"operator_cnpj"`
	OperatorSource string             `json:"operator_source"`
	Role           string             `json:"role"`
	Scopes         string             `json:"scopes"`
	PolicyVersion  string             `json:"policy_version"`
	State          string             `json:"state"`
	ClientKey      string             `json:"client_key"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type StationOperatorRevision struct {
	ID              pgtype.UUID        `json:"id"`
	StationID       pgtype.UUID        `json:"station_id"`
	Cnpj            string             `json:"cnpj"`
	Source          string             `json:"source"`
	SourceReference string             `json:"source_reference"`
	ValidFrom       pgtype.Timestamptz `json:"valid_from"`
	ValidTo         pgtype.Timestamptz `json:"valid_to"`
}

type StationProfile struct {
	StationID     pgtype.UUID        `json:"station_id"`
	PolicyVersion string             `json:"policy_version"`
	Projection    []byte             `json:"projection"`
	Revision      int32              `json:"revision"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}
