// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profiles.sql

package stationprofile

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const closeOperatorRevision = `-- name: CloseOperatorRevision :execrows
UPDATE station_operator_revisions
SET valid_to = now()
WHERE id = $1 AND valid_to IS NULL
`

func (q *Queries) CloseOperatorRevision(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, closeOperatorRevision, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const currentOperatorRevision = `-- name: CurrentOperatorRevision :one
SELECT id, station_id, cnpj, source, source_reference, valid_from, valid_to
FROM station_operator_revisions
WHERE station_id = $1 AND valid_to IS NULL
ORDER BY valid_from DESC
LIMIT 1
`

func (q *Queries) CurrentOperatorRevision(ctx context.Context, stationID pgtype.UUID) (StationOperatorRevision, error) {
	row := q.db.QueryRow(ctx, currentOperatorRevision, stationID)
	var i StationOperatorRevision
	err := row.Scan(
		&i.ID,
		&i.StationID,
		&i.Cnpj,
		&i.Source,
		&i.SourceReference,
		&i.ValidFrom,
		&i.ValidTo,
	)
	return i, err
}

const ensureUnclaimedProfile = `-- name: EnsureUnclaimedProfile :one

INSERT INTO station_profiles (station_id, policy_version, projection)
VALUES ($1, $2, '{}')
ON CONFLICT (station_id) DO NOTHING
RETURNING station_id, policy_version, projection, revision, updated_at
`

type EnsureUnclaimedProfileParams struct {
	StationID     pgtype.UUID `json:"station_id"`
	PolicyVersion string      `json:"policy_version"`
}

// Owned by stationprofile (P30-T02). The profile is a read-only
// public projection over the canonical Directory station: no second
// identity, no private proof/person data, no grant implication.
// Operator revisions link station to effective CNPJ with validity;
// only one open revision per station (partial unique index).
func (q *Queries) EnsureUnclaimedProfile(ctx context.Context, arg EnsureUnclaimedProfileParams) (StationProfile, error) {
	row := q.db.QueryRow(ctx, ensureUnclaimedProfile, arg.StationID, arg.PolicyVersion)
	var i StationProfile
	err := row.Scan(
		&i.StationID,
		&i.PolicyVersion,
		&i.Projection,
		&i.Revision,
		&i.UpdatedAt,
	)
	return i, err
}

const getProfile = `-- name: GetProfile :one
SELECT station_id, policy_version, projection, revision, updated_at
FROM station_profiles
WHERE station_id = $1
`

func (q *Queries) GetProfile(ctx context.Context, stationID pgtype.UUID) (StationProfile, error) {
	row := q.db.QueryRow(ctx, getProfile, stationID)
	var i StationProfile
	err := row.Scan(
		&i.StationID,
		&i.PolicyVersion,
		&i.Projection,
		&i.Revision,
		&i.UpdatedAt,
	)
	return i, err
}

const recordOperatorRevision = `-- name: RecordOperatorRevision :one
INSERT INTO station_operator_revisions (id, station_id, cnpj, source, source_reference)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, station_id, cnpj, source, source_reference, valid_from, valid_to
`

type RecordOperatorRevisionParams struct {
	ID              pgtype.UUID `json:"id"`
	StationID       pgtype.UUID `json:"station_id"`
	Cnpj            string      `json:"cnpj"`
	Source          string      `json:"source"`
	SourceReference string      `json:"source_reference"`
}

func (q *Queries) RecordOperatorRevision(ctx context.Context, arg RecordOperatorRevisionParams) (StationOperatorRevision, error) {
	row := q.db.QueryRow(ctx, recordOperatorRevision,
		arg.ID,
		arg.StationID,
		arg.Cnpj,
		arg.Source,
		arg.SourceReference,
	)
	var i StationOperatorRevision
	err := row.Scan(
		&i.ID,
		&i.StationID,
		&i.Cnpj,
		&i.Source,
		&i.SourceReference,
		&i.ValidFrom,
		&i.ValidTo,
	)
	return i, err
}
