// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: proofs.sql

package stationprofile

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProof = `-- name: CreateProof :one

INSERT INTO claim_proofs (id, claim_id, declaration_id, sha256, bytes_size, format, evidence_kind, object_key, expires_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (declaration_id) WHERE status NOT IN ('rejected', 'deleted') DO NOTHING
RETURNING id, claim_id, declaration_id, sha256, bytes_size, format, evidence_kind, object_key, status, expires_at, created_at
`

type CreateProofParams struct {
	ID            pgtype.UUID        `json:"id"`
	ClaimID       pgtype.UUID        `json:"claim_id"`
	DeclarationID pgtype.UUID        `json:"declaration_id"`
	Sha256        string             `json:"sha256"`
	BytesSize     int64              `json:"bytes_size"`
	Format        string             `json:"format"`
	EvidenceKind  string             `json:"evidence_kind"`
	ObjectKey     string             `json:"object_key"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
}

// Owned by stationprofile (proof intake, P30-T04). Hash-bound
// immutable metadata; bytes live in private object storage behind
// server-generated keys. One proof binds per declaration; expiry and
// deletion purge bytes while rows stay as audit.
func (q *Queries) CreateProof(ctx context.Context, arg CreateProofParams) (ClaimProof, error) {
	row := q.db.QueryRow(ctx, createProof,
		arg.ID,
		arg.ClaimID,
		arg.DeclarationID,
		arg.Sha256,
		arg.BytesSize,
		arg.Format,
		arg.EvidenceKind,
		arg.ObjectKey,
		arg.ExpiresAt,
	)
	var i ClaimProof
	err := row.Scan(
		&i.ID,
		&i.ClaimID,
		&i.DeclarationID,
		&i.Sha256,
		&i.BytesSize,
		&i.Format,
		&i.EvidenceKind,
		&i.ObjectKey,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getProofByHash = `-- name: GetProofByHash :one
SELECT id, claim_id, declaration_id, sha256, bytes_size, format, evidence_kind, object_key, status, expires_at, created_at
FROM claim_proofs
WHERE claim_id = $1 AND sha256 = $2 AND status NOT IN ('rejected', 'deleted')
`

type GetProofByHashParams struct {
	ClaimID pgtype.UUID `json:"claim_id"`
	Sha256  string      `json:"sha256"`
}

func (q *Queries) GetProofByHash(ctx context.Context, arg GetProofByHashParams) (ClaimProof, error) {
	row := q.db.QueryRow(ctx, getProofByHash, arg.ClaimID, arg.Sha256)
	var i ClaimProof
	err := row.Scan(
		&i.ID,
		&i.ClaimID,
		&i.DeclarationID,
		&i.Sha256,
		&i.BytesSize,
		&i.Format,
		&i.EvidenceKind,
		&i.ObjectKey,
		&i.Status,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const listExpiredProofs = `-- name: ListExpiredProofs :many
SELECT id, claim_id, declaration_id, sha256, bytes_size, format, evidence_kind, object_key, status, expires_at, created_at
FROM claim_proofs
WHERE status NOT IN ('expired', 'deleted') AND expires_at <= now()
ORDER BY expires_at ASC
LIMIT $1::int
`

func (q *Queries) ListExpiredProofs(ctx context.Context, pageLimit int32) ([]ClaimProof, error) {
	rows, err := q.db.Query(ctx, listExpiredProofs, pageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ClaimProof
	for rows.Next() {
		var i ClaimProof
		if err := rows.Scan(
			&i.ID,
			&i.ClaimID,
			&i.DeclarationID,
			&i.Sha256,
			&i.BytesSize,
			&i.Format,
			&i.EvidenceKind,
			&i.ObjectKey,
			&i.Status,
			&i.ExpiresAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markProofDeleted = `-- name: MarkProofDeleted :execrows
UPDATE claim_proofs
SET status = 'deleted'
WHERE id = $1 AND status NOT IN ('deleted')
`

func (q *Queries) MarkProofDeleted(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markProofDeleted, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markProofExpired = `-- name: MarkProofExpired :execrows
UPDATE claim_proofs
SET status = 'expired'
WHERE id = $1 AND status NOT IN ('expired', 'deleted')
`

func (q *Queries) MarkProofExpired(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markProofExpired, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
