// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package directory

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type DirectoryIdentifier struct {
	ID               pgtype.UUID        `json:"id"`
	StationID        pgtype.UUID        `json:"station_id"`
	Kind             string             `json:"kind"`
	NormalizedValue  string             `json:"normalized_value"`
	ValidFrom        pgtype.Timestamptz `json:"valid_from"`
	ValidTo          pgtype.Timestamptz `json:"valid_to"`
	SourceRevisionID pgtype.Text        `json:"source_revision_id"`
}

type DirectoryLocationRevision struct {
	ID              pgtype.UUID        `json:"id"`
	StationID       pgtype.UUID        `json:"station_id"`
	Point           interface{}        `json:"point"`
	Quality         string             `json:"quality"`
	Provider        string             `json:"provider"`
	SourceReference string             `json:"source_reference"`
	ObtainedAt      pgtype.Timestamptz `json:"obtained_at"`
	SupersedesID    pgtype.UUID        `json:"supersedes_id"`
}

type DirectoryStation struct {
	ID                pgtype.UUID        `json:"id"`
	DisplayName       string             `json:"display_name"`
	Address           []byte             `json:"address"`
	MunicipalityCode  pgtype.Text        `json:"municipality_code"`
	State             pgtype.Text        `json:"state"`
	Status            string             `json:"status"`
	CurrentPoint      interface{}        `json:"current_point"`
	CurrentQuality    pgtype.Text        `json:"current_quality"`
	CurrentRevisionID pgtype.UUID        `json:"current_revision_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}
