// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: registry.sql

package directory

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countCompleteRegistryRuns = `-- name: CountCompleteRegistryRuns :one
SELECT count(*) FROM registry_source_runs WHERE source = $1 AND state = 'complete'
`

func (q *Queries) CountCompleteRegistryRuns(ctx context.Context, source string) (int64, error) {
	row := q.db.QueryRow(ctx, countCompleteRegistryRuns, source)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRegistryAssertions = `-- name: CountRegistryAssertions :one
SELECT count(*) FROM registry_assertions WHERE run_id = $1
`

func (q *Queries) CountRegistryAssertions(ctx context.Context, runID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRegistryAssertions, runID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRegistryRun = `-- name: CreateRegistryRun :one

INSERT INTO registry_source_runs (id, source, snapshot_identity, checksum, parser_version)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (source, snapshot_identity) DO NOTHING
RETURNING id, source, snapshot_identity, checksum, parser_version, state,
    accepted, duplicates, rejected, error_code, started_at, finished_at
`

type CreateRegistryRunParams struct {
	ID               pgtype.UUID `json:"id"`
	Source           string      `json:"source"`
	SnapshotIdentity string      `json:"snapshot_identity"`
	Checksum         string      `json:"checksum"`
	ParserVersion    string      `json:"parser_version"`
}

// Owned by directory (registry staging, P25-T02). Staging only: publishers
// read complete runs in P25-T04; failed/quarantined runs stay invisible.
func (q *Queries) CreateRegistryRun(ctx context.Context, arg CreateRegistryRunParams) (RegistrySourceRun, error) {
	row := q.db.QueryRow(ctx, createRegistryRun,
		arg.ID,
		arg.Source,
		arg.SnapshotIdentity,
		arg.Checksum,
		arg.ParserVersion,
	)
	var i RegistrySourceRun
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.SnapshotIdentity,
		&i.Checksum,
		&i.ParserVersion,
		&i.State,
		&i.Accepted,
		&i.Duplicates,
		&i.Rejected,
		&i.ErrorCode,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const finishRegistryRun = `-- name: FinishRegistryRun :execrows
UPDATE registry_source_runs
SET state = $1, accepted = $2, duplicates = $3,
    rejected = $4, error_code = $5, finished_at = now()
WHERE id = $6 AND state = 'running'
`

type FinishRegistryRunParams struct {
	State      string      `json:"state"`
	Accepted   int64       `json:"accepted"`
	Duplicates int64       `json:"duplicates"`
	Rejected   int64       `json:"rejected"`
	ErrorCode  string      `json:"error_code"`
	ID         pgtype.UUID `json:"id"`
}

func (q *Queries) FinishRegistryRun(ctx context.Context, arg FinishRegistryRunParams) (int64, error) {
	result, err := q.db.Exec(ctx, finishRegistryRun,
		arg.State,
		arg.Accepted,
		arg.Duplicates,
		arg.Rejected,
		arg.ErrorCode,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getRegistryRun = `-- name: GetRegistryRun :one
SELECT id, source, snapshot_identity, checksum, parser_version, state,
    accepted, duplicates, rejected, error_code, started_at, finished_at
FROM registry_source_runs
WHERE source = $1 AND snapshot_identity = $2
`

type GetRegistryRunParams struct {
	Source           string `json:"source"`
	SnapshotIdentity string `json:"snapshot_identity"`
}

func (q *Queries) GetRegistryRun(ctx context.Context, arg GetRegistryRunParams) (RegistrySourceRun, error) {
	row := q.db.QueryRow(ctx, getRegistryRun, arg.Source, arg.SnapshotIdentity)
	var i RegistrySourceRun
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.SnapshotIdentity,
		&i.Checksum,
		&i.ParserVersion,
		&i.State,
		&i.Accepted,
		&i.Duplicates,
		&i.Rejected,
		&i.ErrorCode,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const stageRegistryAssertion = `-- name: StageRegistryAssertion :one
INSERT INTO registry_assertions (
    id, run_id, source, source_key, checksum, display_name, address,
    municipality_code, state, auth_state, operation, eligibility,
    location_quality, source_reference, effective_date
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11,
    $12, $13, $14, $15
)
ON CONFLICT (source, source_key, checksum) DO NOTHING
RETURNING id
`

type StageRegistryAssertionParams struct {
	ID               pgtype.UUID `json:"id"`
	RunID            pgtype.UUID `json:"run_id"`
	Source           string      `json:"source"`
	SourceKey        string      `json:"source_key"`
	Checksum         string      `json:"checksum"`
	DisplayName      string      `json:"display_name"`
	Address          []byte      `json:"address"`
	MunicipalityCode pgtype.Text `json:"municipality_code"`
	State            pgtype.Text `json:"state"`
	AuthState        string      `json:"auth_state"`
	Operation        string      `json:"operation"`
	Eligibility      string      `json:"eligibility"`
	LocationQuality  string      `json:"location_quality"`
	SourceReference  string      `json:"source_reference"`
	EffectiveDate    pgtype.Date `json:"effective_date"`
}

func (q *Queries) StageRegistryAssertion(ctx context.Context, arg StageRegistryAssertionParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, stageRegistryAssertion,
		arg.ID,
		arg.RunID,
		arg.Source,
		arg.SourceKey,
		arg.Checksum,
		arg.DisplayName,
		arg.Address,
		arg.MunicipalityCode,
		arg.State,
		arg.AuthState,
		arg.Operation,
		arg.Eligibility,
		arg.LocationQuality,
		arg.SourceReference,
		arg.EffectiveDate,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
