// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: registry.sql

package directory

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const attachPreparedAssertion = `-- name: AttachPreparedAssertion :one
INSERT INTO registry_run_assertions (run_id, assertion_id, supersedes_checksum)
SELECT $1, a.id, $2 FROM registry_assertions a
WHERE a.source = 'station-prep' AND a.source_key = $3 AND a.checksum = $4
ON CONFLICT (run_id, assertion_id) DO NOTHING
RETURNING assertion_id
`

type AttachPreparedAssertionParams struct {
	RunID              pgtype.UUID `json:"run_id"`
	SupersedesChecksum string      `json:"supersedes_checksum"`
	SourceKey          string      `json:"source_key"`
	Checksum           string      `json:"checksum"`
}

func (q *Queries) AttachPreparedAssertion(ctx context.Context, arg AttachPreparedAssertionParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, attachPreparedAssertion,
		arg.RunID,
		arg.SupersedesChecksum,
		arg.SourceKey,
		arg.Checksum,
	)
	var assertion_id pgtype.UUID
	err := row.Scan(&assertion_id)
	return assertion_id, err
}

const bindPreparedManifest = `-- name: BindPreparedManifest :one
UPDATE registry_source_runs SET prepared_manifest_sha256 = $1
WHERE id = $2 AND checksum = $3
  AND (prepared_manifest_sha256 = '' OR prepared_manifest_sha256 = $1)
RETURNING id
`

type BindPreparedManifestParams struct {
	ManifestSha256 string      `json:"manifest_sha256"`
	ID             pgtype.UUID `json:"id"`
	Checksum       string      `json:"checksum"`
}

func (q *Queries) BindPreparedManifest(ctx context.Context, arg BindPreparedManifestParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, bindPreparedManifest, arg.ManifestSha256, arg.ID, arg.Checksum)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const cancelSuggestion = `-- name: CancelSuggestion :execrows
UPDATE station_suggestions
SET state = 'cancelled'
WHERE id = $1 AND account_id = $2 AND state = 'pending'
`

type CancelSuggestionParams struct {
	ID        pgtype.UUID `json:"id"`
	AccountID pgtype.UUID `json:"account_id"`
}

func (q *Queries) CancelSuggestion(ctx context.Context, arg CancelSuggestionParams) (int64, error) {
	result, err := q.db.Exec(ctx, cancelSuggestion, arg.ID, arg.AccountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countCompleteRegistryRuns = `-- name: CountCompleteRegistryRuns :one
SELECT count(*) FROM registry_source_runs WHERE source = $1 AND state = 'complete'
`

func (q *Queries) CountCompleteRegistryRuns(ctx context.Context, source string) (int64, error) {
	row := q.db.QueryRow(ctx, countCompleteRegistryRuns, source)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPreparedPublicationRows = `-- name: CountPreparedPublicationRows :one
SELECT count(*) FROM registry_assertions a JOIN registry_run_assertions m ON m.assertion_id=a.id
WHERE m.run_id = $1 AND a.source='station-prep' AND a.municipality_code IS NOT NULL
  AND a.state IS NOT NULL AND a.latitude IS NULL AND a.longitude IS NULL AND a.superseded_by IS NULL
`

func (q *Queries) CountPreparedPublicationRows(ctx context.Context, runID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPreparedPublicationRows, runID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRecentSuggestions = `-- name: CountRecentSuggestions :one
SELECT count(*) FROM station_suggestions
WHERE account_id = $1 AND created_at > now() - make_interval(days => 1)
`

func (q *Queries) CountRecentSuggestions(ctx context.Context, accountID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentSuggestions, accountID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRegistryAssertions = `-- name: CountRegistryAssertions :one
SELECT count(*) FROM registry_assertions WHERE run_id = $1
`

func (q *Queries) CountRegistryAssertions(ctx context.Context, runID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRegistryAssertions, runID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnpublishedPreparedRows = `-- name: CountUnpublishedPreparedRows :one
SELECT count(*) FROM registry_assertions a JOIN registry_run_assertions m ON m.assertion_id=a.id
WHERE m.run_id = $1 AND a.source='station-prep' AND a.municipality_code IS NOT NULL
  AND a.state IS NOT NULL AND a.latitude IS NULL AND a.longitude IS NULL
  AND a.superseded_by IS NULL AND (a.station_id IS NULL OR EXISTS (
 SELECT 1 FROM directory_stations s WHERE s.id=a.station_id AND
 (s.display_name IS DISTINCT FROM a.display_name OR s.address IS DISTINCT FROM a.address
 OR s.municipality_code IS DISTINCT FROM a.municipality_code OR s.state IS DISTINCT FROM a.state)))
`

func (q *Queries) CountUnpublishedPreparedRows(ctx context.Context, runID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countUnpublishedPreparedRows, runID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDecision = `-- name: CreateDecision :one

INSERT INTO suggestion_decisions (id, suggestion_id, decision, reason, reviewer, station_id)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, suggestion_id, decision, reason, reviewer, station_id, decided_at
`

type CreateDecisionParams struct {
	ID           pgtype.UUID `json:"id"`
	SuggestionID pgtype.UUID `json:"suggestion_id"`
	Decision     string      `json:"decision"`
	Reason       string      `json:"reason"`
	Reviewer     string      `json:"reviewer"`
	StationID    pgtype.UUID `json:"station_id"`
}

// Owned by directory (suggestion review, P27-T02). Audited decisions:
// only pending suggestions transition; concurrent reviewers converge
// on the SQL guard instead of overwriting.
func (q *Queries) CreateDecision(ctx context.Context, arg CreateDecisionParams) (SuggestionDecision, error) {
	row := q.db.QueryRow(ctx, createDecision,
		arg.ID,
		arg.SuggestionID,
		arg.Decision,
		arg.Reason,
		arg.Reviewer,
		arg.StationID,
	)
	var i SuggestionDecision
	err := row.Scan(
		&i.ID,
		&i.SuggestionID,
		&i.Decision,
		&i.Reason,
		&i.Reviewer,
		&i.StationID,
		&i.DecidedAt,
	)
	return i, err
}

const createRegistryRun = `-- name: CreateRegistryRun :one

INSERT INTO registry_source_runs (id, source, snapshot_identity, checksum, parser_version)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (source, snapshot_identity) DO NOTHING
RETURNING id, source, snapshot_identity, checksum, parser_version, state,
    accepted, duplicates, rejected, error_code, started_at, finished_at
`

type CreateRegistryRunParams struct {
	ID               pgtype.UUID `json:"id"`
	Source           string      `json:"source"`
	SnapshotIdentity string      `json:"snapshot_identity"`
	Checksum         string      `json:"checksum"`
	ParserVersion    string      `json:"parser_version"`
}

type CreateRegistryRunRow struct {
	ID               pgtype.UUID        `json:"id"`
	Source           string             `json:"source"`
	SnapshotIdentity string             `json:"snapshot_identity"`
	Checksum         string             `json:"checksum"`
	ParserVersion    string             `json:"parser_version"`
	State            string             `json:"state"`
	Accepted         int64              `json:"accepted"`
	Duplicates       int64              `json:"duplicates"`
	Rejected         int64              `json:"rejected"`
	ErrorCode        string             `json:"error_code"`
	StartedAt        pgtype.Timestamptz `json:"started_at"`
	FinishedAt       pgtype.Timestamptz `json:"finished_at"`
}

// Owned by directory (registry staging, P25-T02). Staging only: publishers
// read complete runs in P25-T04; failed/quarantined runs stay invisible.
func (q *Queries) CreateRegistryRun(ctx context.Context, arg CreateRegistryRunParams) (CreateRegistryRunRow, error) {
	row := q.db.QueryRow(ctx, createRegistryRun,
		arg.ID,
		arg.Source,
		arg.SnapshotIdentity,
		arg.Checksum,
		arg.ParserVersion,
	)
	var i CreateRegistryRunRow
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.SnapshotIdentity,
		&i.Checksum,
		&i.ParserVersion,
		&i.State,
		&i.Accepted,
		&i.Duplicates,
		&i.Rejected,
		&i.ErrorCode,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const createSuggestion = `-- name: CreateSuggestion :one

INSERT INTO station_suggestions (id, account_id, client_submission_id, proposal, evidence_ref)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (account_id, client_submission_id) DO NOTHING
RETURNING id, account_id, client_submission_id, proposal, evidence_ref,
    state, created_at, decided_at
`

type CreateSuggestionParams struct {
	ID                 pgtype.UUID `json:"id"`
	AccountID          pgtype.UUID `json:"account_id"`
	ClientSubmissionID string      `json:"client_submission_id"`
	Proposal           []byte      `json:"proposal"`
	EvidenceRef        string      `json:"evidence_ref"`
}

// Owned by directory (station suggestions, P27-T01). Private intake:
// one row per owner idempotency key; owner-only reads; decisions land
// in T02 (approved/rejected), cancellation stays owner-side.
func (q *Queries) CreateSuggestion(ctx context.Context, arg CreateSuggestionParams) (StationSuggestion, error) {
	row := q.db.QueryRow(ctx, createSuggestion,
		arg.ID,
		arg.AccountID,
		arg.ClientSubmissionID,
		arg.Proposal,
		arg.EvidenceRef,
	)
	var i StationSuggestion
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.ClientSubmissionID,
		&i.Proposal,
		&i.EvidenceRef,
		&i.State,
		&i.CreatedAt,
		&i.DecidedAt,
	)
	return i, err
}

const decideSuggestion = `-- name: DecideSuggestion :execrows
UPDATE station_suggestions
SET state = $1, decided_at = now()
WHERE id = $2 AND state = 'pending'
`

type DecideSuggestionParams struct {
	State string      `json:"state"`
	ID    pgtype.UUID `json:"id"`
}

func (q *Queries) DecideSuggestion(ctx context.Context, arg DecideSuggestionParams) (int64, error) {
	result, err := q.db.Exec(ctx, decideSuggestion, arg.State, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findOfficialAssertion = `-- name: FindOfficialAssertion :one
SELECT a.source, a.source_key, a.display_name, a.municipality_code, a.state,
    a.auth_state, a.eligibility, r.finished_at AS run_finished_at
FROM registry_assertions AS a
JOIN registry_source_runs AS r ON r.id = a.run_id
WHERE a.source_key = $1
  AND a.source IN ('registry-csv', 'registry-api')
  AND r.state = 'complete'
ORDER BY r.finished_at DESC NULLS LAST, r.started_at DESC
LIMIT 1
`

type FindOfficialAssertionRow struct {
	Source           string             `json:"source"`
	SourceKey        string             `json:"source_key"`
	DisplayName      string             `json:"display_name"`
	MunicipalityCode pgtype.Text        `json:"municipality_code"`
	State            pgtype.Text        `json:"state"`
	AuthState        string             `json:"auth_state"`
	Eligibility      string             `json:"eligibility"`
	RunFinishedAt    pgtype.Timestamptz `json:"run_finished_at"`
}

func (q *Queries) FindOfficialAssertion(ctx context.Context, sourceKey string) (FindOfficialAssertionRow, error) {
	row := q.db.QueryRow(ctx, findOfficialAssertion, sourceKey)
	var i FindOfficialAssertionRow
	err := row.Scan(
		&i.Source,
		&i.SourceKey,
		&i.DisplayName,
		&i.MunicipalityCode,
		&i.State,
		&i.AuthState,
		&i.Eligibility,
		&i.RunFinishedAt,
	)
	return i, err
}

const finishRegistryRun = `-- name: FinishRegistryRun :execrows
UPDATE registry_source_runs
SET state = $1, accepted = $2, duplicates = $3,
    rejected = $4, error_code = $5, finished_at = now()
WHERE id = $6 AND state = 'running'
`

type FinishRegistryRunParams struct {
	State      string      `json:"state"`
	Accepted   int64       `json:"accepted"`
	Duplicates int64       `json:"duplicates"`
	Rejected   int64       `json:"rejected"`
	ErrorCode  string      `json:"error_code"`
	ID         pgtype.UUID `json:"id"`
}

func (q *Queries) FinishRegistryRun(ctx context.Context, arg FinishRegistryRunParams) (int64, error) {
	result, err := q.db.Exec(ctx, finishRegistryRun,
		arg.State,
		arg.Accepted,
		arg.Duplicates,
		arg.Rejected,
		arg.ErrorCode,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getPreparedMembership = `-- name: GetPreparedMembership :one
SELECT m.assertion_id FROM registry_run_assertions m
JOIN registry_assertions a ON a.id=m.assertion_id
WHERE m.run_id = $1 AND a.source='station-prep' AND a.source_key = $2
 AND a.checksum = $3 AND m.supersedes_checksum = $4
`

type GetPreparedMembershipParams struct {
	RunID              pgtype.UUID `json:"run_id"`
	SourceKey          string      `json:"source_key"`
	Checksum           string      `json:"checksum"`
	SupersedesChecksum string      `json:"supersedes_checksum"`
}

func (q *Queries) GetPreparedMembership(ctx context.Context, arg GetPreparedMembershipParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getPreparedMembership,
		arg.RunID,
		arg.SourceKey,
		arg.Checksum,
		arg.SupersedesChecksum,
	)
	var assertion_id pgtype.UUID
	err := row.Scan(&assertion_id)
	return assertion_id, err
}

const getPreparedRunBinding = `-- name: GetPreparedRunBinding :one
SELECT prepared_manifest_sha256 FROM registry_source_runs
WHERE id = $1 AND source = 'station-prep' AND state = 'complete'
`

func (q *Queries) GetPreparedRunBinding(ctx context.Context, id pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getPreparedRunBinding, id)
	var prepared_manifest_sha256 string
	err := row.Scan(&prepared_manifest_sha256)
	return prepared_manifest_sha256, err
}

const getRegistryRun = `-- name: GetRegistryRun :one
SELECT id, source, snapshot_identity, checksum, parser_version, state,
    accepted, duplicates, rejected, error_code, started_at, finished_at
FROM registry_source_runs
WHERE source = $1 AND snapshot_identity = $2
`

type GetRegistryRunParams struct {
	Source           string `json:"source"`
	SnapshotIdentity string `json:"snapshot_identity"`
}

type GetRegistryRunRow struct {
	ID               pgtype.UUID        `json:"id"`
	Source           string             `json:"source"`
	SnapshotIdentity string             `json:"snapshot_identity"`
	Checksum         string             `json:"checksum"`
	ParserVersion    string             `json:"parser_version"`
	State            string             `json:"state"`
	Accepted         int64              `json:"accepted"`
	Duplicates       int64              `json:"duplicates"`
	Rejected         int64              `json:"rejected"`
	ErrorCode        string             `json:"error_code"`
	StartedAt        pgtype.Timestamptz `json:"started_at"`
	FinishedAt       pgtype.Timestamptz `json:"finished_at"`
}

func (q *Queries) GetRegistryRun(ctx context.Context, arg GetRegistryRunParams) (GetRegistryRunRow, error) {
	row := q.db.QueryRow(ctx, getRegistryRun, arg.Source, arg.SnapshotIdentity)
	var i GetRegistryRunRow
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.SnapshotIdentity,
		&i.Checksum,
		&i.ParserVersion,
		&i.State,
		&i.Accepted,
		&i.Duplicates,
		&i.Rejected,
		&i.ErrorCode,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getRegistryRunByID = `-- name: GetRegistryRunByID :one
SELECT id, source, snapshot_identity, checksum, parser_version, state,
    accepted, duplicates, rejected, error_code, started_at, finished_at
FROM registry_source_runs
WHERE id = $1
`

type GetRegistryRunByIDRow struct {
	ID               pgtype.UUID        `json:"id"`
	Source           string             `json:"source"`
	SnapshotIdentity string             `json:"snapshot_identity"`
	Checksum         string             `json:"checksum"`
	ParserVersion    string             `json:"parser_version"`
	State            string             `json:"state"`
	Accepted         int64              `json:"accepted"`
	Duplicates       int64              `json:"duplicates"`
	Rejected         int64              `json:"rejected"`
	ErrorCode        string             `json:"error_code"`
	StartedAt        pgtype.Timestamptz `json:"started_at"`
	FinishedAt       pgtype.Timestamptz `json:"finished_at"`
}

func (q *Queries) GetRegistryRunByID(ctx context.Context, id pgtype.UUID) (GetRegistryRunByIDRow, error) {
	row := q.db.QueryRow(ctx, getRegistryRunByID, id)
	var i GetRegistryRunByIDRow
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.SnapshotIdentity,
		&i.Checksum,
		&i.ParserVersion,
		&i.State,
		&i.Accepted,
		&i.Duplicates,
		&i.Rejected,
		&i.ErrorCode,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getReviewEvidence = `-- name: GetReviewEvidence :one

SELECT a.id, a.run_id, a.source, a.source_key, a.checksum, a.display_name,
    a.address, a.municipality_code, a.state, a.auth_state, a.operation,
    a.eligibility, a.location_quality, a.source_reference, a.latitude,
    a.longitude, a.crs, a.station_id, a.effective_date, r.state AS run_state
FROM registry_assertions AS a
JOIN registry_source_runs AS r ON r.id = a.run_id
WHERE a.id = $1
`

type GetReviewEvidenceRow struct {
	ID               pgtype.UUID   `json:"id"`
	RunID            pgtype.UUID   `json:"run_id"`
	Source           string        `json:"source"`
	SourceKey        string        `json:"source_key"`
	Checksum         string        `json:"checksum"`
	DisplayName      string        `json:"display_name"`
	Address          []byte        `json:"address"`
	MunicipalityCode pgtype.Text   `json:"municipality_code"`
	State            pgtype.Text   `json:"state"`
	AuthState        string        `json:"auth_state"`
	Operation        string        `json:"operation"`
	Eligibility      string        `json:"eligibility"`
	LocationQuality  string        `json:"location_quality"`
	SourceReference  string        `json:"source_reference"`
	Latitude         pgtype.Float8 `json:"latitude"`
	Longitude        pgtype.Float8 `json:"longitude"`
	Crs              string        `json:"crs"`
	StationID        pgtype.UUID   `json:"station_id"`
	EffectiveDate    pgtype.Date   `json:"effective_date"`
	RunState         string        `json:"run_state"`
}

// Owned by directory (location review, RST-06). The CRS transform stays
// inside PostGIS/PROJ: Go plumbs coordinates, never math. Unknown CRS
// names fail at the Go gate before reaching SQL.
func (q *Queries) GetReviewEvidence(ctx context.Context, id pgtype.UUID) (GetReviewEvidenceRow, error) {
	row := q.db.QueryRow(ctx, getReviewEvidence, id)
	var i GetReviewEvidenceRow
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Source,
		&i.SourceKey,
		&i.Checksum,
		&i.DisplayName,
		&i.Address,
		&i.MunicipalityCode,
		&i.State,
		&i.AuthState,
		&i.Operation,
		&i.Eligibility,
		&i.LocationQuality,
		&i.SourceReference,
		&i.Latitude,
		&i.Longitude,
		&i.Crs,
		&i.StationID,
		&i.EffectiveDate,
		&i.RunState,
	)
	return i, err
}

const getSuggestion = `-- name: GetSuggestion :one
SELECT id, account_id, client_submission_id, proposal, evidence_ref,
    state, created_at, decided_at
FROM station_suggestions
WHERE id = $1
`

func (q *Queries) GetSuggestion(ctx context.Context, id pgtype.UUID) (StationSuggestion, error) {
	row := q.db.QueryRow(ctx, getSuggestion, id)
	var i StationSuggestion
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.ClientSubmissionID,
		&i.Proposal,
		&i.EvidenceRef,
		&i.State,
		&i.CreatedAt,
		&i.DecidedAt,
	)
	return i, err
}

const getSuggestionByKey = `-- name: GetSuggestionByKey :one
SELECT id, account_id, client_submission_id, proposal, evidence_ref,
    state, created_at, decided_at
FROM station_suggestions
WHERE account_id = $1 AND client_submission_id = $2
`

type GetSuggestionByKeyParams struct {
	AccountID          pgtype.UUID `json:"account_id"`
	ClientSubmissionID string      `json:"client_submission_id"`
}

func (q *Queries) GetSuggestionByKey(ctx context.Context, arg GetSuggestionByKeyParams) (StationSuggestion, error) {
	row := q.db.QueryRow(ctx, getSuggestionByKey, arg.AccountID, arg.ClientSubmissionID)
	var i StationSuggestion
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.ClientSubmissionID,
		&i.Proposal,
		&i.EvidenceRef,
		&i.State,
		&i.CreatedAt,
		&i.DecidedAt,
	)
	return i, err
}

const lastCompleteRegistryRun = `-- name: LastCompleteRegistryRun :one
SELECT id, source, snapshot_identity, checksum, parser_version, state,
    accepted, duplicates, rejected, error_code, started_at, finished_at
FROM registry_source_runs
WHERE source = $1 AND state = 'complete'
ORDER BY finished_at DESC NULLS LAST, started_at DESC
LIMIT 1
`

type LastCompleteRegistryRunRow struct {
	ID               pgtype.UUID        `json:"id"`
	Source           string             `json:"source"`
	SnapshotIdentity string             `json:"snapshot_identity"`
	Checksum         string             `json:"checksum"`
	ParserVersion    string             `json:"parser_version"`
	State            string             `json:"state"`
	Accepted         int64              `json:"accepted"`
	Duplicates       int64              `json:"duplicates"`
	Rejected         int64              `json:"rejected"`
	ErrorCode        string             `json:"error_code"`
	StartedAt        pgtype.Timestamptz `json:"started_at"`
	FinishedAt       pgtype.Timestamptz `json:"finished_at"`
}

func (q *Queries) LastCompleteRegistryRun(ctx context.Context, source string) (LastCompleteRegistryRunRow, error) {
	row := q.db.QueryRow(ctx, lastCompleteRegistryRun, source)
	var i LastCompleteRegistryRunRow
	err := row.Scan(
		&i.ID,
		&i.Source,
		&i.SnapshotIdentity,
		&i.Checksum,
		&i.ParserVersion,
		&i.State,
		&i.Accepted,
		&i.Duplicates,
		&i.Rejected,
		&i.ErrorCode,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const linkPreparedSupersedes = `-- name: LinkPreparedSupersedes :execrows
UPDATE registry_assertions older SET superseded_by = newer.id
FROM registry_run_assertions m, registry_assertions newer, registry_run_assertions n
WHERE m.run_id = $1 AND m.assertion_id = older.id
  AND m.supersedes_checksum <> '' AND newer.checksum = m.supersedes_checksum
  AND newer.source_key = older.source_key AND n.run_id = m.run_id AND n.assertion_id = newer.id
  AND older.superseded_by IS NULL AND older.id <> newer.id
`

func (q *Queries) LinkPreparedSupersedes(ctx context.Context, runID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, linkPreparedSupersedes, runID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listOwnedSuggestions = `-- name: ListOwnedSuggestions :many
SELECT id, account_id, client_submission_id, proposal, evidence_ref,
    state, created_at, decided_at
FROM station_suggestions
WHERE account_id = $1
ORDER BY created_at DESC
LIMIT $3::int OFFSET $2::int
`

type ListOwnedSuggestionsParams struct {
	AccountID  pgtype.UUID `json:"account_id"`
	PageOffset int32       `json:"page_offset"`
	PageLimit  int32       `json:"page_limit"`
}

func (q *Queries) ListOwnedSuggestions(ctx context.Context, arg ListOwnedSuggestionsParams) ([]StationSuggestion, error) {
	rows, err := q.db.Query(ctx, listOwnedSuggestions, arg.AccountID, arg.PageOffset, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StationSuggestion
	for rows.Next() {
		var i StationSuggestion
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.ClientSubmissionID,
			&i.Proposal,
			&i.EvidenceRef,
			&i.State,
			&i.CreatedAt,
			&i.DecidedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingSuggestions = `-- name: ListPendingSuggestions :many
SELECT id, account_id, client_submission_id, proposal, evidence_ref,
    state, created_at, decided_at
FROM station_suggestions
WHERE state = 'pending'
ORDER BY created_at ASC
LIMIT $1::int
`

func (q *Queries) ListPendingSuggestions(ctx context.Context, pageLimit int32) ([]StationSuggestion, error) {
	rows, err := q.db.Query(ctx, listPendingSuggestions, pageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StationSuggestion
	for rows.Next() {
		var i StationSuggestion
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.ClientSubmissionID,
			&i.Proposal,
			&i.EvidenceRef,
			&i.State,
			&i.CreatedAt,
			&i.DecidedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPreparedRegistryPage = `-- name: ListPreparedRegistryPage :many
SELECT a.id, a.source_key, a.display_name, a.address, a.municipality_code, a.state
FROM registry_assertions a JOIN registry_run_assertions m ON m.assertion_id = a.id
WHERE m.run_id = $1 AND a.id > $2
  AND a.municipality_code IS NOT NULL AND a.state IS NOT NULL
  AND a.source = 'station-prep' AND a.latitude IS NULL AND a.longitude IS NULL
  AND a.superseded_by IS NULL AND (a.station_id IS NULL OR EXISTS (
 SELECT 1 FROM directory_stations s WHERE s.id=a.station_id AND
 (s.display_name IS DISTINCT FROM a.display_name OR s.address IS DISTINCT FROM a.address
 OR s.municipality_code IS DISTINCT FROM a.municipality_code OR s.state IS DISTINCT FROM a.state)))
ORDER BY a.id LIMIT 100
`

type ListPreparedRegistryPageParams struct {
	RunID   pgtype.UUID `json:"run_id"`
	AfterID pgtype.UUID `json:"after_id"`
}

type ListPreparedRegistryPageRow struct {
	ID               pgtype.UUID `json:"id"`
	SourceKey        string      `json:"source_key"`
	DisplayName      string      `json:"display_name"`
	Address          []byte      `json:"address"`
	MunicipalityCode pgtype.Text `json:"municipality_code"`
	State            pgtype.Text `json:"state"`
}

func (q *Queries) ListPreparedRegistryPage(ctx context.Context, arg ListPreparedRegistryPageParams) ([]ListPreparedRegistryPageRow, error) {
	rows, err := q.db.Query(ctx, listPreparedRegistryPage, arg.RunID, arg.AfterID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPreparedRegistryPageRow
	for rows.Next() {
		var i ListPreparedRegistryPageRow
		if err := rows.Scan(
			&i.ID,
			&i.SourceKey,
			&i.DisplayName,
			&i.Address,
			&i.MunicipalityCode,
			&i.State,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRegistryAssertions = `-- name: ListRegistryAssertions :many
SELECT id, run_id, source, source_key, checksum, display_name, address,
    municipality_code, state, auth_state, operation, eligibility,
    location_quality, source_reference, latitude, longitude, crs,
    station_id
FROM registry_assertions
WHERE registry_assertions.run_id = $1 OR EXISTS (SELECT 1 FROM registry_run_assertions AS m
    WHERE m.run_id = $1 AND m.assertion_id = registry_assertions.id)
ORDER BY source_key, checksum
`

type ListRegistryAssertionsRow struct {
	ID               pgtype.UUID   `json:"id"`
	RunID            pgtype.UUID   `json:"run_id"`
	Source           string        `json:"source"`
	SourceKey        string        `json:"source_key"`
	Checksum         string        `json:"checksum"`
	DisplayName      string        `json:"display_name"`
	Address          []byte        `json:"address"`
	MunicipalityCode pgtype.Text   `json:"municipality_code"`
	State            pgtype.Text   `json:"state"`
	AuthState        string        `json:"auth_state"`
	Operation        string        `json:"operation"`
	Eligibility      string        `json:"eligibility"`
	LocationQuality  string        `json:"location_quality"`
	SourceReference  string        `json:"source_reference"`
	Latitude         pgtype.Float8 `json:"latitude"`
	Longitude        pgtype.Float8 `json:"longitude"`
	Crs              string        `json:"crs"`
	StationID        pgtype.UUID   `json:"station_id"`
}

func (q *Queries) ListRegistryAssertions(ctx context.Context, runID pgtype.UUID) ([]ListRegistryAssertionsRow, error) {
	rows, err := q.db.Query(ctx, listRegistryAssertions, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRegistryAssertionsRow
	for rows.Next() {
		var i ListRegistryAssertionsRow
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.Source,
			&i.SourceKey,
			&i.Checksum,
			&i.DisplayName,
			&i.Address,
			&i.MunicipalityCode,
			&i.State,
			&i.AuthState,
			&i.Operation,
			&i.Eligibility,
			&i.LocationQuality,
			&i.SourceReference,
			&i.Latitude,
			&i.Longitude,
			&i.Crs,
			&i.StationID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const preparedDanglingSupersedes = `-- name: PreparedDanglingSupersedes :one
SELECT count(*) FROM registry_run_assertions m
JOIN registry_assertions older ON older.id = m.assertion_id
WHERE m.run_id = $1 AND m.supersedes_checksum <> '' AND NOT EXISTS (
 SELECT 1 FROM registry_run_assertions newer_membership
 JOIN registry_assertions newer ON newer.id = newer_membership.assertion_id
 WHERE newer_membership.run_id = m.run_id AND newer.source_key = older.source_key
   AND newer.checksum = m.supersedes_checksum
   AND newer.id <> older.id
   AND (older.superseded_by IS NULL OR older.superseded_by = newer.id)
)
`

func (q *Queries) PreparedDanglingSupersedes(ctx context.Context, runID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, preparedDanglingSupersedes, runID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const refreshPreparedStationFacts = `-- name: RefreshPreparedStationFacts :one
WITH refreshed AS (
 UPDATE directory_stations AS s
 SET display_name= $1, address= $2::jsonb
 WHERE s.id= $3 AND (s.display_name IS DISTINCT FROM $1 OR s.address IS DISTINCT FROM $2::jsonb)
   AND EXISTS (
    SELECT 1 FROM registry_assertions AS previous JOIN registry_source_runs AS r ON r.id=previous.run_id
    WHERE previous.station_id=s.id AND previous.source='station-prep'
      AND previous.display_name=s.display_name AND previous.address=s.address
      AND r.state='complete' AND r.prepared_manifest_sha256 IS NOT NULL
   )
 RETURNING s.id
)
SELECT id FROM refreshed
UNION ALL SELECT id FROM directory_stations WHERE id= $3 AND display_name= $1 AND address= $2::jsonb
LIMIT 1
`

type RefreshPreparedStationFactsParams struct {
	DisplayName string      `json:"display_name"`
	Address     []byte      `json:"address"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) RefreshPreparedStationFacts(ctx context.Context, arg RefreshPreparedStationFactsParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, refreshPreparedStationFacts, arg.DisplayName, arg.Address, arg.ID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const resumePreparedRun = `-- name: ResumePreparedRun :execrows
UPDATE registry_source_runs SET state = 'running', accepted = 0, duplicates = 0,
    rejected = 0, error_code = '', finished_at = NULL
WHERE id = $1 AND source = 'station-prep' AND state IN ('failed', 'running')
`

func (q *Queries) ResumePreparedRun(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, resumePreparedRun, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setAssertionStation = `-- name: SetAssertionStation :execrows
UPDATE registry_assertions
SET station_id = $1
WHERE id = $2 AND station_id IS NULL
`

type SetAssertionStationParams struct {
	StationID pgtype.UUID `json:"station_id"`
	ID        pgtype.UUID `json:"id"`
}

func (q *Queries) SetAssertionStation(ctx context.Context, arg SetAssertionStationParams) (int64, error) {
	result, err := q.db.Exec(ctx, setAssertionStation, arg.StationID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setAssertionSuperseded = `-- name: SetAssertionSuperseded :execrows
UPDATE registry_assertions
SET superseded_by = $1
WHERE id = $2 AND superseded_by IS NULL
`

type SetAssertionSupersededParams struct {
	SupersededBy pgtype.UUID `json:"superseded_by"`
	ID           pgtype.UUID `json:"id"`
}

func (q *Queries) SetAssertionSuperseded(ctx context.Context, arg SetAssertionSupersededParams) (int64, error) {
	result, err := q.db.Exec(ctx, setAssertionSuperseded, arg.SupersededBy, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setInitialRegistryLocality = `-- name: SetInitialRegistryLocality :one
UPDATE directory_stations
SET municipality_code = COALESCE(municipality_code, $1),
    state = COALESCE(state, $2)
WHERE id = $3
  AND (municipality_code IS NULL OR municipality_code = $1)
  AND (state IS NULL OR state = $2)
RETURNING id
`

type SetInitialRegistryLocalityParams struct {
	MunicipalityCode pgtype.Text `json:"municipality_code"`
	State            pgtype.Text `json:"state"`
	ID               pgtype.UUID `json:"id"`
}

func (q *Queries) SetInitialRegistryLocality(ctx context.Context, arg SetInitialRegistryLocalityParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, setInitialRegistryLocality, arg.MunicipalityCode, arg.State, arg.ID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const stageRegistryAssertion = `-- name: StageRegistryAssertion :one
INSERT INTO registry_assertions (
    id, run_id, source, source_key, checksum, display_name, address,
    municipality_code, state, auth_state, operation, eligibility,
    location_quality, source_reference, effective_date,
    latitude, longitude, crs
) VALUES (
    $1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10, $11,
    $12, $13, $14, $15,
    $16, $17, $18
)
ON CONFLICT (source, source_key, checksum) DO NOTHING
RETURNING id
`

type StageRegistryAssertionParams struct {
	ID               pgtype.UUID   `json:"id"`
	RunID            pgtype.UUID   `json:"run_id"`
	Source           string        `json:"source"`
	SourceKey        string        `json:"source_key"`
	Checksum         string        `json:"checksum"`
	DisplayName      string        `json:"display_name"`
	Address          []byte        `json:"address"`
	MunicipalityCode pgtype.Text   `json:"municipality_code"`
	State            pgtype.Text   `json:"state"`
	AuthState        string        `json:"auth_state"`
	Operation        string        `json:"operation"`
	Eligibility      string        `json:"eligibility"`
	LocationQuality  string        `json:"location_quality"`
	SourceReference  string        `json:"source_reference"`
	EffectiveDate    pgtype.Date   `json:"effective_date"`
	Latitude         pgtype.Float8 `json:"latitude"`
	Longitude        pgtype.Float8 `json:"longitude"`
	Crs              string        `json:"crs"`
}

func (q *Queries) StageRegistryAssertion(ctx context.Context, arg StageRegistryAssertionParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, stageRegistryAssertion,
		arg.ID,
		arg.RunID,
		arg.Source,
		arg.SourceKey,
		arg.Checksum,
		arg.DisplayName,
		arg.Address,
		arg.MunicipalityCode,
		arg.State,
		arg.AuthState,
		arg.Operation,
		arg.Eligibility,
		arg.LocationQuality,
		arg.SourceReference,
		arg.EffectiveDate,
		arg.Latitude,
		arg.Longitude,
		arg.Crs,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const transformPoint = `-- name: TransformPoint :one
SELECT ST_Y(ST_Transform(ST_SetSRID(ST_MakePoint($1::float8, $2::float8), $3::int), 4326))::float8 AS latitude,
    ST_X(ST_Transform(ST_SetSRID(ST_MakePoint($1::float8, $2::float8), $3::int), 4326))::float8 AS longitude
`

type TransformPointParams struct {
	Lon  float64 `json:"lon"`
	Lat  float64 `json:"lat"`
	Srid int32   `json:"srid"`
}

type TransformPointRow struct {
	Latitude  float64 `json:"latitude"`
	Longitude float64 `json:"longitude"`
}

func (q *Queries) TransformPoint(ctx context.Context, arg TransformPointParams) (TransformPointRow, error) {
	row := q.db.QueryRow(ctx, transformPoint, arg.Lon, arg.Lat, arg.Srid)
	var i TransformPointRow
	err := row.Scan(&i.Latitude, &i.Longitude)
	return i, err
}

const updateStationStatus = `-- name: UpdateStationStatus :execrows
UPDATE directory_stations
SET status = $1
WHERE id = $2 AND status <> $1
  -- Revocation sticks: a sourced suspended/revoked status is never
  -- cleared back to active by a later snapshot; reactivation is an
  -- audited operator decision, not an import side effect.
  AND NOT (status IN ('suspended', 'revoked') AND $1 = 'active')
`

type UpdateStationStatusParams struct {
	Status string      `json:"status"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateStationStatus(ctx context.Context, arg UpdateStationStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateStationStatus, arg.Status, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
