// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stations.sql

package directory

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveIdentifiers = `-- name: CountActiveIdentifiers :one
SELECT count(*) FROM directory_identifiers WHERE valid_to IS NULL
`

func (q *Queries) CountActiveIdentifiers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveIdentifiers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countStations = `-- name: CountStations :one
SELECT count(*) FROM directory_stations
`

func (q *Queries) CountStations(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countStations)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createIdentifier = `-- name: CreateIdentifier :one
INSERT INTO directory_identifiers (id, station_id, kind, normalized_value, source_revision_id)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (kind, normalized_value) WHERE valid_to IS NULL DO NOTHING
RETURNING station_id
`

type CreateIdentifierParams struct {
	ID               pgtype.UUID `json:"id"`
	StationID        pgtype.UUID `json:"station_id"`
	Kind             string      `json:"kind"`
	Value            string      `json:"value"`
	SourceRevisionID pgtype.Text `json:"source_revision_id"`
}

func (q *Queries) CreateIdentifier(ctx context.Context, arg CreateIdentifierParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createIdentifier,
		arg.ID,
		arg.StationID,
		arg.Kind,
		arg.Value,
		arg.SourceRevisionID,
	)
	var station_id pgtype.UUID
	err := row.Scan(&station_id)
	return station_id, err
}

const createLocationRevision = `-- name: CreateLocationRevision :one
INSERT INTO directory_location_revisions
    (id, station_id, point, quality, provider, source_reference, supersedes_id)
VALUES (
    $1, $2,
    ST_GeogFromText(NULLIF($3, '')),
    $4, $5, $6, $7
)
RETURNING id, station_id, ST_AsText(point) AS point_wkt, quality,
    provider, source_reference, obtained_at, supersedes_id
`

type CreateLocationRevisionParams struct {
	ID              pgtype.UUID `json:"id"`
	StationID       pgtype.UUID `json:"station_id"`
	PointWkt        interface{} `json:"point_wkt"`
	Quality         string      `json:"quality"`
	Provider        string      `json:"provider"`
	SourceReference string      `json:"source_reference"`
	SupersedesID    pgtype.UUID `json:"supersedes_id"`
}

type CreateLocationRevisionRow struct {
	ID              pgtype.UUID        `json:"id"`
	StationID       pgtype.UUID        `json:"station_id"`
	PointWkt        interface{}        `json:"point_wkt"`
	Quality         string             `json:"quality"`
	Provider        string             `json:"provider"`
	SourceReference string             `json:"source_reference"`
	ObtainedAt      pgtype.Timestamptz `json:"obtained_at"`
	SupersedesID    pgtype.UUID        `json:"supersedes_id"`
}

func (q *Queries) CreateLocationRevision(ctx context.Context, arg CreateLocationRevisionParams) (CreateLocationRevisionRow, error) {
	row := q.db.QueryRow(ctx, createLocationRevision,
		arg.ID,
		arg.StationID,
		arg.PointWkt,
		arg.Quality,
		arg.Provider,
		arg.SourceReference,
		arg.SupersedesID,
	)
	var i CreateLocationRevisionRow
	err := row.Scan(
		&i.ID,
		&i.StationID,
		&i.PointWkt,
		&i.Quality,
		&i.Provider,
		&i.SourceReference,
		&i.ObtainedAt,
		&i.SupersedesID,
	)
	return i, err
}

const createStation = `-- name: CreateStation :one

INSERT INTO directory_stations (id, display_name, address, municipality_code, state)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, display_name, municipality_code, state, status, created_at
`

type CreateStationParams struct {
	ID               pgtype.UUID `json:"id"`
	DisplayName      string      `json:"display_name"`
	Address          []byte      `json:"address"`
	MunicipalityCode pgtype.Text `json:"municipality_code"`
	State            pgtype.Text `json:"state"`
}

type CreateStationRow struct {
	ID               pgtype.UUID        `json:"id"`
	DisplayName      string             `json:"display_name"`
	MunicipalityCode pgtype.Text        `json:"municipality_code"`
	State            pgtype.Text        `json:"state"`
	Status           string             `json:"status"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
}

// Owned by directory. Modules must not import another module's generated
// package; cross-module reads use owned queries documented in DATA_MODEL.
func (q *Queries) CreateStation(ctx context.Context, arg CreateStationParams) (CreateStationRow, error) {
	row := q.db.QueryRow(ctx, createStation,
		arg.ID,
		arg.DisplayName,
		arg.Address,
		arg.MunicipalityCode,
		arg.State,
	)
	var i CreateStationRow
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.MunicipalityCode,
		&i.State,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getStation = `-- name: GetStation :one
SELECT id, display_name, address, municipality_code, state, status,
    ST_AsText(current_point) AS current_point_wkt, current_quality,
    current_revision_id, created_at
FROM directory_stations
WHERE id = $1
`

type GetStationRow struct {
	ID                pgtype.UUID        `json:"id"`
	DisplayName       string             `json:"display_name"`
	Address           []byte             `json:"address"`
	MunicipalityCode  pgtype.Text        `json:"municipality_code"`
	State             pgtype.Text        `json:"state"`
	Status            string             `json:"status"`
	CurrentPointWkt   interface{}        `json:"current_point_wkt"`
	CurrentQuality    pgtype.Text        `json:"current_quality"`
	CurrentRevisionID pgtype.UUID        `json:"current_revision_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) GetStation(ctx context.Context, id pgtype.UUID) (GetStationRow, error) {
	row := q.db.QueryRow(ctx, getStation, id)
	var i GetStationRow
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Address,
		&i.MunicipalityCode,
		&i.State,
		&i.Status,
		&i.CurrentPointWkt,
		&i.CurrentQuality,
		&i.CurrentRevisionID,
		&i.CreatedAt,
	)
	return i, err
}

const listLocationRevisions = `-- name: ListLocationRevisions :many
SELECT id, station_id, ST_AsText(point) AS point_wkt, quality,
    provider, source_reference, obtained_at, supersedes_id
FROM directory_location_revisions
WHERE station_id = $1
ORDER BY obtained_at ASC, id ASC
`

type ListLocationRevisionsRow struct {
	ID              pgtype.UUID        `json:"id"`
	StationID       pgtype.UUID        `json:"station_id"`
	PointWkt        interface{}        `json:"point_wkt"`
	Quality         string             `json:"quality"`
	Provider        string             `json:"provider"`
	SourceReference string             `json:"source_reference"`
	ObtainedAt      pgtype.Timestamptz `json:"obtained_at"`
	SupersedesID    pgtype.UUID        `json:"supersedes_id"`
}

func (q *Queries) ListLocationRevisions(ctx context.Context, stationID pgtype.UUID) ([]ListLocationRevisionsRow, error) {
	rows, err := q.db.Query(ctx, listLocationRevisions, stationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLocationRevisionsRow
	for rows.Next() {
		var i ListLocationRevisionsRow
		if err := rows.Scan(
			&i.ID,
			&i.StationID,
			&i.PointWkt,
			&i.Quality,
			&i.Provider,
			&i.SourceReference,
			&i.ObtainedAt,
			&i.SupersedesID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nearbyStations = `-- name: NearbyStations :many
SELECT id, display_name, address, municipality_code, state, status,
    ST_AsText(current_point) AS current_point_wkt, current_quality,
    current_revision_id, created_at,
    ST_Distance(current_point, ST_SetSRID(ST_MakePoint($1::float8, $2::float8), 4326)::geography) AS distance_m
FROM directory_stations
WHERE current_point IS NOT NULL
    AND ST_DWithin(current_point, ST_SetSRID(ST_MakePoint($1::float8, $2::float8), 4326)::geography, $3::int)
    AND ($4::boolean = FALSE OR
        (ST_Distance(current_point, ST_SetSRID(ST_MakePoint($1::float8, $2::float8), 4326)::geography) > $5::float8) OR
        (ST_Distance(current_point, ST_SetSRID(ST_MakePoint($1::float8, $2::float8), 4326)::geography) = $5::float8 AND id::text > $6::text))
ORDER BY distance_m ASC, id::text ASC
LIMIT $7::int
`

type NearbyStationsParams struct {
	Lon          float64 `json:"lon"`
	Lat          float64 `json:"lat"`
	RadiusM      int32   `json:"radius_m"`
	HasCursor    bool    `json:"has_cursor"`
	AfterDist    float64 `json:"after_dist"`
	AfterID      string  `json:"after_id"`
	LimitPlusOne int32   `json:"limit_plus_one"`
}

type NearbyStationsRow struct {
	ID                pgtype.UUID        `json:"id"`
	DisplayName       string             `json:"display_name"`
	Address           []byte             `json:"address"`
	MunicipalityCode  pgtype.Text        `json:"municipality_code"`
	State             pgtype.Text        `json:"state"`
	Status            string             `json:"status"`
	CurrentPointWkt   interface{}        `json:"current_point_wkt"`
	CurrentQuality    pgtype.Text        `json:"current_quality"`
	CurrentRevisionID pgtype.UUID        `json:"current_revision_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	DistanceM         interface{}        `json:"distance_m"`
}

func (q *Queries) NearbyStations(ctx context.Context, arg NearbyStationsParams) ([]NearbyStationsRow, error) {
	rows, err := q.db.Query(ctx, nearbyStations,
		arg.Lon,
		arg.Lat,
		arg.RadiusM,
		arg.HasCursor,
		arg.AfterDist,
		arg.AfterID,
		arg.LimitPlusOne,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NearbyStationsRow
	for rows.Next() {
		var i NearbyStationsRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.Address,
			&i.MunicipalityCode,
			&i.State,
			&i.Status,
			&i.CurrentPointWkt,
			&i.CurrentQuality,
			&i.CurrentRevisionID,
			&i.CreatedAt,
			&i.DistanceM,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveActiveIdentifier = `-- name: ResolveActiveIdentifier :one
SELECT s.id, s.display_name, s.municipality_code, s.state, s.status,
    ST_AsText(s.current_point) AS current_point_wkt, s.current_quality,
    s.current_revision_id, s.created_at
FROM directory_identifiers AS i
JOIN directory_stations AS s ON s.id = i.station_id
WHERE i.kind = $1 AND i.normalized_value = $2 AND i.valid_to IS NULL
`

type ResolveActiveIdentifierParams struct {
	Kind  string `json:"kind"`
	Value string `json:"value"`
}

type ResolveActiveIdentifierRow struct {
	ID                pgtype.UUID        `json:"id"`
	DisplayName       string             `json:"display_name"`
	MunicipalityCode  pgtype.Text        `json:"municipality_code"`
	State             pgtype.Text        `json:"state"`
	Status            string             `json:"status"`
	CurrentPointWkt   interface{}        `json:"current_point_wkt"`
	CurrentQuality    pgtype.Text        `json:"current_quality"`
	CurrentRevisionID pgtype.UUID        `json:"current_revision_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ResolveActiveIdentifier(ctx context.Context, arg ResolveActiveIdentifierParams) (ResolveActiveIdentifierRow, error) {
	row := q.db.QueryRow(ctx, resolveActiveIdentifier, arg.Kind, arg.Value)
	var i ResolveActiveIdentifierRow
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.MunicipalityCode,
		&i.State,
		&i.Status,
		&i.CurrentPointWkt,
		&i.CurrentQuality,
		&i.CurrentRevisionID,
		&i.CreatedAt,
	)
	return i, err
}

const retireIdentifier = `-- name: RetireIdentifier :execrows
UPDATE directory_identifiers
SET valid_to = now()
WHERE kind = $1 AND normalized_value = $2 AND valid_to IS NULL
`

type RetireIdentifierParams struct {
	Kind  string `json:"kind"`
	Value string `json:"value"`
}

func (q *Queries) RetireIdentifier(ctx context.Context, arg RetireIdentifierParams) (int64, error) {
	result, err := q.db.Exec(ctx, retireIdentifier, arg.Kind, arg.Value)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const searchStations = `-- name: SearchStations :many
SELECT id, display_name, address, municipality_code, state, status,
    ST_AsText(current_point) AS current_point_wkt, current_quality,
    current_revision_id, created_at
FROM directory_stations
WHERE ($1::text = '' OR state = $1)
    AND ($2::text = '' OR municipality_code = $2)
    AND ($3::text = '' OR display_name ILIKE '%' || $3 || '%')
    AND ($4::text = '' OR id::text > $4::text)
ORDER BY id::text ASC
LIMIT $5::int
`

type SearchStationsParams struct {
	State        string `json:"state"`
	Municipality string `json:"municipality"`
	Q            string `json:"q"`
	AfterID      string `json:"after_id"`
	LimitPlusOne int32  `json:"limit_plus_one"`
}

type SearchStationsRow struct {
	ID                pgtype.UUID        `json:"id"`
	DisplayName       string             `json:"display_name"`
	Address           []byte             `json:"address"`
	MunicipalityCode  pgtype.Text        `json:"municipality_code"`
	State             pgtype.Text        `json:"state"`
	Status            string             `json:"status"`
	CurrentPointWkt   interface{}        `json:"current_point_wkt"`
	CurrentQuality    pgtype.Text        `json:"current_quality"`
	CurrentRevisionID pgtype.UUID        `json:"current_revision_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) SearchStations(ctx context.Context, arg SearchStationsParams) ([]SearchStationsRow, error) {
	rows, err := q.db.Query(ctx, searchStations,
		arg.State,
		arg.Municipality,
		arg.Q,
		arg.AfterID,
		arg.LimitPlusOne,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchStationsRow
	for rows.Next() {
		var i SearchStationsRow
		if err := rows.Scan(
			&i.ID,
			&i.DisplayName,
			&i.Address,
			&i.MunicipalityCode,
			&i.State,
			&i.Status,
			&i.CurrentPointWkt,
			&i.CurrentQuality,
			&i.CurrentRevisionID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const stationCNPJ = `-- name: StationCNPJ :one
SELECT normalized_value FROM directory_identifiers
WHERE station_id = $1 AND kind = 'CNPJ' AND valid_to IS NULL
`

func (q *Queries) StationCNPJ(ctx context.Context, stationID pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, stationCNPJ, stationID)
	var normalized_value string
	err := row.Scan(&normalized_value)
	return normalized_value, err
}

const updateStationProjection = `-- name: UpdateStationProjection :exec
UPDATE directory_stations
SET current_point = ST_GeogFromText(NULLIF($1, '')),
    current_quality = $2,
    current_revision_id = $3
WHERE id = $4
`

type UpdateStationProjectionParams struct {
	PointWkt   interface{} `json:"point_wkt"`
	Quality    pgtype.Text `json:"quality"`
	RevisionID pgtype.UUID `json:"revision_id"`
	ID         pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateStationProjection(ctx context.Context, arg UpdateStationProjectionParams) error {
	_, err := q.db.Exec(ctx, updateStationProjection,
		arg.PointWkt,
		arg.Quality,
		arg.RevisionID,
		arg.ID,
	)
	return err
}
