// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package privacy

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type PrivacyRequest struct {
	ID                 pgtype.UUID        `json:"id"`
	ContributorID      string             `json:"contributor_id"`
	ContributorRef     string             `json:"contributor_ref"`
	ClientSubmissionID string             `json:"client_submission_id"`
	Type               string             `json:"type"`
	Status             string             `json:"status"`
	Archive            []byte             `json:"archive"`
	ArchiveSha256      string             `json:"archive_sha256"`
	RequestedAt        pgtype.Timestamptz `json:"requested_at"`
	ReadyAt            pgtype.Timestamptz `json:"ready_at"`
	ExpiresAt          pgtype.Timestamptz `json:"expires_at"`
	CompletedAt        pgtype.Timestamptz `json:"completed_at"`
	PolicyVersion      string             `json:"policy_version"`
}
