// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: privacy.sql

package privacy

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRequest = `-- name: GetRequest :one
SELECT id, contributor_id, contributor_ref, client_submission_id, type,
    status, archive, archive_sha256, requested_at, ready_at, expires_at,
    completed_at, policy_version
FROM privacy_requests
WHERE id = $1
`

func (q *Queries) GetRequest(ctx context.Context, id pgtype.UUID) (PrivacyRequest, error) {
	row := q.db.QueryRow(ctx, getRequest, id)
	var i PrivacyRequest
	err := row.Scan(
		&i.ID,
		&i.ContributorID,
		&i.ContributorRef,
		&i.ClientSubmissionID,
		&i.Type,
		&i.Status,
		&i.Archive,
		&i.ArchiveSha256,
		&i.RequestedAt,
		&i.ReadyAt,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.PolicyVersion,
	)
	return i, err
}

const getRequestByNaturalKey = `-- name: GetRequestByNaturalKey :one
SELECT id, contributor_id, contributor_ref, client_submission_id, type,
    status, archive, archive_sha256, requested_at, ready_at, expires_at,
    completed_at, policy_version
FROM privacy_requests
WHERE contributor_id = $1 AND client_submission_id = $2
`

type GetRequestByNaturalKeyParams struct {
	ContributorID      string `json:"contributor_id"`
	ClientSubmissionID string `json:"client_submission_id"`
}

func (q *Queries) GetRequestByNaturalKey(ctx context.Context, arg GetRequestByNaturalKeyParams) (PrivacyRequest, error) {
	row := q.db.QueryRow(ctx, getRequestByNaturalKey, arg.ContributorID, arg.ClientSubmissionID)
	var i PrivacyRequest
	err := row.Scan(
		&i.ID,
		&i.ContributorID,
		&i.ContributorRef,
		&i.ClientSubmissionID,
		&i.Type,
		&i.Status,
		&i.Archive,
		&i.ArchiveSha256,
		&i.RequestedAt,
		&i.ReadyAt,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.PolicyVersion,
	)
	return i, err
}

const insertLedgerEntry = `-- name: InsertLedgerEntry :one

INSERT INTO privacy_deletion_ledger
    (id, contributor_id, contributor_ref, scope, reason, occurred_at,
     policy_version)
VALUES ($1, $2, $3, $4, $5,
    $6, $7)
ON CONFLICT DO NOTHING
RETURNING id
`

type InsertLedgerEntryParams struct {
	ID             pgtype.UUID        `json:"id"`
	ContributorID  string             `json:"contributor_id"`
	ContributorRef string             `json:"contributor_ref"`
	Scope          string             `json:"scope"`
	Reason         string             `json:"reason"`
	OccurredAt     pgtype.Timestamptz `json:"occurred_at"`
	PolicyVersion  string             `json:"policy_version"`
}

// Deletion replay ledger (P07-T04): insert-once per contributor and
// scope, contributor-scoped reads, replay marks. No DELETE path: the
// ledger ages out with the backup horizon under retention (P07-T05).
func (q *Queries) InsertLedgerEntry(ctx context.Context, arg InsertLedgerEntryParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertLedgerEntry,
		arg.ID,
		arg.ContributorID,
		arg.ContributorRef,
		arg.Scope,
		arg.Reason,
		arg.OccurredAt,
		arg.PolicyVersion,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const insertRequest = `-- name: InsertRequest :one

INSERT INTO privacy_requests
    (id, contributor_id, contributor_ref, client_submission_id, type,
     status, requested_at, policy_version)
VALUES ($1, $2, $3, $4,
    $5, $6, $7, $8)
ON CONFLICT DO NOTHING
RETURNING id
`

type InsertRequestParams struct {
	ID                 pgtype.UUID        `json:"id"`
	ContributorID      string             `json:"contributor_id"`
	ContributorRef     string             `json:"contributor_ref"`
	ClientSubmissionID string             `json:"client_submission_id"`
	Type               string             `json:"type"`
	Status             string             `json:"status"`
	RequestedAt        pgtype.Timestamptz `json:"requested_at"`
	PolicyVersion      string             `json:"policy_version"`
}

// Owned by privacy. Requests are insert-once: retries converge on the
// owner natural key, and outcomes move forward only (REQUESTED to READY
// or FAILED) through the guarded transitions below. No mutation exists
// outside those guards and no removal path exists in this file: expiry
// purges arrive with the retention scheduler (P07-T05), and erasure
// removes payloads through the deletion workflow (P07-T04), never by
// editing export history.
func (q *Queries) InsertRequest(ctx context.Context, arg InsertRequestParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertRequest,
		arg.ID,
		arg.ContributorID,
		arg.ContributorRef,
		arg.ClientSubmissionID,
		arg.Type,
		arg.Status,
		arg.RequestedAt,
		arg.PolicyVersion,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const listLedgerByContributor = `-- name: ListLedgerByContributor :many
SELECT id, contributor_id, contributor_ref, scope, reason, occurred_at,
    replayed_at, policy_version
FROM privacy_deletion_ledger
WHERE contributor_id = $1
ORDER BY scope ASC
`

func (q *Queries) ListLedgerByContributor(ctx context.Context, contributorID string) ([]PrivacyDeletionLedger, error) {
	rows, err := q.db.Query(ctx, listLedgerByContributor, contributorID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PrivacyDeletionLedger
	for rows.Next() {
		var i PrivacyDeletionLedger
		if err := rows.Scan(
			&i.ID,
			&i.ContributorID,
			&i.ContributorRef,
			&i.Scope,
			&i.Reason,
			&i.OccurredAt,
			&i.ReplayedAt,
			&i.PolicyVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDeletionReady = `-- name: MarkDeletionReady :one
UPDATE privacy_requests
SET status = 'READY', ready_at = $1, completed_at = $2
WHERE id = $3 AND status = 'REQUESTED' AND type = 'DELETION'
RETURNING id
`

type MarkDeletionReadyParams struct {
	ReadyAt     pgtype.Timestamptz `json:"ready_at"`
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	ID          pgtype.UUID        `json:"id"`
}

func (q *Queries) MarkDeletionReady(ctx context.Context, arg MarkDeletionReadyParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, markDeletionReady, arg.ReadyAt, arg.CompletedAt, arg.ID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const markFailed = `-- name: MarkFailed :one
UPDATE privacy_requests
SET status = 'FAILED', completed_at = $1
WHERE id = $2 AND status = 'REQUESTED'
RETURNING id
`

type MarkFailedParams struct {
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	ID          pgtype.UUID        `json:"id"`
}

func (q *Queries) MarkFailed(ctx context.Context, arg MarkFailedParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, markFailed, arg.CompletedAt, arg.ID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const markLedgerReplayed = `-- name: MarkLedgerReplayed :execrows
UPDATE privacy_deletion_ledger
SET replayed_at = $1
WHERE id = $2
`

type MarkLedgerReplayedParams struct {
	ReplayedAt pgtype.Timestamptz `json:"replayed_at"`
	ID         pgtype.UUID        `json:"id"`
}

func (q *Queries) MarkLedgerReplayed(ctx context.Context, arg MarkLedgerReplayedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markLedgerReplayed, arg.ReplayedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markReady = `-- name: MarkReady :one
UPDATE privacy_requests
SET status = 'READY', archive = $1, archive_sha256 = $2,
    ready_at = $3, expires_at = $4,
    completed_at = $5
WHERE id = $6 AND status = 'REQUESTED'
RETURNING id
`

type MarkReadyParams struct {
	Archive       []byte             `json:"archive"`
	ArchiveSha256 string             `json:"archive_sha256"`
	ReadyAt       pgtype.Timestamptz `json:"ready_at"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	CompletedAt   pgtype.Timestamptz `json:"completed_at"`
	ID            pgtype.UUID        `json:"id"`
}

func (q *Queries) MarkReady(ctx context.Context, arg MarkReadyParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, markReady,
		arg.Archive,
		arg.ArchiveSha256,
		arg.ReadyAt,
		arg.ExpiresAt,
		arg.CompletedAt,
		arg.ID,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const oldestExpiredArchive = `-- name: OldestExpiredArchive :one

SELECT expires_at
FROM privacy_requests
WHERE status = 'READY' AND archive IS NOT NULL AND expires_at < $1
ORDER BY expires_at ASC
LIMIT 1
`

// Retention (P07-T05): purge expired export bytes and aged-out ledger
// rows in bounded batches. Receipts stay; only payload goes, and the
// ledger keeps exactly the backup horizon (35 days).
func (q *Queries) OldestExpiredArchive(ctx context.Context, now pgtype.Timestamptz) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, oldestExpiredArchive, now)
	var expires_at pgtype.Timestamptz
	err := row.Scan(&expires_at)
	return expires_at, err
}

const oldestLedgerRow = `-- name: OldestLedgerRow :one
SELECT occurred_at
FROM privacy_deletion_ledger
WHERE occurred_at < $1
ORDER BY occurred_at ASC
LIMIT 1
`

func (q *Queries) OldestLedgerRow(ctx context.Context, cutoff pgtype.Timestamptz) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, oldestLedgerRow, cutoff)
	var occurred_at pgtype.Timestamptz
	err := row.Scan(&occurred_at)
	return occurred_at, err
}

const purgeExpiredArchives = `-- name: PurgeExpiredArchives :execrows
UPDATE privacy_requests AS dead
SET archive = NULL
WHERE dead.id IN (
    SELECT live.id FROM privacy_requests AS live
    WHERE live.status = 'READY' AND live.archive IS NOT NULL AND live.expires_at < $1
    ORDER BY live.expires_at ASC
    LIMIT $2
)
`

type PurgeExpiredArchivesParams struct {
	Now   pgtype.Timestamptz `json:"now"`
	Batch int32              `json:"batch"`
}

func (q *Queries) PurgeExpiredArchives(ctx context.Context, arg PurgeExpiredArchivesParams) (int64, error) {
	result, err := q.db.Exec(ctx, purgeExpiredArchives, arg.Now, arg.Batch)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgeOldLedger = `-- name: PurgeOldLedger :execrows
DELETE FROM privacy_deletion_ledger AS dead
WHERE dead.id IN (
    SELECT live.id FROM privacy_deletion_ledger AS live
    WHERE live.occurred_at < $1
    ORDER BY live.occurred_at ASC
    LIMIT $2
)
`

type PurgeOldLedgerParams struct {
	Cutoff pgtype.Timestamptz `json:"cutoff"`
	Batch  int32              `json:"batch"`
}

func (q *Queries) PurgeOldLedger(ctx context.Context, arg PurgeOldLedgerParams) (int64, error) {
	result, err := q.db.Exec(ctx, purgeOldLedger, arg.Cutoff, arg.Batch)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgeOwnerArchives = `-- name: PurgeOwnerArchives :execrows
UPDATE privacy_requests
SET archive = NULL
WHERE contributor_id = $1 AND archive IS NOT NULL
`

func (q *Queries) PurgeOwnerArchives(ctx context.Context, contributorID string) (int64, error) {
	result, err := q.db.Exec(ctx, purgeOwnerArchives, contributorID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
