// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: privacy.sql

package privacy

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getRequest = `-- name: GetRequest :one
SELECT id, contributor_id, contributor_ref, client_submission_id, type,
    status, archive, archive_sha256, requested_at, ready_at, expires_at,
    completed_at, policy_version
FROM privacy_requests
WHERE id = $1
`

func (q *Queries) GetRequest(ctx context.Context, id pgtype.UUID) (PrivacyRequest, error) {
	row := q.db.QueryRow(ctx, getRequest, id)
	var i PrivacyRequest
	err := row.Scan(
		&i.ID,
		&i.ContributorID,
		&i.ContributorRef,
		&i.ClientSubmissionID,
		&i.Type,
		&i.Status,
		&i.Archive,
		&i.ArchiveSha256,
		&i.RequestedAt,
		&i.ReadyAt,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.PolicyVersion,
	)
	return i, err
}

const getRequestByNaturalKey = `-- name: GetRequestByNaturalKey :one
SELECT id, contributor_id, contributor_ref, client_submission_id, type,
    status, archive, archive_sha256, requested_at, ready_at, expires_at,
    completed_at, policy_version
FROM privacy_requests
WHERE contributor_id = $1 AND client_submission_id = $2
`

type GetRequestByNaturalKeyParams struct {
	ContributorID      string `json:"contributor_id"`
	ClientSubmissionID string `json:"client_submission_id"`
}

func (q *Queries) GetRequestByNaturalKey(ctx context.Context, arg GetRequestByNaturalKeyParams) (PrivacyRequest, error) {
	row := q.db.QueryRow(ctx, getRequestByNaturalKey, arg.ContributorID, arg.ClientSubmissionID)
	var i PrivacyRequest
	err := row.Scan(
		&i.ID,
		&i.ContributorID,
		&i.ContributorRef,
		&i.ClientSubmissionID,
		&i.Type,
		&i.Status,
		&i.Archive,
		&i.ArchiveSha256,
		&i.RequestedAt,
		&i.ReadyAt,
		&i.ExpiresAt,
		&i.CompletedAt,
		&i.PolicyVersion,
	)
	return i, err
}

const insertRequest = `-- name: InsertRequest :one

INSERT INTO privacy_requests
    (id, contributor_id, contributor_ref, client_submission_id, type,
     status, requested_at, policy_version)
VALUES ($1, $2, $3, $4,
    $5, $6, $7, $8)
ON CONFLICT DO NOTHING
RETURNING id
`

type InsertRequestParams struct {
	ID                 pgtype.UUID        `json:"id"`
	ContributorID      string             `json:"contributor_id"`
	ContributorRef     string             `json:"contributor_ref"`
	ClientSubmissionID string             `json:"client_submission_id"`
	Type               string             `json:"type"`
	Status             string             `json:"status"`
	RequestedAt        pgtype.Timestamptz `json:"requested_at"`
	PolicyVersion      string             `json:"policy_version"`
}

// Owned by privacy. Requests are insert-once: retries converge on the
// owner natural key, and outcomes move forward only (REQUESTED to READY
// or FAILED) through the guarded transitions below. No UPDATE outside
// those guards and no DELETE path exists in this file: expiry purges
// arrive with the retention scheduler (P07-T05), and erasure removes
// payloads through the deletion workflow (P07-T04), never by editing
// export history.
func (q *Queries) InsertRequest(ctx context.Context, arg InsertRequestParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertRequest,
		arg.ID,
		arg.ContributorID,
		arg.ContributorRef,
		arg.ClientSubmissionID,
		arg.Type,
		arg.Status,
		arg.RequestedAt,
		arg.PolicyVersion,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const markFailed = `-- name: MarkFailed :one
UPDATE privacy_requests
SET status = 'FAILED', completed_at = $1
WHERE id = $2 AND status = 'REQUESTED'
RETURNING id
`

type MarkFailedParams struct {
	CompletedAt pgtype.Timestamptz `json:"completed_at"`
	ID          pgtype.UUID        `json:"id"`
}

func (q *Queries) MarkFailed(ctx context.Context, arg MarkFailedParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, markFailed, arg.CompletedAt, arg.ID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const markReady = `-- name: MarkReady :one
UPDATE privacy_requests
SET status = 'READY', archive = $1, archive_sha256 = $2,
    ready_at = $3, expires_at = $4,
    completed_at = $5
WHERE id = $6 AND status = 'REQUESTED'
RETURNING id
`

type MarkReadyParams struct {
	Archive       []byte             `json:"archive"`
	ArchiveSha256 string             `json:"archive_sha256"`
	ReadyAt       pgtype.Timestamptz `json:"ready_at"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	CompletedAt   pgtype.Timestamptz `json:"completed_at"`
	ID            pgtype.UUID        `json:"id"`
}

func (q *Queries) MarkReady(ctx context.Context, arg MarkReadyParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, markReady,
		arg.Archive,
		arg.ArchiveSha256,
		arg.ReadyAt,
		arg.ExpiresAt,
		arg.CompletedAt,
		arg.ID,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
