// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: comments.sql

package feedback

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCommentView = `-- name: GetCommentView :one
SELECT c.id, c.account_id, a.alias, c.station_id, c.product,
    c.parent_id, c.depth, c.text, c.revision, c.created_at, c.updated_at
FROM feedback_comments c
JOIN accounts a ON a.id = c.account_id
WHERE c.id = $1 AND c.deleted_at IS NULL
`

type GetCommentViewRow struct {
	ID        pgtype.UUID        `json:"id"`
	AccountID pgtype.UUID        `json:"account_id"`
	Alias     string             `json:"alias"`
	StationID pgtype.UUID        `json:"station_id"`
	Product   string             `json:"product"`
	ParentID  pgtype.UUID        `json:"parent_id"`
	Depth     int16              `json:"depth"`
	Text      string             `json:"text"`
	Revision  int32              `json:"revision"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetCommentView(ctx context.Context, id pgtype.UUID) (GetCommentViewRow, error) {
	row := q.db.QueryRow(ctx, getCommentView, id)
	var i GetCommentViewRow
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Alias,
		&i.StationID,
		&i.Product,
		&i.ParentID,
		&i.Depth,
		&i.Text,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertComment = `-- name: InsertComment :exec
INSERT INTO feedback_comments
    (id, account_id, station_id, product, parent_id, depth, text,
     revision, created_at, updated_at, deleted_at)
VALUES ($1, $2, $3, $4, $5, $6,
    $7, 1, $8, $8, NULL)
`

type InsertCommentParams struct {
	ID        pgtype.UUID        `json:"id"`
	AccountID pgtype.UUID        `json:"account_id"`
	StationID pgtype.UUID        `json:"station_id"`
	Product   string             `json:"product"`
	ParentID  pgtype.UUID        `json:"parent_id"`
	Depth     int16              `json:"depth"`
	Text      string             `json:"text"`
	Now       pgtype.Timestamptz `json:"now"`
}

func (q *Queries) InsertComment(ctx context.Context, arg InsertCommentParams) error {
	_, err := q.db.Exec(ctx, insertComment,
		arg.ID,
		arg.AccountID,
		arg.StationID,
		arg.Product,
		arg.ParentID,
		arg.Depth,
		arg.Text,
		arg.Now,
	)
	return err
}

const listReplies = `-- name: ListReplies :many
SELECT c.id, c.account_id, a.alias, c.station_id, c.product,
    c.parent_id, c.depth, c.text, c.revision, c.created_at, c.updated_at
FROM feedback_comments c
JOIN accounts a ON a.id = c.account_id
WHERE c.parent_id = $1 AND c.deleted_at IS NULL
    AND (c.created_at, c.id) > ($2, $3::uuid)
ORDER BY c.created_at, c.id
LIMIT $4
`

type ListRepliesParams struct {
	ParentID  pgtype.UUID        `json:"parent_id"`
	AfterAt   pgtype.Timestamptz `json:"after_at"`
	AfterID   pgtype.UUID        `json:"after_id"`
	PageLimit int32              `json:"page_limit"`
}

type ListRepliesRow struct {
	ID        pgtype.UUID        `json:"id"`
	AccountID pgtype.UUID        `json:"account_id"`
	Alias     string             `json:"alias"`
	StationID pgtype.UUID        `json:"station_id"`
	Product   string             `json:"product"`
	ParentID  pgtype.UUID        `json:"parent_id"`
	Depth     int16              `json:"depth"`
	Text      string             `json:"text"`
	Revision  int32              `json:"revision"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListReplies(ctx context.Context, arg ListRepliesParams) ([]ListRepliesRow, error) {
	rows, err := q.db.Query(ctx, listReplies,
		arg.ParentID,
		arg.AfterAt,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRepliesRow
	for rows.Next() {
		var i ListRepliesRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Alias,
			&i.StationID,
			&i.Product,
			&i.ParentID,
			&i.Depth,
			&i.Text,
			&i.Revision,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTopLevel = `-- name: ListTopLevel :many
SELECT c.id, c.account_id, a.alias, c.station_id, c.product,
    c.parent_id, c.depth, c.text, c.revision, c.created_at, c.updated_at
FROM feedback_comments c
JOIN accounts a ON a.id = c.account_id
WHERE c.station_id = $1 AND c.product = $2
    AND c.parent_id IS NULL AND c.deleted_at IS NULL
    AND (c.created_at, c.id) > ($3, $4::uuid)
ORDER BY c.created_at, c.id
LIMIT $5
`

type ListTopLevelParams struct {
	StationID pgtype.UUID        `json:"station_id"`
	Product   string             `json:"product"`
	AfterAt   pgtype.Timestamptz `json:"after_at"`
	AfterID   pgtype.UUID        `json:"after_id"`
	PageLimit int32              `json:"page_limit"`
}

type ListTopLevelRow struct {
	ID        pgtype.UUID        `json:"id"`
	AccountID pgtype.UUID        `json:"account_id"`
	Alias     string             `json:"alias"`
	StationID pgtype.UUID        `json:"station_id"`
	Product   string             `json:"product"`
	ParentID  pgtype.UUID        `json:"parent_id"`
	Depth     int16              `json:"depth"`
	Text      string             `json:"text"`
	Revision  int32              `json:"revision"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListTopLevel(ctx context.Context, arg ListTopLevelParams) ([]ListTopLevelRow, error) {
	rows, err := q.db.Query(ctx, listTopLevel,
		arg.StationID,
		arg.Product,
		arg.AfterAt,
		arg.AfterID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTopLevelRow
	for rows.Next() {
		var i ListTopLevelRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Alias,
			&i.StationID,
			&i.Product,
			&i.ParentID,
			&i.Depth,
			&i.Text,
			&i.Revision,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockComment = `-- name: LockComment :one

SELECT id, account_id, station_id, product, parent_id, depth, text,
    revision, created_at, updated_at, deleted_at
FROM feedback_comments
WHERE id = $1
FOR UPDATE
`

// Owned by feedback. Bounded plain-text comments and one-level
// replies (P14-T03, B-BR-F03/F04). Edits compare-and-swap the
// revision; deletes tombstone. Reads resolve the opaque account
// alias and never expose addresses or provider subjects.
func (q *Queries) LockComment(ctx context.Context, id pgtype.UUID) (FeedbackComment, error) {
	row := q.db.QueryRow(ctx, lockComment, id)
	var i FeedbackComment
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.StationID,
		&i.Product,
		&i.ParentID,
		&i.Depth,
		&i.Text,
		&i.Revision,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const tombstoneComment = `-- name: TombstoneComment :execrows
UPDATE feedback_comments
SET deleted_at = $1
WHERE id = $2 AND account_id = $3 AND deleted_at IS NULL
`

type TombstoneCommentParams struct {
	Now       pgtype.Timestamptz `json:"now"`
	ID        pgtype.UUID        `json:"id"`
	AccountID pgtype.UUID        `json:"account_id"`
}

func (q *Queries) TombstoneComment(ctx context.Context, arg TombstoneCommentParams) (int64, error) {
	result, err := q.db.Exec(ctx, tombstoneComment, arg.Now, arg.ID, arg.AccountID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateCommentText = `-- name: UpdateCommentText :execrows
UPDATE feedback_comments
SET text = $1, revision = revision + 1, updated_at = $2
WHERE id = $3 AND revision = $4 AND deleted_at IS NULL
`

type UpdateCommentTextParams struct {
	Text             string             `json:"text"`
	Now              pgtype.Timestamptz `json:"now"`
	ID               pgtype.UUID        `json:"id"`
	ExpectedRevision int32              `json:"expected_revision"`
}

func (q *Queries) UpdateCommentText(ctx context.Context, arg UpdateCommentTextParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateCommentText,
		arg.Text,
		arg.Now,
		arg.ID,
		arg.ExpectedRevision,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
