// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: erase.sql

package feedback

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const listCommentsByAccount = `-- name: ListCommentsByAccount :many
SELECT id, account_id, station_id, product, parent_id, depth, text,
    revision, created_at, updated_at, deleted_at, visibility
FROM feedback_comments
WHERE account_id = $1
ORDER BY created_at, id
`

func (q *Queries) ListCommentsByAccount(ctx context.Context, accountID pgtype.UUID) ([]FeedbackComment, error) {
	rows, err := q.db.Query(ctx, listCommentsByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FeedbackComment
	for rows.Next() {
		var i FeedbackComment
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.StationID,
			&i.Product,
			&i.ParentID,
			&i.Depth,
			&i.Text,
			&i.Revision,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.Visibility,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRatingsByAccount = `-- name: ListRatingsByAccount :many

SELECT id, account_id, station_id, product, stars, revision, created_at, deleted_at
FROM feedback_ratings
WHERE account_id = $1
ORDER BY station_id, product, created_at, id
`

// Owned by feedback. Account-footprint export and erasure (P14-T05B,
// B-BR-F02/F07). Export lists one account's rows for the owner archive;
// erasure tombstones live rows by account and lets the caller rebuild the
// affected aggregates from live rows. History stays for audit (deleted_at),
// aggregates read live rows only. No cross-account rows ever match.
func (q *Queries) ListRatingsByAccount(ctx context.Context, accountID pgtype.UUID) ([]FeedbackRating, error) {
	rows, err := q.db.Query(ctx, listRatingsByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FeedbackRating
	for rows.Next() {
		var i FeedbackRating
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.StationID,
			&i.Product,
			&i.Stars,
			&i.Revision,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVotesByAccount = `-- name: ListVotesByAccount :many
SELECT id, account_id, comment_id, comment_revision, choice, created_at, deleted_at
FROM feedback_votes
WHERE account_id = $1
ORDER BY comment_id, comment_revision, created_at, id
`

func (q *Queries) ListVotesByAccount(ctx context.Context, accountID pgtype.UUID) ([]FeedbackVote, error) {
	rows, err := q.db.Query(ctx, listVotesByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FeedbackVote
	for rows.Next() {
		var i FeedbackVote
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.CommentID,
			&i.CommentRevision,
			&i.Choice,
			&i.CreatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
