// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package feedback

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Account struct {
	ID        pgtype.UUID        `json:"id"`
	Alias     string             `json:"alias"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type AccountAddress struct {
	AddressHash string             `json:"address_hash"`
	AccountID   pgtype.UUID        `json:"account_id"`
	LinkedAt    pgtype.Timestamptz `json:"linked_at"`
}

type AccountBindingAudit struct {
	ID            pgtype.UUID        `json:"id"`
	AccountID     pgtype.UUID        `json:"account_id"`
	ContributorID string             `json:"contributor_id"`
	Action        string             `json:"action"`
	OccurredAt    pgtype.Timestamptz `json:"occurred_at"`
}

type AccountContributorBinding struct {
	AccountID      pgtype.UUID        `json:"account_id"`
	ContributorID  string             `json:"contributor_id"`
	KeyFingerprint string             `json:"key_fingerprint"`
	BoundAt        pgtype.Timestamptz `json:"bound_at"`
}

type AccountEmailCode struct {
	ID          pgtype.UUID        `json:"id"`
	AddressHash string             `json:"address_hash"`
	Salt        string             `json:"salt"`
	Hash        string             `json:"hash"`
	IssuedAt    pgtype.Timestamptz `json:"issued_at"`
	Attempts    int32              `json:"attempts"`
	ConsumedAt  pgtype.Timestamptz `json:"consumed_at"`
}

type AccountOidcNonce struct {
	Nonce      string             `json:"nonce"`
	ConsumedAt pgtype.Timestamptz `json:"consumed_at"`
}

type AccountProviderLink struct {
	AccountID pgtype.UUID        `json:"account_id"`
	Provider  string             `json:"provider"`
	Issuer    string             `json:"issuer"`
	Subject   string             `json:"subject"`
	Email     string             `json:"email"`
	LinkedAt  pgtype.Timestamptz `json:"linked_at"`
}

type AccountSessionFamily struct {
	ID            pgtype.UUID        `json:"id"`
	AccountID     pgtype.UUID        `json:"account_id"`
	RefreshSalt   string             `json:"refresh_salt"`
	RefreshHash   string             `json:"refresh_hash"`
	AccessSalt    string             `json:"access_salt"`
	AccessHash    string             `json:"access_hash"`
	AccessExpires pgtype.Timestamptz `json:"access_expires"`
	IssuedAt      pgtype.Timestamptz `json:"issued_at"`
	RevokedAt     pgtype.Timestamptz `json:"revoked_at"`
}

type ClaimDecision struct {
	ID            pgtype.UUID        `json:"id"`
	ClaimID       pgtype.UUID        `json:"claim_id"`
	Reviewer      string             `json:"reviewer"`
	Decision      string             `json:"decision"`
	Reason        string             `json:"reason"`
	PolicyVersion string             `json:"policy_version"`
	ProofVersion  int32              `json:"proof_version"`
	OperatorCnpj  string             `json:"operator_cnpj"`
	Scopes        string             `json:"scopes"`
	DecidedAt     pgtype.Timestamptz `json:"decided_at"`
}

type ClaimDeclaration struct {
	ID             pgtype.UUID        `json:"id"`
	ClaimID        pgtype.UUID        `json:"claim_id"`
	Version        int32              `json:"version"`
	NonceDigest    string             `json:"nonce_digest"`
	ExpectedDigest string             `json:"expected_digest"`
	Declaration    string             `json:"declaration"`
	State          string             `json:"state"`
	Attempts       int32              `json:"attempts"`
	ExpiresAt      pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt     pgtype.Timestamptz `json:"consumed_at"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
}

type DirectoryIdentifier struct {
	ID               pgtype.UUID        `json:"id"`
	StationID        pgtype.UUID        `json:"station_id"`
	Kind             string             `json:"kind"`
	NormalizedValue  string             `json:"normalized_value"`
	ValidFrom        pgtype.Timestamptz `json:"valid_from"`
	ValidTo          pgtype.Timestamptz `json:"valid_to"`
	SourceRevisionID pgtype.Text        `json:"source_revision_id"`
}

type DirectoryLocationRevision struct {
	ID              pgtype.UUID        `json:"id"`
	StationID       pgtype.UUID        `json:"station_id"`
	Point           interface{}        `json:"point"`
	Quality         string             `json:"quality"`
	Provider        string             `json:"provider"`
	SourceReference string             `json:"source_reference"`
	ObtainedAt      pgtype.Timestamptz `json:"obtained_at"`
	SupersedesID    pgtype.UUID        `json:"supersedes_id"`
}

type DirectoryStation struct {
	ID                pgtype.UUID        `json:"id"`
	DisplayName       string             `json:"display_name"`
	Address           []byte             `json:"address"`
	MunicipalityCode  pgtype.Text        `json:"municipality_code"`
	State             pgtype.Text        `json:"state"`
	Status            string             `json:"status"`
	CurrentPoint      interface{}        `json:"current_point"`
	CurrentQuality    pgtype.Text        `json:"current_quality"`
	CurrentRevisionID pgtype.UUID        `json:"current_revision_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type FeedbackComment struct {
	ID                pgtype.UUID        `json:"id"`
	AccountID         pgtype.UUID        `json:"account_id"`
	StationID         pgtype.UUID        `json:"station_id"`
	Product           string             `json:"product"`
	ParentID          pgtype.UUID        `json:"parent_id"`
	Depth             int16              `json:"depth"`
	Text              string             `json:"text"`
	Revision          int32              `json:"revision"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
	Visibility        string             `json:"visibility"`
	BusinessStationID pgtype.UUID        `json:"business_station_id"`
	BusinessGrantID   pgtype.UUID        `json:"business_grant_id"`
}

type FeedbackRating struct {
	ID        pgtype.UUID        `json:"id"`
	AccountID pgtype.UUID        `json:"account_id"`
	StationID pgtype.UUID        `json:"station_id"`
	Product   string             `json:"product"`
	Stars     int16              `json:"stars"`
	Revision  int32              `json:"revision"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type FeedbackRatingStat struct {
	StationID    pgtype.UUID        `json:"station_id"`
	Product      string             `json:"product"`
	RatingsCount int64              `json:"ratings_count"`
	StarsSum     int64              `json:"stars_sum"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type FeedbackTally struct {
	CommentID    pgtype.UUID        `json:"comment_id"`
	Revision     int32              `json:"revision"`
	ValidCount   int64              `json:"valid_count"`
	InvalidCount int64              `json:"invalid_count"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type FeedbackVote struct {
	ID              pgtype.UUID        `json:"id"`
	AccountID       pgtype.UUID        `json:"account_id"`
	CommentID       pgtype.UUID        `json:"comment_id"`
	CommentRevision int32              `json:"comment_revision"`
	Choice          string             `json:"choice"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

type ProfileClaim struct {
	ID             pgtype.UUID        `json:"id"`
	AccountID      pgtype.UUID        `json:"account_id"`
	StationID      pgtype.UUID        `json:"station_id"`
	OperatorCnpj   string             `json:"operator_cnpj"`
	OperatorSource string             `json:"operator_source"`
	Role           string             `json:"role"`
	Scopes         string             `json:"scopes"`
	PolicyVersion  string             `json:"policy_version"`
	State          string             `json:"state"`
	ClientKey      string             `json:"client_key"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type RepresentationGrant struct {
	ID           pgtype.UUID        `json:"id"`
	AccountID    pgtype.UUID        `json:"account_id"`
	StationID    pgtype.UUID        `json:"station_id"`
	OperatorCnpj string             `json:"operator_cnpj"`
	Role         string             `json:"role"`
	Scopes       string             `json:"scopes"`
	Version      int32              `json:"version"`
	Status       string             `json:"status"`
	ClaimID      pgtype.UUID        `json:"claim_id"`
	DecisionID   pgtype.UUID        `json:"decision_id"`
	ValidFrom    pgtype.Timestamptz `json:"valid_from"`
	ValidTo      pgtype.Timestamptz `json:"valid_to"`
}

type StationOperatorRevision struct {
	ID              pgtype.UUID        `json:"id"`
	StationID       pgtype.UUID        `json:"station_id"`
	Cnpj            string             `json:"cnpj"`
	Source          string             `json:"source"`
	SourceReference string             `json:"source_reference"`
	ValidFrom       pgtype.Timestamptz `json:"valid_from"`
	ValidTo         pgtype.Timestamptz `json:"valid_to"`
}

type StationProfile struct {
	StationID     pgtype.UUID        `json:"station_id"`
	PolicyVersion string             `json:"policy_version"`
	Projection    []byte             `json:"projection"`
	Revision      int32              `json:"revision"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}
