// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: ratings.sql

package feedback

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countSumLive = `-- name: CountSumLive :one
SELECT count(*)::bigint AS ratings_count, coalesce(sum(stars), 0)::bigint AS stars_sum
FROM feedback_ratings
WHERE station_id = $1 AND product = $2 AND deleted_at IS NULL
`

type CountSumLiveParams struct {
	StationID pgtype.UUID `json:"station_id"`
	Product   string      `json:"product"`
}

type CountSumLiveRow struct {
	RatingsCount int64 `json:"ratings_count"`
	StarsSum     int64 `json:"stars_sum"`
}

func (q *Queries) CountSumLive(ctx context.Context, arg CountSumLiveParams) (CountSumLiveRow, error) {
	row := q.db.QueryRow(ctx, countSumLive, arg.StationID, arg.Product)
	var i CountSumLiveRow
	err := row.Scan(&i.RatingsCount, &i.StarsSum)
	return i, err
}

const getStats = `-- name: GetStats :one
SELECT station_id, product, ratings_count, stars_sum, updated_at
FROM feedback_rating_stats
WHERE station_id = $1 AND product = $2
`

type GetStatsParams struct {
	StationID pgtype.UUID `json:"station_id"`
	Product   string      `json:"product"`
}

func (q *Queries) GetStats(ctx context.Context, arg GetStatsParams) (FeedbackRatingStat, error) {
	row := q.db.QueryRow(ctx, getStats, arg.StationID, arg.Product)
	var i FeedbackRatingStat
	err := row.Scan(
		&i.StationID,
		&i.Product,
		&i.RatingsCount,
		&i.StarsSum,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementStats = `-- name: IncrementStats :exec

INSERT INTO feedback_rating_stats
    (station_id, product, ratings_count, stars_sum, updated_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (station_id, product) DO UPDATE SET
    ratings_count = feedback_rating_stats.ratings_count + EXCLUDED.ratings_count,
    stars_sum = feedback_rating_stats.stars_sum + EXCLUDED.stars_sum,
    updated_at = EXCLUDED.updated_at
`

type IncrementStatsParams struct {
	StationID  pgtype.UUID        `json:"station_id"`
	Product    string             `json:"product"`
	CountDelta int64              `json:"count_delta"`
	SumDelta   int64              `json:"sum_delta"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

// IncrementStats applies signed deltas atomically for the write path
// (same lost-update rationale as IncrementTally). Full recomputation
// stays in RebuildStats for reconciliation.
func (q *Queries) IncrementStats(ctx context.Context, arg IncrementStatsParams) error {
	_, err := q.db.Exec(ctx, incrementStats,
		arg.StationID,
		arg.Product,
		arg.CountDelta,
		arg.SumDelta,
		arg.UpdatedAt,
	)
	return err
}

const insertRating = `-- name: InsertRating :exec
INSERT INTO feedback_ratings
    (id, account_id, station_id, product, stars, revision, created_at, deleted_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, NULL)
`

type InsertRatingParams struct {
	ID        pgtype.UUID        `json:"id"`
	AccountID pgtype.UUID        `json:"account_id"`
	StationID pgtype.UUID        `json:"station_id"`
	Product   string             `json:"product"`
	Stars     int16              `json:"stars"`
	Revision  int32              `json:"revision"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertRating(ctx context.Context, arg InsertRatingParams) error {
	_, err := q.db.Exec(ctx, insertRating,
		arg.ID,
		arg.AccountID,
		arg.StationID,
		arg.Product,
		arg.Stars,
		arg.Revision,
		arg.CreatedAt,
	)
	return err
}

const lockRating = `-- name: LockRating :one

SELECT id, account_id, station_id, product, stars, revision, created_at, deleted_at
FROM feedback_ratings
WHERE account_id = $1 AND station_id = $2 AND product = $3
    AND deleted_at IS NULL
FOR UPDATE
`

type LockRatingParams struct {
	AccountID pgtype.UUID `json:"account_id"`
	StationID pgtype.UUID `json:"station_id"`
	Product   string      `json:"product"`
}

// Owned by feedback. One live rating per account/station/product
// (P14-T02, B-BR-F02). Writers lock the live row, converge on equal
// stars, bump the revision on change, then recompute the key stats in
// the same transaction; a lost unique race re-reads the winner.
func (q *Queries) LockRating(ctx context.Context, arg LockRatingParams) (FeedbackRating, error) {
	row := q.db.QueryRow(ctx, lockRating, arg.AccountID, arg.StationID, arg.Product)
	var i FeedbackRating
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.StationID,
		&i.Product,
		&i.Stars,
		&i.Revision,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const tombstoneRating = `-- name: TombstoneRating :execrows
UPDATE feedback_ratings
SET deleted_at = $1
WHERE account_id = $2 AND station_id = $3 AND product = $4
    AND deleted_at IS NULL
`

type TombstoneRatingParams struct {
	Now       pgtype.Timestamptz `json:"now"`
	AccountID pgtype.UUID        `json:"account_id"`
	StationID pgtype.UUID        `json:"station_id"`
	Product   string             `json:"product"`
}

func (q *Queries) TombstoneRating(ctx context.Context, arg TombstoneRatingParams) (int64, error) {
	result, err := q.db.Exec(ctx, tombstoneRating,
		arg.Now,
		arg.AccountID,
		arg.StationID,
		arg.Product,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateRatingStars = `-- name: UpdateRatingStars :exec
UPDATE feedback_ratings
SET stars = $1, revision = $2
WHERE id = $3 AND deleted_at IS NULL
`

type UpdateRatingStarsParams struct {
	Stars    int16       `json:"stars"`
	Revision int32       `json:"revision"`
	ID       pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateRatingStars(ctx context.Context, arg UpdateRatingStarsParams) error {
	_, err := q.db.Exec(ctx, updateRatingStars, arg.Stars, arg.Revision, arg.ID)
	return err
}

const upsertStats = `-- name: UpsertStats :exec
INSERT INTO feedback_rating_stats
    (station_id, product, ratings_count, stars_sum, updated_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (station_id, product) DO UPDATE SET
    ratings_count = $3,
    stars_sum = $4,
    updated_at = $5
`

type UpsertStatsParams struct {
	StationID    pgtype.UUID        `json:"station_id"`
	Product      string             `json:"product"`
	RatingsCount int64              `json:"ratings_count"`
	StarsSum     int64              `json:"stars_sum"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertStats(ctx context.Context, arg UpsertStatsParams) error {
	_, err := q.db.Exec(ctx, upsertStats,
		arg.StationID,
		arg.Product,
		arg.RatingsCount,
		arg.StarsSum,
		arg.UpdatedAt,
	)
	return err
}
