// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: votes.sql

package feedback

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countVotes = `-- name: CountVotes :one
SELECT count(*) FILTER (WHERE choice = 'VALID')::bigint AS valid_count,
    count(*) FILTER (WHERE choice = 'INVALID')::bigint AS invalid_count
FROM feedback_votes
WHERE comment_id = $1 AND comment_revision = $2
    AND deleted_at IS NULL
`

type CountVotesParams struct {
	CommentID       pgtype.UUID `json:"comment_id"`
	CommentRevision int32       `json:"comment_revision"`
}

type CountVotesRow struct {
	ValidCount   int64 `json:"valid_count"`
	InvalidCount int64 `json:"invalid_count"`
}

func (q *Queries) CountVotes(ctx context.Context, arg CountVotesParams) (CountVotesRow, error) {
	row := q.db.QueryRow(ctx, countVotes, arg.CommentID, arg.CommentRevision)
	var i CountVotesRow
	err := row.Scan(&i.ValidCount, &i.InvalidCount)
	return i, err
}

const getTally = `-- name: GetTally :one
SELECT comment_id, revision, valid_count, invalid_count, updated_at
FROM feedback_tallies
WHERE comment_id = $1 AND revision = $2
`

type GetTallyParams struct {
	CommentID pgtype.UUID `json:"comment_id"`
	Revision  int32       `json:"revision"`
}

func (q *Queries) GetTally(ctx context.Context, arg GetTallyParams) (FeedbackTally, error) {
	row := q.db.QueryRow(ctx, getTally, arg.CommentID, arg.Revision)
	var i FeedbackTally
	err := row.Scan(
		&i.CommentID,
		&i.Revision,
		&i.ValidCount,
		&i.InvalidCount,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementTally = `-- name: IncrementTally :exec

INSERT INTO feedback_tallies
    (comment_id, revision, valid_count, invalid_count, updated_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (comment_id, revision) DO UPDATE SET
    valid_count = feedback_tallies.valid_count + EXCLUDED.valid_count,
    invalid_count = feedback_tallies.invalid_count + EXCLUDED.invalid_count,
    updated_at = EXCLUDED.updated_at
`

type IncrementTallyParams struct {
	CommentID    pgtype.UUID        `json:"comment_id"`
	Revision     int32              `json:"revision"`
	ValidDelta   int64              `json:"valid_delta"`
	InvalidDelta int64              `json:"invalid_delta"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

// IncrementTally applies signed deltas atomically for the write path.
// Recompute-in-transaction loses updates under concurrency (two
// writers snapshot overlapping states and last-writer-wins stale
// counts); the single-statement increment serializes on the row.
// Full recomputation stays in RebuildTally for reconciliation.
func (q *Queries) IncrementTally(ctx context.Context, arg IncrementTallyParams) error {
	_, err := q.db.Exec(ctx, incrementTally,
		arg.CommentID,
		arg.Revision,
		arg.ValidDelta,
		arg.InvalidDelta,
		arg.UpdatedAt,
	)
	return err
}

const insertVote = `-- name: InsertVote :exec
INSERT INTO feedback_votes
    (id, account_id, comment_id, comment_revision, choice, created_at, deleted_at)
VALUES ($1, $2, $3, $4, $5, $6, NULL)
`

type InsertVoteParams struct {
	ID              pgtype.UUID        `json:"id"`
	AccountID       pgtype.UUID        `json:"account_id"`
	CommentID       pgtype.UUID        `json:"comment_id"`
	CommentRevision int32              `json:"comment_revision"`
	Choice          string             `json:"choice"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertVote(ctx context.Context, arg InsertVoteParams) error {
	_, err := q.db.Exec(ctx, insertVote,
		arg.ID,
		arg.AccountID,
		arg.CommentID,
		arg.CommentRevision,
		arg.Choice,
		arg.CreatedAt,
	)
	return err
}

const lockVote = `-- name: LockVote :one

SELECT id, account_id, comment_id, comment_revision, choice, created_at, deleted_at
FROM feedback_votes
WHERE account_id = $1 AND comment_id = $2
    AND comment_revision = $3 AND deleted_at IS NULL
FOR UPDATE
`

type LockVoteParams struct {
	AccountID       pgtype.UUID `json:"account_id"`
	CommentID       pgtype.UUID `json:"comment_id"`
	CommentRevision int32       `json:"comment_revision"`
}

// Owned by feedback. One live vote per account/comment/revision
// (P14-T04, B-BR-F05). Changes rewrite the choice, removals
// tombstone, tallies recompute per revision in the same transaction;
// a lost unique race re-reads the winner.
func (q *Queries) LockVote(ctx context.Context, arg LockVoteParams) (FeedbackVote, error) {
	row := q.db.QueryRow(ctx, lockVote, arg.AccountID, arg.CommentID, arg.CommentRevision)
	var i FeedbackVote
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.CommentID,
		&i.CommentRevision,
		&i.Choice,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const tombstoneVote = `-- name: TombstoneVote :execrows
UPDATE feedback_votes
SET deleted_at = $1
WHERE account_id = $2 AND comment_id = $3
    AND comment_revision = $4 AND deleted_at IS NULL
`

type TombstoneVoteParams struct {
	Now             pgtype.Timestamptz `json:"now"`
	AccountID       pgtype.UUID        `json:"account_id"`
	CommentID       pgtype.UUID        `json:"comment_id"`
	CommentRevision int32              `json:"comment_revision"`
}

func (q *Queries) TombstoneVote(ctx context.Context, arg TombstoneVoteParams) (int64, error) {
	result, err := q.db.Exec(ctx, tombstoneVote,
		arg.Now,
		arg.AccountID,
		arg.CommentID,
		arg.CommentRevision,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateVoteChoice = `-- name: UpdateVoteChoice :exec
UPDATE feedback_votes
SET choice = $1
WHERE id = $2 AND deleted_at IS NULL
`

type UpdateVoteChoiceParams struct {
	Choice string      `json:"choice"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) UpdateVoteChoice(ctx context.Context, arg UpdateVoteChoiceParams) error {
	_, err := q.db.Exec(ctx, updateVoteChoice, arg.Choice, arg.ID)
	return err
}

const upsertTally = `-- name: UpsertTally :exec
INSERT INTO feedback_tallies
    (comment_id, revision, valid_count, invalid_count, updated_at)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (comment_id, revision) DO UPDATE SET
    valid_count = $3,
    invalid_count = $4,
    updated_at = $5
`

type UpsertTallyParams struct {
	CommentID    pgtype.UUID        `json:"comment_id"`
	Revision     int32              `json:"revision"`
	ValidCount   int64              `json:"valid_count"`
	InvalidCount int64              `json:"invalid_count"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertTally(ctx context.Context, arg UpsertTallyParams) error {
	_, err := q.db.Exec(ctx, upsertTally,
		arg.CommentID,
		arg.Revision,
		arg.ValidCount,
		arg.InvalidCount,
		arg.UpdatedAt,
	)
	return err
}
