// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: idempotency.sql

package identity

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const completeAttempt = `-- name: CompleteAttempt :exec
UPDATE identity_idempotency
SET response_code = $1, response_json = $2::jsonb
WHERE contributor_id = $3 AND method = $4
    AND route = $5 AND key = $6 AND response_code IS NULL
`

type CompleteAttemptParams struct {
	ResponseCode  pgtype.Int4 `json:"response_code"`
	ResponseJson  []byte      `json:"response_json"`
	ContributorID pgtype.UUID `json:"contributor_id"`
	Method        string      `json:"method"`
	Route         string      `json:"route"`
	Key           string      `json:"key"`
}

func (q *Queries) CompleteAttempt(ctx context.Context, arg CompleteAttemptParams) error {
	_, err := q.db.Exec(ctx, completeAttempt,
		arg.ResponseCode,
		arg.ResponseJson,
		arg.ContributorID,
		arg.Method,
		arg.Route,
		arg.Key,
	)
	return err
}

const deleteAttempt = `-- name: DeleteAttempt :exec
DELETE FROM identity_idempotency
WHERE contributor_id = $1 AND method = $2
    AND route = $3 AND key = $4
`

type DeleteAttemptParams struct {
	ContributorID pgtype.UUID `json:"contributor_id"`
	Method        string      `json:"method"`
	Route         string      `json:"route"`
	Key           string      `json:"key"`
}

func (q *Queries) DeleteAttempt(ctx context.Context, arg DeleteAttemptParams) error {
	_, err := q.db.Exec(ctx, deleteAttempt,
		arg.ContributorID,
		arg.Method,
		arg.Route,
		arg.Key,
	)
	return err
}

const lockAttempt = `-- name: LockAttempt :one
SELECT contributor_id, method, route, key, request_hash, response_code,
    response_json, created_at, expires_at
FROM identity_idempotency
WHERE contributor_id = $1 AND method = $2
    AND route = $3 AND key = $4
FOR UPDATE
`

type LockAttemptParams struct {
	ContributorID pgtype.UUID `json:"contributor_id"`
	Method        string      `json:"method"`
	Route         string      `json:"route"`
	Key           string      `json:"key"`
}

func (q *Queries) LockAttempt(ctx context.Context, arg LockAttemptParams) (IdentityIdempotency, error) {
	row := q.db.QueryRow(ctx, lockAttempt,
		arg.ContributorID,
		arg.Method,
		arg.Route,
		arg.Key,
	)
	var i IdentityIdempotency
	err := row.Scan(
		&i.ContributorID,
		&i.Method,
		&i.Route,
		&i.Key,
		&i.RequestHash,
		&i.ResponseCode,
		&i.ResponseJson,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const oldestExpiredAttempt = `-- name: OldestExpiredAttempt :one

SELECT expires_at
FROM identity_idempotency
WHERE expires_at < $1
ORDER BY expires_at ASC
LIMIT 1
`

// Retention (P07-T05): purge expired idempotency windows in bounded
// batches. Expired outcomes are never replayed, so removal only frees
// space; seven-day mobile retries use fresh keys.
func (q *Queries) OldestExpiredAttempt(ctx context.Context, now pgtype.Timestamptz) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, oldestExpiredAttempt, now)
	var expires_at pgtype.Timestamptz
	err := row.Scan(&expires_at)
	return expires_at, err
}

const purgeExpiredAttempts = `-- name: PurgeExpiredAttempts :execrows
DELETE FROM identity_idempotency AS dead
WHERE (dead.contributor_id, dead.method, dead.route, dead.key) IN (
    SELECT live.contributor_id, live.method, live.route, live.key
    FROM identity_idempotency AS live
    WHERE live.expires_at < $1
    ORDER BY live.expires_at ASC
    LIMIT $2
)
`

type PurgeExpiredAttemptsParams struct {
	Now   pgtype.Timestamptz `json:"now"`
	Batch int32              `json:"batch"`
}

func (q *Queries) PurgeExpiredAttempts(ctx context.Context, arg PurgeExpiredAttemptsParams) (int64, error) {
	result, err := q.db.Exec(ctx, purgeExpiredAttempts, arg.Now, arg.Batch)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const reserveAttempt = `-- name: ReserveAttempt :one

INSERT INTO identity_idempotency
    (contributor_id, method, route, key, request_hash, expires_at)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (contributor_id, method, route, key) DO NOTHING
RETURNING contributor_id, method, route, key, request_hash, response_code,
    response_json, created_at, expires_at
`

type ReserveAttemptParams struct {
	ContributorID pgtype.UUID        `json:"contributor_id"`
	Method        string             `json:"method"`
	Route         string             `json:"route"`
	Key           string             `json:"key"`
	RequestHash   string             `json:"request_hash"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
}

// Owned by identity. Retries replay the stored outcome; a changed body for
// the same key conflicts instead of executing twice.
func (q *Queries) ReserveAttempt(ctx context.Context, arg ReserveAttemptParams) (IdentityIdempotency, error) {
	row := q.db.QueryRow(ctx, reserveAttempt,
		arg.ContributorID,
		arg.Method,
		arg.Route,
		arg.Key,
		arg.RequestHash,
		arg.ExpiresAt,
	)
	var i IdentityIdempotency
	err := row.Scan(
		&i.ContributorID,
		&i.Method,
		&i.Route,
		&i.Key,
		&i.RequestHash,
		&i.ResponseCode,
		&i.ResponseJson,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
