// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package identity

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type IdentityChallenge struct {
	ID          pgtype.UUID        `json:"id"`
	NonceHash   string             `json:"nonce_hash"`
	Fingerprint string             `json:"fingerprint"`
	Purpose     string             `json:"purpose"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
	ConsumedAt  pgtype.Timestamptz `json:"consumed_at"`
}

type IdentityContributor struct {
	ID               pgtype.UUID        `json:"id"`
	Status           string             `json:"status"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
	AttributionToken pgtype.Text        `json:"attribution_token"`
}

type IdentityIdempotency struct {
	ContributorID pgtype.UUID        `json:"contributor_id"`
	Method        string             `json:"method"`
	Route         string             `json:"route"`
	Key           string             `json:"key"`
	RequestHash   string             `json:"request_hash"`
	ResponseCode  pgtype.Int4        `json:"response_code"`
	ResponseJson  []byte             `json:"response_json"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
}

type IdentityKey struct {
	ID            pgtype.UUID        `json:"id"`
	ContributorID pgtype.UUID        `json:"contributor_id"`
	Algorithm     string             `json:"algorithm"`
	PublicJwk     string             `json:"public_jwk"`
	Fingerprint   string             `json:"fingerprint"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	RevokedAt     pgtype.Timestamptz `json:"revoked_at"`
}

type IdentityRateWindow struct {
	SubjectDigest string             `json:"subject_digest"`
	Operation     string             `json:"operation"`
	WindowStart   pgtype.Timestamptz `json:"window_start"`
	Count         int32              `json:"count"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
}
