// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: quotas.sql

package identity

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cleanupExpiredWindows = `-- name: CleanupExpiredWindows :execrows
DELETE FROM identity_rate_windows WHERE expires_at < now()
`

func (q *Queries) CleanupExpiredWindows(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, cleanupExpiredWindows)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const consumeQuota = `-- name: ConsumeQuota :one

INSERT INTO identity_rate_windows
    (subject_digest, operation, window_start, count, expires_at)
VALUES ($1, $2, $3, 1, $4)
ON CONFLICT (subject_digest, operation, window_start)
DO UPDATE SET count = identity_rate_windows.count + 1
WHERE identity_rate_windows.count < $5
RETURNING count, expires_at
`

type ConsumeQuotaParams struct {
	SubjectDigest string             `json:"subject_digest"`
	Operation     string             `json:"operation"`
	WindowStart   pgtype.Timestamptz `json:"window_start"`
	ExpiresAt     pgtype.Timestamptz `json:"expires_at"`
	Cap           int32              `json:"cap"`
}

type ConsumeQuotaRow struct {
	Count     int32              `json:"count"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

// Owned by identity. Quota checks share the business transaction's pool
// but never its rows: a denied check runs before expensive work starts.
func (q *Queries) ConsumeQuota(ctx context.Context, arg ConsumeQuotaParams) (ConsumeQuotaRow, error) {
	row := q.db.QueryRow(ctx, consumeQuota,
		arg.SubjectDigest,
		arg.Operation,
		arg.WindowStart,
		arg.ExpiresAt,
		arg.Cap,
	)
	var i ConsumeQuotaRow
	err := row.Scan(&i.Count, &i.ExpiresAt)
	return i, err
}
