// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: registration.sql

package identity

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeChallenge = `-- name: ConsumeChallenge :one
UPDATE identity_challenges
SET consumed_at = now()
WHERE id = $1
    AND consumed_at IS NULL
    AND expires_at > now()
RETURNING id, nonce_hash, fingerprint, purpose
`

type ConsumeChallengeRow struct {
	ID          pgtype.UUID `json:"id"`
	NonceHash   string      `json:"nonce_hash"`
	Fingerprint string      `json:"fingerprint"`
	Purpose     string      `json:"purpose"`
}

func (q *Queries) ConsumeChallenge(ctx context.Context, id pgtype.UUID) (ConsumeChallengeRow, error) {
	row := q.db.QueryRow(ctx, consumeChallenge, id)
	var i ConsumeChallengeRow
	err := row.Scan(
		&i.ID,
		&i.NonceHash,
		&i.Fingerprint,
		&i.Purpose,
	)
	return i, err
}

const createChallenge = `-- name: CreateChallenge :one

INSERT INTO identity_challenges (id, nonce_hash, fingerprint, purpose, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type CreateChallengeParams struct {
	ID          pgtype.UUID        `json:"id"`
	NonceHash   string             `json:"nonce_hash"`
	Fingerprint string             `json:"fingerprint"`
	Purpose     string             `json:"purpose"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

// Owned by identity. Modules must not import another module's generated
// package; cross-module reads use owned queries documented in DATA_MODEL.
func (q *Queries) CreateChallenge(ctx context.Context, arg CreateChallengeParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createChallenge,
		arg.ID,
		arg.NonceHash,
		arg.Fingerprint,
		arg.Purpose,
		arg.ExpiresAt,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const createContributor = `-- name: CreateContributor :one
INSERT INTO identity_contributors (id)
VALUES ($1)
RETURNING id
`

func (q *Queries) CreateContributor(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createContributor, id)
	var id_2 pgtype.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const createKey = `-- name: CreateKey :one
INSERT INTO identity_keys (id, contributor_id, algorithm, public_jwk, fingerprint)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (fingerprint) DO NOTHING
RETURNING id, contributor_id
`

type CreateKeyParams struct {
	ID            pgtype.UUID `json:"id"`
	ContributorID pgtype.UUID `json:"contributor_id"`
	Algorithm     string      `json:"algorithm"`
	PublicJwk     string      `json:"public_jwk"`
	Fingerprint   string      `json:"fingerprint"`
}

type CreateKeyRow struct {
	ID            pgtype.UUID `json:"id"`
	ContributorID pgtype.UUID `json:"contributor_id"`
}

func (q *Queries) CreateKey(ctx context.Context, arg CreateKeyParams) (CreateKeyRow, error) {
	row := q.db.QueryRow(ctx, createKey,
		arg.ID,
		arg.ContributorID,
		arg.Algorithm,
		arg.PublicJwk,
		arg.Fingerprint,
	)
	var i CreateKeyRow
	err := row.Scan(&i.ID, &i.ContributorID)
	return i, err
}

const findKeyByFingerprint = `-- name: FindKeyByFingerprint :one
SELECT id, contributor_id, algorithm, public_jwk, fingerprint, created_at, revoked_at
FROM identity_keys
WHERE fingerprint = $1
`

func (q *Queries) FindKeyByFingerprint(ctx context.Context, fingerprint string) (IdentityKey, error) {
	row := q.db.QueryRow(ctx, findKeyByFingerprint, fingerprint)
	var i IdentityKey
	err := row.Scan(
		&i.ID,
		&i.ContributorID,
		&i.Algorithm,
		&i.PublicJwk,
		&i.Fingerprint,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getChallenge = `-- name: GetChallenge :one
SELECT id, nonce_hash, fingerprint, purpose, expires_at, consumed_at
FROM identity_challenges
WHERE id = $1
`

func (q *Queries) GetChallenge(ctx context.Context, id pgtype.UUID) (IdentityChallenge, error) {
	row := q.db.QueryRow(ctx, getChallenge, id)
	var i IdentityChallenge
	err := row.Scan(
		&i.ID,
		&i.NonceHash,
		&i.Fingerprint,
		&i.Purpose,
		&i.ExpiresAt,
		&i.ConsumedAt,
	)
	return i, err
}

const getContributor = `-- name: GetContributor :one
SELECT id, status, created_at, deleted_at
FROM identity_contributors
WHERE id = $1
`

func (q *Queries) GetContributor(ctx context.Context, id pgtype.UUID) (IdentityContributor, error) {
	row := q.db.QueryRow(ctx, getContributor, id)
	var i IdentityContributor
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const revokeKey = `-- name: RevokeKey :execrows
UPDATE identity_keys
SET revoked_at = now()
WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeKey(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, revokeKey, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
