// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: registration.sql

package identity

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const consumeChallenge = `-- name: ConsumeChallenge :one
UPDATE identity_challenges
SET consumed_at = now()
WHERE id = $1
    AND consumed_at IS NULL
    AND expires_at > now()
RETURNING id, nonce_hash, fingerprint, purpose
`

type ConsumeChallengeRow struct {
	ID          pgtype.UUID `json:"id"`
	NonceHash   string      `json:"nonce_hash"`
	Fingerprint string      `json:"fingerprint"`
	Purpose     string      `json:"purpose"`
}

func (q *Queries) ConsumeChallenge(ctx context.Context, id pgtype.UUID) (ConsumeChallengeRow, error) {
	row := q.db.QueryRow(ctx, consumeChallenge, id)
	var i ConsumeChallengeRow
	err := row.Scan(
		&i.ID,
		&i.NonceHash,
		&i.Fingerprint,
		&i.Purpose,
	)
	return i, err
}

const createChallenge = `-- name: CreateChallenge :one

INSERT INTO identity_challenges (id, nonce_hash, fingerprint, purpose, expires_at)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type CreateChallengeParams struct {
	ID          pgtype.UUID        `json:"id"`
	NonceHash   string             `json:"nonce_hash"`
	Fingerprint string             `json:"fingerprint"`
	Purpose     string             `json:"purpose"`
	ExpiresAt   pgtype.Timestamptz `json:"expires_at"`
}

// Owned by identity. Modules must not import another module's generated
// package; cross-module reads use owned queries documented in DATA_MODEL.
func (q *Queries) CreateChallenge(ctx context.Context, arg CreateChallengeParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createChallenge,
		arg.ID,
		arg.NonceHash,
		arg.Fingerprint,
		arg.Purpose,
		arg.ExpiresAt,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const createContributor = `-- name: CreateContributor :one
INSERT INTO identity_contributors (id)
VALUES ($1)
RETURNING id
`

func (q *Queries) CreateContributor(ctx context.Context, id pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createContributor, id)
	var id_2 pgtype.UUID
	err := row.Scan(&id_2)
	return id_2, err
}

const createKey = `-- name: CreateKey :one
INSERT INTO identity_keys (id, contributor_id, algorithm, public_jwk, fingerprint)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (fingerprint) DO NOTHING
RETURNING id, contributor_id
`

type CreateKeyParams struct {
	ID            pgtype.UUID `json:"id"`
	ContributorID pgtype.UUID `json:"contributor_id"`
	Algorithm     string      `json:"algorithm"`
	PublicJwk     string      `json:"public_jwk"`
	Fingerprint   string      `json:"fingerprint"`
}

type CreateKeyRow struct {
	ID            pgtype.UUID `json:"id"`
	ContributorID pgtype.UUID `json:"contributor_id"`
}

func (q *Queries) CreateKey(ctx context.Context, arg CreateKeyParams) (CreateKeyRow, error) {
	row := q.db.QueryRow(ctx, createKey,
		arg.ID,
		arg.ContributorID,
		arg.Algorithm,
		arg.PublicJwk,
		arg.Fingerprint,
	)
	var i CreateKeyRow
	err := row.Scan(&i.ID, &i.ContributorID)
	return i, err
}

const deleteContributor = `-- name: DeleteContributor :execrows

UPDATE identity_contributors
SET status = 'deleted', attribution_token = NULL, deleted_at = now()
WHERE id = $1 AND status != 'deleted'
`

// Erasure (P07-T04, B-BR-016): revoke writes and unlink identity in the
// narrow privacy workflow. Only these queries may move a contributor to
// deleted or clear its attribution token; normal writes never touch
// them.
func (q *Queries) DeleteContributor(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteContributor, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findKeyByFingerprint = `-- name: FindKeyByFingerprint :one
SELECT id, contributor_id, algorithm, public_jwk, fingerprint, created_at, revoked_at
FROM identity_keys
WHERE fingerprint = $1
`

func (q *Queries) FindKeyByFingerprint(ctx context.Context, fingerprint string) (IdentityKey, error) {
	row := q.db.QueryRow(ctx, findKeyByFingerprint, fingerprint)
	var i IdentityKey
	err := row.Scan(
		&i.ID,
		&i.ContributorID,
		&i.Algorithm,
		&i.PublicJwk,
		&i.Fingerprint,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const getAttributionToken = `-- name: GetAttributionToken :one
SELECT attribution_token FROM identity_contributors WHERE id = $1
`

func (q *Queries) GetAttributionToken(ctx context.Context, id pgtype.UUID) (pgtype.Text, error) {
	row := q.db.QueryRow(ctx, getAttributionToken, id)
	var attribution_token pgtype.Text
	err := row.Scan(&attribution_token)
	return attribution_token, err
}

const getChallenge = `-- name: GetChallenge :one
SELECT id, nonce_hash, fingerprint, purpose, expires_at, consumed_at
FROM identity_challenges
WHERE id = $1
`

func (q *Queries) GetChallenge(ctx context.Context, id pgtype.UUID) (IdentityChallenge, error) {
	row := q.db.QueryRow(ctx, getChallenge, id)
	var i IdentityChallenge
	err := row.Scan(
		&i.ID,
		&i.NonceHash,
		&i.Fingerprint,
		&i.Purpose,
		&i.ExpiresAt,
		&i.ConsumedAt,
	)
	return i, err
}

const getContributor = `-- name: GetContributor :one
SELECT id, status, created_at, deleted_at
FROM identity_contributors
WHERE id = $1
`

type GetContributorRow struct {
	ID        pgtype.UUID        `json:"id"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) GetContributor(ctx context.Context, id pgtype.UUID) (GetContributorRow, error) {
	row := q.db.QueryRow(ctx, getContributor, id)
	var i GetContributorRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const oldestExpiredChallenge = `-- name: OldestExpiredChallenge :one

SELECT expires_at
FROM identity_challenges
WHERE expires_at < $1
ORDER BY expires_at ASC
LIMIT 1
`

// Retention (P07-T05): purge expired challenges in bounded batches.
// Consumed challenges stay until expiry so replays keep failing
// closed instead of looking unknown.
func (q *Queries) OldestExpiredChallenge(ctx context.Context, now pgtype.Timestamptz) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, oldestExpiredChallenge, now)
	var expires_at pgtype.Timestamptz
	err := row.Scan(&expires_at)
	return expires_at, err
}

const purgeExpiredChallenges = `-- name: PurgeExpiredChallenges :execrows
DELETE FROM identity_challenges AS dead
WHERE dead.id IN (
    SELECT live.id FROM identity_challenges AS live
    WHERE live.expires_at < $1
    ORDER BY live.expires_at ASC
    LIMIT $2
)
`

type PurgeExpiredChallengesParams struct {
	Now   pgtype.Timestamptz `json:"now"`
	Batch int32              `json:"batch"`
}

func (q *Queries) PurgeExpiredChallenges(ctx context.Context, arg PurgeExpiredChallengesParams) (int64, error) {
	result, err := q.db.Exec(ctx, purgeExpiredChallenges, arg.Now, arg.Batch)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeContributorKeys = `-- name: RevokeContributorKeys :execrows
UPDATE identity_keys
SET revoked_at = now()
WHERE contributor_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeContributorKeys(ctx context.Context, contributorID pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, revokeContributorKeys, contributorID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeKey = `-- name: RevokeKey :execrows
UPDATE identity_keys
SET revoked_at = now()
WHERE id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeKey(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, revokeKey, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setAttributionToken = `-- name: SetAttributionToken :execrows
UPDATE identity_contributors
SET attribution_token = $1
WHERE id = $2 AND attribution_token IS NULL
`

type SetAttributionTokenParams struct {
	Token pgtype.Text `json:"token"`
	ID    pgtype.UUID `json:"id"`
}

func (q *Queries) SetAttributionToken(ctx context.Context, arg SetAttributionTokenParams) (int64, error) {
	result, err := q.db.Exec(ctx, setAttributionToken, arg.Token, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
