// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: feed.sql

package community

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cityFeed = `-- name: CityFeed :many
SELECT p.station_id, s.display_name, p.fuel_product, p.unit,
 p.amount_milli_brl, p.confidence, p.independent_supporters,
 p.confirmation_count, p.anchor_received_at, p.expires_at, p.projection_version
FROM directory_stations s
JOIN community_current_prices p ON p.station_id = s.id
WHERE s.state = $1 AND s.municipality_code = $2 AND s.status = 'active'
 AND p.fuel_product = $3 AND p.unit = $4
 AND p.condition_kind = 'STANDARD' AND p.qualifier_key = 'STANDARD'
 AND p.availability = 'AVAILABLE' AND p.amount_milli_brl IS NOT NULL
 AND p.anchor_received_at IS NOT NULL AND p.anchor_received_at <= $5
 AND p.expires_at > $5
 AND (NOT $6::boolean OR
  ($7::text = 'recent' AND (p.anchor_received_at < $8 OR
    (p.anchor_received_at = $8 AND p.station_id::text > $9::text))) OR
  ($7::text = 'cheapest' AND (p.amount_milli_brl > $10::bigint OR
    (p.amount_milli_brl = $10::bigint AND p.station_id::text > $9::text))))
ORDER BY CASE WHEN $7::text = 'cheapest' THEN p.amount_milli_brl END ASC,
 CASE WHEN $7::text = 'recent' THEN p.anchor_received_at END DESC, p.station_id ASC
LIMIT $11::int
`

type CityFeedParams struct {
	State            pgtype.Text        `json:"state"`
	MunicipalityCode pgtype.Text        `json:"municipality_code"`
	FuelProduct      string             `json:"fuel_product"`
	Unit             string             `json:"unit"`
	Now              pgtype.Timestamptz `json:"now"`
	HasCursor        bool               `json:"has_cursor"`
	SortOrder        string             `json:"sort_order"`
	AfterTime        pgtype.Timestamptz `json:"after_time"`
	AfterID          string             `json:"after_id"`
	AfterAmount      int64              `json:"after_amount"`
	LimitPlusOne     int32              `json:"limit_plus_one"`
}

type CityFeedRow struct {
	StationID             pgtype.UUID        `json:"station_id"`
	DisplayName           string             `json:"display_name"`
	FuelProduct           string             `json:"fuel_product"`
	Unit                  string             `json:"unit"`
	AmountMilliBrl        pgtype.Int8        `json:"amount_milli_brl"`
	Confidence            string             `json:"confidence"`
	IndependentSupporters int32              `json:"independent_supporters"`
	ConfirmationCount     int32              `json:"confirmation_count"`
	AnchorReceivedAt      pgtype.Timestamptz `json:"anchor_received_at"`
	ExpiresAt             pgtype.Timestamptz `json:"expires_at"`
	ProjectionVersion     int64              `json:"projection_version"`
}

// Owned public community read: the explicitly declared directory join reads
// only canonical public identity/city fields, never another module's private data.
func (q *Queries) CityFeed(ctx context.Context, arg CityFeedParams) ([]CityFeedRow, error) {
	rows, err := q.db.Query(ctx, cityFeed,
		arg.State,
		arg.MunicipalityCode,
		arg.FuelProduct,
		arg.Unit,
		arg.Now,
		arg.HasCursor,
		arg.SortOrder,
		arg.AfterTime,
		arg.AfterID,
		arg.AfterAmount,
		arg.LimitPlusOne,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CityFeedRow
	for rows.Next() {
		var i CityFeedRow
		if err := rows.Scan(
			&i.StationID,
			&i.DisplayName,
			&i.FuelProduct,
			&i.Unit,
			&i.AmountMilliBrl,
			&i.Confidence,
			&i.IndependentSupporters,
			&i.ConfirmationCount,
			&i.AnchorReceivedAt,
			&i.ExpiresAt,
			&i.ProjectionVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
