// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package community

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CommunityConfirmation struct {
	ID                 pgtype.UUID        `json:"id"`
	ObservationID      pgtype.UUID        `json:"observation_id"`
	ContributorRef     string             `json:"contributor_ref"`
	ClientSubmissionID string             `json:"client_submission_id"`
	ReceivedAt         pgtype.Timestamptz `json:"received_at"`
	PolicyVersion      string             `json:"policy_version"`
}

type CommunityCurrentPrice struct {
	StationID                   pgtype.UUID        `json:"station_id"`
	FuelProduct                 string             `json:"fuel_product"`
	Unit                        string             `json:"unit"`
	ConditionKind               string             `json:"condition_kind"`
	QualifierKey                string             `json:"qualifier_key"`
	AmountMilliBrl              pgtype.Int8        `json:"amount_milli_brl"`
	Availability                string             `json:"availability"`
	Confidence                  string             `json:"confidence"`
	RepresentativeObservationID pgtype.UUID        `json:"representative_observation_id"`
	IndependentSupporters       int32              `json:"independent_supporters"`
	ConfirmationCount           int32              `json:"confirmation_count"`
	AnchorReceivedAt            pgtype.Timestamptz `json:"anchor_received_at"`
	ExpiresAt                   pgtype.Timestamptz `json:"expires_at"`
	NextRecomputeAt             pgtype.Timestamptz `json:"next_recompute_at"`
	ComputedAt                  pgtype.Timestamptz `json:"computed_at"`
	ProjectionVersion           int64              `json:"projection_version"`
	AlgorithmVersion            string             `json:"algorithm_version"`
	PolicyConfigVersion         string             `json:"policy_config_version"`
}

type CommunityDispute struct {
	ID                  pgtype.UUID        `json:"id"`
	TargetObservationID pgtype.UUID        `json:"target_observation_id"`
	ContributorRef      string             `json:"contributor_ref"`
	ClientSubmissionID  string             `json:"client_submission_id"`
	Reason              string             `json:"reason"`
	Detail              string             `json:"detail"`
	ReplacementID       pgtype.UUID        `json:"replacement_id"`
	Status              string             `json:"status"`
	ReceivedAt          pgtype.Timestamptz `json:"received_at"`
	PolicyVersion       string             `json:"policy_version"`
}

type CommunityObservation struct {
	ID                 pgtype.UUID        `json:"id"`
	ContributorRef     string             `json:"contributor_ref"`
	ClientSubmissionID string             `json:"client_submission_id"`
	StationID          pgtype.UUID        `json:"station_id"`
	FuelProduct        string             `json:"fuel_product"`
	Unit               string             `json:"unit"`
	AmountMilliBrl     int64              `json:"amount_milli_brl"`
	RawPriceText       string             `json:"raw_price_text"`
	ConditionKind      string             `json:"condition_kind"`
	QualifierKey       string             `json:"qualifier_key"`
	EvidenceID         pgtype.UUID        `json:"evidence_id"`
	ReceivedAt         pgtype.Timestamptz `json:"received_at"`
	ClaimedCapturedAt  pgtype.Timestamptz `json:"claimed_captured_at"`
	SupersedesID       pgtype.UUID        `json:"supersedes_id"`
	PolicyVersion      string             `json:"policy_version"`
}

type CommunityObservationDecision struct {
	ID            pgtype.UUID        `json:"id"`
	ObservationID pgtype.UUID        `json:"observation_id"`
	Sequence      int64              `json:"sequence"`
	ToState       string             `json:"to_state"`
	ReasonCodes   []string           `json:"reason_codes"`
	PolicyVersion string             `json:"policy_version"`
	OccurredAt    pgtype.Timestamptz `json:"occurred_at"`
	ActorRef      string             `json:"actor_ref"`
}

type CommunityObservationSignal struct {
	ObservationID  pgtype.UUID        `json:"observation_id"`
	ProximityBand  string             `json:"proximity_band"`
	RecencyBand    string             `json:"recency_band"`
	CaptureFlag    string             `json:"capture_flag"`
	PhotoSignal    string             `json:"photo_signal"`
	DuplicateCount int32              `json:"duplicate_count"`
	RegionalBand   string             `json:"regional_band"`
	RiskCodes      []string           `json:"risk_codes"`
	NeedsReview    bool               `json:"needs_review"`
	PolicyVersion  string             `json:"policy_version"`
	ComputedAt     pgtype.Timestamptz `json:"computed_at"`
}

type CommunityProjectionInput struct {
	ProjectionKey      string             `json:"projection_key"`
	Version            int64              `json:"version"`
	InputCutoff        pgtype.Timestamptz `json:"input_cutoff"`
	SupportingEventIds []string           `json:"supporting_event_ids"`
	ReasonCodes        []string           `json:"reason_codes"`
	ComputedAt         pgtype.Timestamptz `json:"computed_at"`
}

type DirectoryIdentifier struct {
	ID               pgtype.UUID        `json:"id"`
	StationID        pgtype.UUID        `json:"station_id"`
	Kind             string             `json:"kind"`
	NormalizedValue  string             `json:"normalized_value"`
	ValidFrom        pgtype.Timestamptz `json:"valid_from"`
	ValidTo          pgtype.Timestamptz `json:"valid_to"`
	SourceRevisionID pgtype.Text        `json:"source_revision_id"`
}

type DirectoryLocationRevision struct {
	ID              pgtype.UUID        `json:"id"`
	StationID       pgtype.UUID        `json:"station_id"`
	Point           interface{}        `json:"point"`
	Quality         string             `json:"quality"`
	Provider        string             `json:"provider"`
	SourceReference string             `json:"source_reference"`
	ObtainedAt      pgtype.Timestamptz `json:"obtained_at"`
	SupersedesID    pgtype.UUID        `json:"supersedes_id"`
}

type DirectoryStation struct {
	ID                pgtype.UUID        `json:"id"`
	DisplayName       string             `json:"display_name"`
	Address           []byte             `json:"address"`
	MunicipalityCode  pgtype.Text        `json:"municipality_code"`
	State             pgtype.Text        `json:"state"`
	Status            string             `json:"status"`
	CurrentPoint      interface{}        `json:"current_point"`
	CurrentQuality    pgtype.Text        `json:"current_quality"`
	CurrentRevisionID pgtype.UUID        `json:"current_revision_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}
