// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package community

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type CommunityObservation struct {
	ID                 pgtype.UUID        `json:"id"`
	ContributorRef     string             `json:"contributor_ref"`
	ClientSubmissionID string             `json:"client_submission_id"`
	StationID          pgtype.UUID        `json:"station_id"`
	FuelProduct        string             `json:"fuel_product"`
	Unit               string             `json:"unit"`
	AmountMilliBrl     int64              `json:"amount_milli_brl"`
	RawPriceText       string             `json:"raw_price_text"`
	ConditionKind      string             `json:"condition_kind"`
	QualifierKey       string             `json:"qualifier_key"`
	EvidenceID         pgtype.UUID        `json:"evidence_id"`
	ReceivedAt         pgtype.Timestamptz `json:"received_at"`
	ClaimedCapturedAt  pgtype.Timestamptz `json:"claimed_captured_at"`
	SupersedesID       pgtype.UUID        `json:"supersedes_id"`
	PolicyVersion      string             `json:"policy_version"`
}

type CommunityObservationDecision struct {
	ID            pgtype.UUID        `json:"id"`
	ObservationID pgtype.UUID        `json:"observation_id"`
	Sequence      int64              `json:"sequence"`
	ToState       string             `json:"to_state"`
	ReasonCodes   []string           `json:"reason_codes"`
	PolicyVersion string             `json:"policy_version"`
	OccurredAt    pgtype.Timestamptz `json:"occurred_at"`
	ActorRef      string             `json:"actor_ref"`
}

type DirectoryIdentifier struct {
	ID               pgtype.UUID        `json:"id"`
	StationID        pgtype.UUID        `json:"station_id"`
	Kind             string             `json:"kind"`
	NormalizedValue  string             `json:"normalized_value"`
	ValidFrom        pgtype.Timestamptz `json:"valid_from"`
	ValidTo          pgtype.Timestamptz `json:"valid_to"`
	SourceRevisionID pgtype.Text        `json:"source_revision_id"`
}

type DirectoryLocationRevision struct {
	ID              pgtype.UUID        `json:"id"`
	StationID       pgtype.UUID        `json:"station_id"`
	Point           interface{}        `json:"point"`
	Quality         string             `json:"quality"`
	Provider        string             `json:"provider"`
	SourceReference string             `json:"source_reference"`
	ObtainedAt      pgtype.Timestamptz `json:"obtained_at"`
	SupersedesID    pgtype.UUID        `json:"supersedes_id"`
}

type DirectoryStation struct {
	ID                pgtype.UUID        `json:"id"`
	DisplayName       string             `json:"display_name"`
	Address           []byte             `json:"address"`
	MunicipalityCode  pgtype.Text        `json:"municipality_code"`
	State             pgtype.Text        `json:"state"`
	Status            string             `json:"status"`
	CurrentPoint      interface{}        `json:"current_point"`
	CurrentQuality    pgtype.Text        `json:"current_quality"`
	CurrentRevisionID pgtype.UUID        `json:"current_revision_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}
