// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: observations.sql

package community

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const appendDecision = `-- name: AppendDecision :one
INSERT INTO community_observation_decisions
    (id, observation_id, sequence, to_state, reason_codes, policy_version,
     occurred_at, actor_ref)
VALUES ($1, $2, $3, $4, $5,
    $6, $7, $8)
RETURNING id
`

type AppendDecisionParams struct {
	ID            pgtype.UUID        `json:"id"`
	ObservationID pgtype.UUID        `json:"observation_id"`
	Sequence      int64              `json:"sequence"`
	ToState       string             `json:"to_state"`
	ReasonCodes   []string           `json:"reason_codes"`
	PolicyVersion string             `json:"policy_version"`
	OccurredAt    pgtype.Timestamptz `json:"occurred_at"`
	ActorRef      string             `json:"actor_ref"`
}

func (q *Queries) AppendDecision(ctx context.Context, arg AppendDecisionParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, appendDecision,
		arg.ID,
		arg.ObservationID,
		arg.Sequence,
		arg.ToState,
		arg.ReasonCodes,
		arg.PolicyVersion,
		arg.OccurredAt,
		arg.ActorRef,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getObservation = `-- name: GetObservation :one
SELECT id, contributor_ref, client_submission_id, station_id, fuel_product,
    unit, amount_milli_brl, raw_price_text, condition_kind, qualifier_key,
    evidence_id, received_at, claimed_captured_at, supersedes_id, policy_version
FROM community_observations
WHERE id = $1
`

func (q *Queries) GetObservation(ctx context.Context, id pgtype.UUID) (CommunityObservation, error) {
	row := q.db.QueryRow(ctx, getObservation, id)
	var i CommunityObservation
	err := row.Scan(
		&i.ID,
		&i.ContributorRef,
		&i.ClientSubmissionID,
		&i.StationID,
		&i.FuelProduct,
		&i.Unit,
		&i.AmountMilliBrl,
		&i.RawPriceText,
		&i.ConditionKind,
		&i.QualifierKey,
		&i.EvidenceID,
		&i.ReceivedAt,
		&i.ClaimedCapturedAt,
		&i.SupersedesID,
		&i.PolicyVersion,
	)
	return i, err
}

const getObservationByNaturalKey = `-- name: GetObservationByNaturalKey :one
SELECT id, contributor_ref, client_submission_id, station_id, fuel_product,
    unit, amount_milli_brl, raw_price_text, condition_kind, qualifier_key,
    evidence_id, received_at, claimed_captured_at, supersedes_id, policy_version
FROM community_observations
WHERE contributor_ref = $1 AND client_submission_id = $2
`

type GetObservationByNaturalKeyParams struct {
	ContributorRef     string `json:"contributor_ref"`
	ClientSubmissionID string `json:"client_submission_id"`
}

func (q *Queries) GetObservationByNaturalKey(ctx context.Context, arg GetObservationByNaturalKeyParams) (CommunityObservation, error) {
	row := q.db.QueryRow(ctx, getObservationByNaturalKey, arg.ContributorRef, arg.ClientSubmissionID)
	var i CommunityObservation
	err := row.Scan(
		&i.ID,
		&i.ContributorRef,
		&i.ClientSubmissionID,
		&i.StationID,
		&i.FuelProduct,
		&i.Unit,
		&i.AmountMilliBrl,
		&i.RawPriceText,
		&i.ConditionKind,
		&i.QualifierKey,
		&i.EvidenceID,
		&i.ReceivedAt,
		&i.ClaimedCapturedAt,
		&i.SupersedesID,
		&i.PolicyVersion,
	)
	return i, err
}

const insertObservation = `-- name: InsertObservation :one

INSERT INTO community_observations
    (id, contributor_ref, client_submission_id, station_id, fuel_product,
     unit, amount_milli_brl, raw_price_text, condition_kind, qualifier_key,
     evidence_id, received_at, claimed_captured_at, supersedes_id, policy_version)
VALUES ($1, $2, $3, $4,
    $5, $6, $7, $8,
    $9, $10, $11, $12,
    $13, $14, $15)
ON CONFLICT (contributor_ref, client_submission_id) DO NOTHING
RETURNING id
`

type InsertObservationParams struct {
	ID                 pgtype.UUID        `json:"id"`
	ContributorRef     string             `json:"contributor_ref"`
	ClientSubmissionID string             `json:"client_submission_id"`
	StationID          pgtype.UUID        `json:"station_id"`
	FuelProduct        string             `json:"fuel_product"`
	Unit               string             `json:"unit"`
	AmountMilliBrl     int64              `json:"amount_milli_brl"`
	RawPriceText       string             `json:"raw_price_text"`
	ConditionKind      string             `json:"condition_kind"`
	QualifierKey       string             `json:"qualifier_key"`
	EvidenceID         pgtype.UUID        `json:"evidence_id"`
	ReceivedAt         pgtype.Timestamptz `json:"received_at"`
	ClaimedCapturedAt  pgtype.Timestamptz `json:"claimed_captured_at"`
	SupersedesID       pgtype.UUID        `json:"supersedes_id"`
	PolicyVersion      string             `json:"policy_version"`
}

// Owned by community. Facts and decisions are insert-only: this file
// contains no UPDATE or DELETE against community tables, and review
// tooling must keep it that way. Corrections append new facts.
func (q *Queries) InsertObservation(ctx context.Context, arg InsertObservationParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertObservation,
		arg.ID,
		arg.ContributorRef,
		arg.ClientSubmissionID,
		arg.StationID,
		arg.FuelProduct,
		arg.Unit,
		arg.AmountMilliBrl,
		arg.RawPriceText,
		arg.ConditionKind,
		arg.QualifierKey,
		arg.EvidenceID,
		arg.ReceivedAt,
		arg.ClaimedCapturedAt,
		arg.SupersedesID,
		arg.PolicyVersion,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const listByContributor = `-- name: ListByContributor :many
SELECT id, contributor_ref, client_submission_id, station_id, fuel_product,
    unit, amount_milli_brl, raw_price_text, condition_kind, qualifier_key,
    evidence_id, received_at, claimed_captured_at, supersedes_id, policy_version
FROM community_observations
WHERE contributor_ref = $1
    AND ($2::boolean = FALSE OR
        (received_at, id::text) < ($3, $4::text))
ORDER BY received_at DESC, id::text DESC
LIMIT $5
`

type ListByContributorParams struct {
	ContributorRef string             `json:"contributor_ref"`
	HasCursor      bool               `json:"has_cursor"`
	AfterTime      pgtype.Timestamptz `json:"after_time"`
	AfterID        string             `json:"after_id"`
	LimitPlusOne   int32              `json:"limit_plus_one"`
}

func (q *Queries) ListByContributor(ctx context.Context, arg ListByContributorParams) ([]CommunityObservation, error) {
	rows, err := q.db.Query(ctx, listByContributor,
		arg.ContributorRef,
		arg.HasCursor,
		arg.AfterTime,
		arg.AfterID,
		arg.LimitPlusOne,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CommunityObservation
	for rows.Next() {
		var i CommunityObservation
		if err := rows.Scan(
			&i.ID,
			&i.ContributorRef,
			&i.ClientSubmissionID,
			&i.StationID,
			&i.FuelProduct,
			&i.Unit,
			&i.AmountMilliBrl,
			&i.RawPriceText,
			&i.ConditionKind,
			&i.QualifierKey,
			&i.EvidenceID,
			&i.ReceivedAt,
			&i.ClaimedCapturedAt,
			&i.SupersedesID,
			&i.PolicyVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDecisions = `-- name: ListDecisions :many
SELECT id, observation_id, sequence, to_state, reason_codes, policy_version,
    occurred_at, actor_ref
FROM community_observation_decisions
WHERE observation_id = $1
ORDER BY sequence ASC
`

func (q *Queries) ListDecisions(ctx context.Context, observationID pgtype.UUID) ([]CommunityObservationDecision, error) {
	rows, err := q.db.Query(ctx, listDecisions, observationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CommunityObservationDecision
	for rows.Next() {
		var i CommunityObservationDecision
		if err := rows.Scan(
			&i.ID,
			&i.ObservationID,
			&i.Sequence,
			&i.ToState,
			&i.ReasonCodes,
			&i.PolicyVersion,
			&i.OccurredAt,
			&i.ActorRef,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unlinkConfirmations = `-- name: UnlinkConfirmations :execrows
UPDATE community_confirmations
SET contributor_ref = 'erased-' || id::text
WHERE contributor_ref = $1
`

func (q *Queries) UnlinkConfirmations(ctx context.Context, contributorRef string) (int64, error) {
	result, err := q.db.Exec(ctx, unlinkConfirmations, contributorRef)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const unlinkDisputes = `-- name: UnlinkDisputes :execrows
UPDATE community_disputes
SET contributor_ref = 'erased-' || id::text
WHERE contributor_ref = $1
`

func (q *Queries) UnlinkDisputes(ctx context.Context, contributorRef string) (int64, error) {
	result, err := q.db.Exec(ctx, unlinkDisputes, contributorRef)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const unlinkObservations = `-- name: UnlinkObservations :execrows

UPDATE community_observations
SET contributor_ref = $1
WHERE contributor_ref = $2
`

type UnlinkObservationsParams struct {
	AnonRef        string `json:"anon_ref"`
	ContributorRef string `json:"contributor_ref"`
}

// Erasure (P07-T04, B-BR-016, ADR-008): unlink contributor links in the
// narrow privacy workflow while immutable price facts stay for history.
// Observations keep product/price/provenance with an anonymized
// reference; reporter references unlink per row so pair uniqueness
// survives. Only these queries may rewrite contributor references;
// normal writes never touch them.
func (q *Queries) UnlinkObservations(ctx context.Context, arg UnlinkObservationsParams) (int64, error) {
	result, err := q.db.Exec(ctx, unlinkObservations, arg.AnonRef, arg.ContributorRef)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
