// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: photo_captures.sql

package community

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bindPhotoCapture = `-- name: BindPhotoCapture :execrows
UPDATE community_photo_captures SET evidence_session_id = $1, captured_at = $2
WHERE id = $3 AND contributor_ref = $4 AND key_id = $5
AND expires_at > $6
AND $2 >= issued_at AND $2 < camera_expires_at
AND (evidence_session_id IS NULL OR (evidence_session_id = $1 AND captured_at = $2))
`

type BindPhotoCaptureParams struct {
	SessionID      pgtype.UUID        `json:"session_id"`
	CapturedAt     pgtype.Timestamptz `json:"captured_at"`
	ID             pgtype.UUID        `json:"id"`
	ContributorRef string             `json:"contributor_ref"`
	KeyID          string             `json:"key_id"`
	NowAt          pgtype.Timestamptz `json:"now_at"`
}

func (q *Queries) BindPhotoCapture(ctx context.Context, arg BindPhotoCaptureParams) (int64, error) {
	result, err := q.db.Exec(ctx, bindPhotoCapture,
		arg.SessionID,
		arg.CapturedAt,
		arg.ID,
		arg.ContributorRef,
		arg.KeyID,
		arg.NowAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const erasePhotoCaptures = `-- name: ErasePhotoCaptures :execrows
DELETE FROM community_photo_captures WHERE contributor_ref = $1
`

func (q *Queries) ErasePhotoCaptures(ctx context.Context, contributorRef string) (int64, error) {
	result, err := q.db.Exec(ctx, erasePhotoCaptures, contributorRef)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertPhotoCapture = `-- name: InsertPhotoCapture :one
INSERT INTO community_photo_captures
(id, contributor_ref, key_id, client_capture_id, station_id, issued_at, camera_expires_at, expires_at, policy_version)
VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9)
ON CONFLICT (contributor_ref, client_capture_id) DO UPDATE SET client_capture_id = EXCLUDED.client_capture_id
WHERE community_photo_captures.key_id = EXCLUDED.key_id AND community_photo_captures.station_id = EXCLUDED.station_id
RETURNING id, contributor_ref, key_id, client_capture_id, station_id, issued_at, camera_expires_at, expires_at, policy_version, evidence_session_id, captured_at
`

type InsertPhotoCaptureParams struct {
	ID              pgtype.UUID        `json:"id"`
	ContributorRef  string             `json:"contributor_ref"`
	KeyID           string             `json:"key_id"`
	ClientCaptureID string             `json:"client_capture_id"`
	StationID       pgtype.UUID        `json:"station_id"`
	IssuedAt        pgtype.Timestamptz `json:"issued_at"`
	CameraExpiresAt pgtype.Timestamptz `json:"camera_expires_at"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	PolicyVersion   string             `json:"policy_version"`
}

func (q *Queries) InsertPhotoCapture(ctx context.Context, arg InsertPhotoCaptureParams) (CommunityPhotoCapture, error) {
	row := q.db.QueryRow(ctx, insertPhotoCapture,
		arg.ID,
		arg.ContributorRef,
		arg.KeyID,
		arg.ClientCaptureID,
		arg.StationID,
		arg.IssuedAt,
		arg.CameraExpiresAt,
		arg.ExpiresAt,
		arg.PolicyVersion,
	)
	var i CommunityPhotoCapture
	err := row.Scan(
		&i.ID,
		&i.ContributorRef,
		&i.KeyID,
		&i.ClientCaptureID,
		&i.StationID,
		&i.IssuedAt,
		&i.CameraExpiresAt,
		&i.ExpiresAt,
		&i.PolicyVersion,
		&i.EvidenceSessionID,
		&i.CapturedAt,
	)
	return i, err
}

const ownedPhotoCapture = `-- name: OwnedPhotoCapture :one
SELECT id, contributor_ref, key_id, client_capture_id, station_id, issued_at, camera_expires_at, expires_at, policy_version, evidence_session_id, captured_at FROM community_photo_captures WHERE id = $1 AND contributor_ref = $2
`

type OwnedPhotoCaptureParams struct {
	ID             pgtype.UUID `json:"id"`
	ContributorRef string      `json:"contributor_ref"`
}

func (q *Queries) OwnedPhotoCapture(ctx context.Context, arg OwnedPhotoCaptureParams) (CommunityPhotoCapture, error) {
	row := q.db.QueryRow(ctx, ownedPhotoCapture, arg.ID, arg.ContributorRef)
	var i CommunityPhotoCapture
	err := row.Scan(
		&i.ID,
		&i.ContributorRef,
		&i.KeyID,
		&i.ClientCaptureID,
		&i.StationID,
		&i.IssuedAt,
		&i.CameraExpiresAt,
		&i.ExpiresAt,
		&i.PolicyVersion,
		&i.EvidenceSessionID,
		&i.CapturedAt,
	)
	return i, err
}

const purgePhotoCaptures = `-- name: PurgePhotoCaptures :execrows
DELETE FROM community_photo_captures AS target WHERE target.id IN (
 SELECT receipt.id FROM community_photo_captures AS receipt WHERE receipt.expires_at <= $1
 ORDER BY receipt.expires_at, receipt.id LIMIT $2
)
`

type PurgePhotoCapturesParams struct {
	NowAt pgtype.Timestamptz `json:"now_at"`
	Batch int32              `json:"batch"`
}

func (q *Queries) PurgePhotoCaptures(ctx context.Context, arg PurgePhotoCapturesParams) (int64, error) {
	result, err := q.db.Exec(ctx, purgePhotoCaptures, arg.NowAt, arg.Batch)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
