// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projection.sql

package community

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const confirmationsForAnchors = `-- name: ConfirmationsForAnchors :many
SELECT c.id, c.observation_id, c.contributor_ref, c.client_submission_id,
    c.received_at, c.policy_version
FROM community_confirmations c
WHERE c.observation_id = ANY($1::uuid[])
ORDER BY c.received_at ASC, c.id ASC
`

func (q *Queries) ConfirmationsForAnchors(ctx context.Context, anchorIds []pgtype.UUID) ([]CommunityConfirmation, error) {
	rows, err := q.db.Query(ctx, confirmationsForAnchors, anchorIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CommunityConfirmation
	for rows.Next() {
		var i CommunityConfirmation
		if err := rows.Scan(
			&i.ID,
			&i.ObservationID,
			&i.ContributorRef,
			&i.ClientSubmissionID,
			&i.ReceivedAt,
			&i.PolicyVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const dueProjections = `-- name: DueProjections :many
SELECT station_id, fuel_product, unit, condition_kind, qualifier_key,
    next_recompute_at
FROM community_current_prices
WHERE next_recompute_at IS NOT NULL AND next_recompute_at <= $1
ORDER BY next_recompute_at ASC
LIMIT $2
`

type DueProjectionsParams struct {
	Now   pgtype.Timestamptz `json:"now"`
	Batch int32              `json:"batch"`
}

type DueProjectionsRow struct {
	StationID       pgtype.UUID        `json:"station_id"`
	FuelProduct     string             `json:"fuel_product"`
	Unit            string             `json:"unit"`
	ConditionKind   string             `json:"condition_kind"`
	QualifierKey    string             `json:"qualifier_key"`
	NextRecomputeAt pgtype.Timestamptz `json:"next_recompute_at"`
}

func (q *Queries) DueProjections(ctx context.Context, arg DueProjectionsParams) ([]DueProjectionsRow, error) {
	rows, err := q.db.Query(ctx, dueProjections, arg.Now, arg.Batch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DueProjectionsRow
	for rows.Next() {
		var i DueProjectionsRow
		if err := rows.Scan(
			&i.StationID,
			&i.FuelProduct,
			&i.Unit,
			&i.ConditionKind,
			&i.QualifierKey,
			&i.NextRecomputeAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const eligibleAnchors = `-- name: EligibleAnchors :many
SELECT o.id, o.contributor_ref, o.client_submission_id, o.station_id,
    o.fuel_product, o.unit, o.amount_milli_brl, o.raw_price_text,
    o.condition_kind, o.qualifier_key, o.evidence_id, o.received_at,
    o.claimed_captured_at, o.supersedes_id, o.policy_version
FROM community_observations o
WHERE o.station_id = $1
    AND o.fuel_product = $2
    AND o.unit = $3
    AND o.condition_kind = $4
    AND o.qualifier_key = $5
    AND o.received_at >= $6
    AND (SELECT d.to_state FROM community_observation_decisions d
         WHERE d.observation_id = o.id
         ORDER BY d.sequence DESC LIMIT 1) = 'VALIDATED'
ORDER BY o.received_at ASC, o.id ASC
`

type EligibleAnchorsParams struct {
	StationID     pgtype.UUID        `json:"station_id"`
	FuelProduct   string             `json:"fuel_product"`
	Unit          string             `json:"unit"`
	ConditionKind string             `json:"condition_kind"`
	QualifierKey  string             `json:"qualifier_key"`
	Cutoff        pgtype.Timestamptz `json:"cutoff"`
}

type EligibleAnchorsRow struct {
	ID                 pgtype.UUID        `json:"id"`
	ContributorRef     string             `json:"contributor_ref"`
	ClientSubmissionID string             `json:"client_submission_id"`
	StationID          pgtype.UUID        `json:"station_id"`
	FuelProduct        string             `json:"fuel_product"`
	Unit               string             `json:"unit"`
	AmountMilliBrl     int64              `json:"amount_milli_brl"`
	RawPriceText       string             `json:"raw_price_text"`
	ConditionKind      string             `json:"condition_kind"`
	QualifierKey       string             `json:"qualifier_key"`
	EvidenceID         pgtype.UUID        `json:"evidence_id"`
	ReceivedAt         pgtype.Timestamptz `json:"received_at"`
	ClaimedCapturedAt  pgtype.Timestamptz `json:"claimed_captured_at"`
	SupersedesID       pgtype.UUID        `json:"supersedes_id"`
	PolicyVersion      string             `json:"policy_version"`
}

func (q *Queries) EligibleAnchors(ctx context.Context, arg EligibleAnchorsParams) ([]EligibleAnchorsRow, error) {
	rows, err := q.db.Query(ctx, eligibleAnchors,
		arg.StationID,
		arg.FuelProduct,
		arg.Unit,
		arg.ConditionKind,
		arg.QualifierKey,
		arg.Cutoff,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EligibleAnchorsRow
	for rows.Next() {
		var i EligibleAnchorsRow
		if err := rows.Scan(
			&i.ID,
			&i.ContributorRef,
			&i.ClientSubmissionID,
			&i.StationID,
			&i.FuelProduct,
			&i.Unit,
			&i.AmountMilliBrl,
			&i.RawPriceText,
			&i.ConditionKind,
			&i.QualifierKey,
			&i.EvidenceID,
			&i.ReceivedAt,
			&i.ClaimedCapturedAt,
			&i.SupersedesID,
			&i.PolicyVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProjection = `-- name: GetProjection :one
SELECT station_id, fuel_product, unit, condition_kind, qualifier_key,
    amount_milli_brl, availability, confidence,
    representative_observation_id, independent_supporters,
    confirmation_count, anchor_received_at, expires_at,
    next_recompute_at, computed_at, projection_version,
    algorithm_version, policy_config_version
FROM community_current_prices
WHERE station_id = $1
    AND fuel_product = $2
    AND unit = $3
    AND condition_kind = $4
    AND qualifier_key = $5
`

type GetProjectionParams struct {
	StationID     pgtype.UUID `json:"station_id"`
	FuelProduct   string      `json:"fuel_product"`
	Unit          string      `json:"unit"`
	ConditionKind string      `json:"condition_kind"`
	QualifierKey  string      `json:"qualifier_key"`
}

func (q *Queries) GetProjection(ctx context.Context, arg GetProjectionParams) (CommunityCurrentPrice, error) {
	row := q.db.QueryRow(ctx, getProjection,
		arg.StationID,
		arg.FuelProduct,
		arg.Unit,
		arg.ConditionKind,
		arg.QualifierKey,
	)
	var i CommunityCurrentPrice
	err := row.Scan(
		&i.StationID,
		&i.FuelProduct,
		&i.Unit,
		&i.ConditionKind,
		&i.QualifierKey,
		&i.AmountMilliBrl,
		&i.Availability,
		&i.Confidence,
		&i.RepresentativeObservationID,
		&i.IndependentSupporters,
		&i.ConfirmationCount,
		&i.AnchorReceivedAt,
		&i.ExpiresAt,
		&i.NextRecomputeAt,
		&i.ComputedAt,
		&i.ProjectionVersion,
		&i.AlgorithmVersion,
		&i.PolicyConfigVersion,
	)
	return i, err
}

const lockPriceKey = `-- name: LockPriceKey :exec

SELECT pg_advisory_xact_lock(hashtext($1))
`

// Owned by community. Projection writes serialize on a transactional
// advisory lock per price key before loading votes: a stale worker can
// never overwrite a fresher projection, and versions only move forward
// under the lock. Reads hit the indexed current row, never history.
func (q *Queries) LockPriceKey(ctx context.Context, key string) error {
	_, err := q.db.Exec(ctx, lockPriceKey, key)
	return err
}

const upsertProjection = `-- name: UpsertProjection :execrows
INSERT INTO community_current_prices AS p
    (station_id, fuel_product, unit, condition_kind, qualifier_key,
     amount_milli_brl, availability, confidence,
     representative_observation_id, independent_supporters,
     confirmation_count, anchor_received_at, expires_at,
     next_recompute_at, computed_at, projection_version,
     algorithm_version, policy_config_version)
VALUES ($1, $2, $3, $4,
    $5, $6, $7, $8,
    $9, $10,
    $11, $12, $13,
    $14, $15, $16,
    $17, $18)
ON CONFLICT (station_id, fuel_product, unit, condition_kind,
    qualifier_key) DO UPDATE SET
    amount_milli_brl = EXCLUDED.amount_milli_brl,
    availability = EXCLUDED.availability,
    confidence = EXCLUDED.confidence,
    representative_observation_id = EXCLUDED.representative_observation_id,
    independent_supporters = EXCLUDED.independent_supporters,
    confirmation_count = EXCLUDED.confirmation_count,
    anchor_received_at = EXCLUDED.anchor_received_at,
    expires_at = EXCLUDED.expires_at,
    next_recompute_at = EXCLUDED.next_recompute_at,
    computed_at = EXCLUDED.computed_at,
    projection_version = EXCLUDED.projection_version,
    algorithm_version = EXCLUDED.algorithm_version,
    policy_config_version = EXCLUDED.policy_config_version
WHERE p.projection_version < EXCLUDED.projection_version
`

type UpsertProjectionParams struct {
	StationID                   pgtype.UUID        `json:"station_id"`
	FuelProduct                 string             `json:"fuel_product"`
	Unit                        string             `json:"unit"`
	ConditionKind               string             `json:"condition_kind"`
	QualifierKey                string             `json:"qualifier_key"`
	AmountMilliBrl              pgtype.Int8        `json:"amount_milli_brl"`
	Availability                string             `json:"availability"`
	Confidence                  string             `json:"confidence"`
	RepresentativeObservationID pgtype.UUID        `json:"representative_observation_id"`
	IndependentSupporters       int32              `json:"independent_supporters"`
	ConfirmationCount           int32              `json:"confirmation_count"`
	AnchorReceivedAt            pgtype.Timestamptz `json:"anchor_received_at"`
	ExpiresAt                   pgtype.Timestamptz `json:"expires_at"`
	NextRecomputeAt             pgtype.Timestamptz `json:"next_recompute_at"`
	ComputedAt                  pgtype.Timestamptz `json:"computed_at"`
	ProjectionVersion           int64              `json:"projection_version"`
	AlgorithmVersion            string             `json:"algorithm_version"`
	PolicyConfigVersion         string             `json:"policy_config_version"`
}

func (q *Queries) UpsertProjection(ctx context.Context, arg UpsertProjectionParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertProjection,
		arg.StationID,
		arg.FuelProduct,
		arg.Unit,
		arg.ConditionKind,
		arg.QualifierKey,
		arg.AmountMilliBrl,
		arg.Availability,
		arg.Confidence,
		arg.RepresentativeObservationID,
		arg.IndependentSupporters,
		arg.ConfirmationCount,
		arg.AnchorReceivedAt,
		arg.ExpiresAt,
		arg.NextRecomputeAt,
		arg.ComputedAt,
		arg.ProjectionVersion,
		arg.AlgorithmVersion,
		arg.PolicyConfigVersion,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertProjectionInputs = `-- name: UpsertProjectionInputs :execrows
INSERT INTO community_projection_inputs AS i
    (projection_key, version, input_cutoff, supporting_event_ids,
     reason_codes, computed_at)
VALUES ($1, $2, $3, $4,
    $5, $6)
ON CONFLICT (projection_key) DO UPDATE SET
    version = EXCLUDED.version,
    input_cutoff = EXCLUDED.input_cutoff,
    supporting_event_ids = EXCLUDED.supporting_event_ids,
    reason_codes = EXCLUDED.reason_codes,
    computed_at = EXCLUDED.computed_at
WHERE i.version < EXCLUDED.version
`

type UpsertProjectionInputsParams struct {
	ProjectionKey      string             `json:"projection_key"`
	Version            int64              `json:"version"`
	InputCutoff        pgtype.Timestamptz `json:"input_cutoff"`
	SupportingEventIds []string           `json:"supporting_event_ids"`
	ReasonCodes        []string           `json:"reason_codes"`
	ComputedAt         pgtype.Timestamptz `json:"computed_at"`
}

func (q *Queries) UpsertProjectionInputs(ctx context.Context, arg UpsertProjectionInputsParams) (int64, error) {
	result, err := q.db.Exec(ctx, upsertProjectionInputs,
		arg.ProjectionKey,
		arg.Version,
		arg.InputCutoff,
		arg.SupportingEventIds,
		arg.ReasonCodes,
		arg.ComputedAt,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
