// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: signals.sql

package community

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getSignals = `-- name: GetSignals :one
SELECT observation_id, proximity_band, recency_band, capture_flag,
    photo_signal, duplicate_count, regional_band, risk_codes,
    needs_review, policy_version, computed_at
FROM community_observation_signals
WHERE observation_id = $1
`

func (q *Queries) GetSignals(ctx context.Context, observationID pgtype.UUID) (CommunityObservationSignal, error) {
	row := q.db.QueryRow(ctx, getSignals, observationID)
	var i CommunityObservationSignal
	err := row.Scan(
		&i.ObservationID,
		&i.ProximityBand,
		&i.RecencyBand,
		&i.CaptureFlag,
		&i.PhotoSignal,
		&i.DuplicateCount,
		&i.RegionalBand,
		&i.RiskCodes,
		&i.NeedsReview,
		&i.PolicyVersion,
		&i.ComputedAt,
	)
	return i, err
}

const upsertSignals = `-- name: UpsertSignals :one

INSERT INTO community_observation_signals
    (observation_id, proximity_band, recency_band, capture_flag,
     photo_signal, duplicate_count, regional_band, risk_codes,
     needs_review, policy_version, computed_at)
VALUES ($1, $2, $3, $4,
    $5, $6, $7, $8,
    $9, $10, $11)
ON CONFLICT (observation_id) DO UPDATE SET
    proximity_band = EXCLUDED.proximity_band,
    recency_band = EXCLUDED.recency_band,
    capture_flag = EXCLUDED.capture_flag,
    photo_signal = EXCLUDED.photo_signal,
    duplicate_count = EXCLUDED.duplicate_count,
    regional_band = EXCLUDED.regional_band,
    risk_codes = EXCLUDED.risk_codes,
    needs_review = EXCLUDED.needs_review,
    policy_version = EXCLUDED.policy_version,
    computed_at = EXCLUDED.computed_at
RETURNING observation_id
`

type UpsertSignalsParams struct {
	ObservationID  pgtype.UUID        `json:"observation_id"`
	ProximityBand  string             `json:"proximity_band"`
	RecencyBand    string             `json:"recency_band"`
	CaptureFlag    string             `json:"capture_flag"`
	PhotoSignal    string             `json:"photo_signal"`
	DuplicateCount int32              `json:"duplicate_count"`
	RegionalBand   string             `json:"regional_band"`
	RiskCodes      []string           `json:"risk_codes"`
	NeedsReview    bool               `json:"needs_review"`
	PolicyVersion  string             `json:"policy_version"`
	ComputedAt     pgtype.Timestamptz `json:"computed_at"`
}

// Owned by community. Derived signal projection: bands and reason codes
// only, never coordinates or meter-level claims (see the privacy
// column test). Recomputable: upserts converge by observation.
func (q *Queries) UpsertSignals(ctx context.Context, arg UpsertSignalsParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, upsertSignals,
		arg.ObservationID,
		arg.ProximityBand,
		arg.RecencyBand,
		arg.CaptureFlag,
		arg.PhotoSignal,
		arg.DuplicateCount,
		arg.RegionalBand,
		arg.RiskCodes,
		arg.NeedsReview,
		arg.PolicyVersion,
		arg.ComputedAt,
	)
	var observation_id pgtype.UUID
	err := row.Scan(&observation_id)
	return observation_id, err
}
