// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: votes.sql

package community

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getConfirmationByNaturalKey = `-- name: GetConfirmationByNaturalKey :one
SELECT id, observation_id, contributor_ref, client_submission_id,
    received_at, policy_version
FROM community_confirmations
WHERE contributor_ref = $1 AND client_submission_id = $2
`

type GetConfirmationByNaturalKeyParams struct {
	ContributorRef     string `json:"contributor_ref"`
	ClientSubmissionID string `json:"client_submission_id"`
}

func (q *Queries) GetConfirmationByNaturalKey(ctx context.Context, arg GetConfirmationByNaturalKeyParams) (CommunityConfirmation, error) {
	row := q.db.QueryRow(ctx, getConfirmationByNaturalKey, arg.ContributorRef, arg.ClientSubmissionID)
	var i CommunityConfirmation
	err := row.Scan(
		&i.ID,
		&i.ObservationID,
		&i.ContributorRef,
		&i.ClientSubmissionID,
		&i.ReceivedAt,
		&i.PolicyVersion,
	)
	return i, err
}

const getDisputeByNaturalKey = `-- name: GetDisputeByNaturalKey :one
SELECT id, target_observation_id, contributor_ref, client_submission_id,
    reason, detail, replacement_id, status, received_at, policy_version
FROM community_disputes
WHERE contributor_ref = $1 AND client_submission_id = $2
`

type GetDisputeByNaturalKeyParams struct {
	ContributorRef     string `json:"contributor_ref"`
	ClientSubmissionID string `json:"client_submission_id"`
}

func (q *Queries) GetDisputeByNaturalKey(ctx context.Context, arg GetDisputeByNaturalKeyParams) (CommunityDispute, error) {
	row := q.db.QueryRow(ctx, getDisputeByNaturalKey, arg.ContributorRef, arg.ClientSubmissionID)
	var i CommunityDispute
	err := row.Scan(
		&i.ID,
		&i.TargetObservationID,
		&i.ContributorRef,
		&i.ClientSubmissionID,
		&i.Reason,
		&i.Detail,
		&i.ReplacementID,
		&i.Status,
		&i.ReceivedAt,
		&i.PolicyVersion,
	)
	return i, err
}

const getOpenDispute = `-- name: GetOpenDispute :one
SELECT id, target_observation_id, contributor_ref, client_submission_id,
    reason, detail, replacement_id, status, received_at, policy_version
FROM community_disputes
WHERE contributor_ref = $1
    AND target_observation_id = $2
    AND reason = $3 AND status = 'OPEN'
`

type GetOpenDisputeParams struct {
	ContributorRef      string      `json:"contributor_ref"`
	TargetObservationID pgtype.UUID `json:"target_observation_id"`
	Reason              string      `json:"reason"`
}

func (q *Queries) GetOpenDispute(ctx context.Context, arg GetOpenDisputeParams) (CommunityDispute, error) {
	row := q.db.QueryRow(ctx, getOpenDispute, arg.ContributorRef, arg.TargetObservationID, arg.Reason)
	var i CommunityDispute
	err := row.Scan(
		&i.ID,
		&i.TargetObservationID,
		&i.ContributorRef,
		&i.ClientSubmissionID,
		&i.Reason,
		&i.Detail,
		&i.ReplacementID,
		&i.Status,
		&i.ReceivedAt,
		&i.PolicyVersion,
	)
	return i, err
}

const insertConfirmation = `-- name: InsertConfirmation :one

INSERT INTO community_confirmations
    (id, observation_id, contributor_ref, client_submission_id,
     received_at, policy_version)
VALUES ($1, $2, $3, $4,
    $5, $6)
ON CONFLICT (contributor_ref, client_submission_id) DO NOTHING
RETURNING id
`

type InsertConfirmationParams struct {
	ID                 pgtype.UUID        `json:"id"`
	ObservationID      pgtype.UUID        `json:"observation_id"`
	ContributorRef     string             `json:"contributor_ref"`
	ClientSubmissionID string             `json:"client_submission_id"`
	ReceivedAt         pgtype.Timestamptz `json:"received_at"`
	PolicyVersion      string             `json:"policy_version"`
}

// Owned by community. Votes and reports are insert-only: retries
// converge on natural keys, duplicate support conflicts on the
// observation+contributor pair, and active repeated reports converge on
// the open triple. Resolution history lands with moderation (P07); no
// UPDATE or DELETE path exists in this file.
func (q *Queries) InsertConfirmation(ctx context.Context, arg InsertConfirmationParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertConfirmation,
		arg.ID,
		arg.ObservationID,
		arg.ContributorRef,
		arg.ClientSubmissionID,
		arg.ReceivedAt,
		arg.PolicyVersion,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const insertDispute = `-- name: InsertDispute :one
INSERT INTO community_disputes
    (id, target_observation_id, contributor_ref, client_submission_id,
     reason, detail, replacement_id, status, received_at, policy_version)
VALUES ($1, $2, $3,
    $4, $5, $6, $7, $8,
    $9, $10)
ON CONFLICT (contributor_ref, client_submission_id) DO NOTHING
RETURNING id
`

type InsertDisputeParams struct {
	ID                  pgtype.UUID        `json:"id"`
	TargetObservationID pgtype.UUID        `json:"target_observation_id"`
	ContributorRef      string             `json:"contributor_ref"`
	ClientSubmissionID  string             `json:"client_submission_id"`
	Reason              string             `json:"reason"`
	Detail              string             `json:"detail"`
	ReplacementID       pgtype.UUID        `json:"replacement_id"`
	Status              string             `json:"status"`
	ReceivedAt          pgtype.Timestamptz `json:"received_at"`
	PolicyVersion       string             `json:"policy_version"`
}

func (q *Queries) InsertDispute(ctx context.Context, arg InsertDisputeParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertDispute,
		arg.ID,
		arg.TargetObservationID,
		arg.ContributorRef,
		arg.ClientSubmissionID,
		arg.Reason,
		arg.Detail,
		arg.ReplacementID,
		arg.Status,
		arg.ReceivedAt,
		arg.PolicyVersion,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
