// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package trust

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type TrustCurrent struct {
	ContributorRef string             `json:"contributor_ref"`
	Tier           string             `json:"tier"`
	Version        int64              `json:"version"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

type TrustDecision struct {
	ID             pgtype.UUID        `json:"id"`
	ContributorRef string             `json:"contributor_ref"`
	Tier           string             `json:"tier"`
	Reason         string             `json:"reason"`
	CaseRefs       []string           `json:"case_refs"`
	PolicyVersion  string             `json:"policy_version"`
	OccurredAt     pgtype.Timestamptz `json:"occurred_at"`
}
