// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: trust.sql

package trust

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteTrustCurrent = `-- name: DeleteTrustCurrent :execrows

DELETE FROM trust_current
WHERE contributor_ref = $1
`

// Erasure (P07-T04, B-BR-016): drop the rebuildable current view so the
// erased owner reads as NEW, and unlink decision history to an opaque
// token (reviewed-outcome counts survive, identity links do not). Only
// these queries may remove trust rows; verdict recording stays
// append-only.
func (q *Queries) DeleteTrustCurrent(ctx context.Context, contributorRef string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteTrustCurrent, contributorRef)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getCurrent = `-- name: GetCurrent :one
SELECT contributor_ref, tier, version, updated_at
FROM trust_current
WHERE contributor_ref = $1
`

func (q *Queries) GetCurrent(ctx context.Context, contributorRef string) (TrustCurrent, error) {
	row := q.db.QueryRow(ctx, getCurrent, contributorRef)
	var i TrustCurrent
	err := row.Scan(
		&i.ContributorRef,
		&i.Tier,
		&i.Version,
		&i.UpdatedAt,
	)
	return i, err
}

const insertDecision = `-- name: InsertDecision :one

INSERT INTO trust_decisions
    (id, contributor_ref, tier, reason, case_refs, policy_version,
     occurred_at)
VALUES ($1, $2, $3, $4, $5,
    $6, $7)
RETURNING id
`

type InsertDecisionParams struct {
	ID             pgtype.UUID        `json:"id"`
	ContributorRef string             `json:"contributor_ref"`
	Tier           string             `json:"tier"`
	Reason         string             `json:"reason"`
	CaseRefs       []string           `json:"case_refs"`
	PolicyVersion  string             `json:"policy_version"`
	OccurredAt     pgtype.Timestamptz `json:"occurred_at"`
}

// Owned by trust. Decisions are insert-only; the current view
// upserts to the latest verdict in the same transaction. No UPDATE or
// DELETE path exists in this file: blocks, reversals and
// rehabilitations all arrive as new decision rows.
func (q *Queries) InsertDecision(ctx context.Context, arg InsertDecisionParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertDecision,
		arg.ID,
		arg.ContributorRef,
		arg.Tier,
		arg.Reason,
		arg.CaseRefs,
		arg.PolicyVersion,
		arg.OccurredAt,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const listDecisions = `-- name: ListDecisions :many
SELECT id, contributor_ref, tier, reason, case_refs, policy_version,
    occurred_at
FROM trust_decisions
WHERE contributor_ref = $1
ORDER BY occurred_at ASC, id ASC
`

func (q *Queries) ListDecisions(ctx context.Context, contributorRef string) ([]TrustDecision, error) {
	rows, err := q.db.Query(ctx, listDecisions, contributorRef)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TrustDecision
	for rows.Next() {
		var i TrustDecision
		if err := rows.Scan(
			&i.ID,
			&i.ContributorRef,
			&i.Tier,
			&i.Reason,
			&i.CaseRefs,
			&i.PolicyVersion,
			&i.OccurredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unlinkTrustDecisions = `-- name: UnlinkTrustDecisions :execrows
UPDATE trust_decisions
SET contributor_ref = $1
WHERE contributor_ref = $2
`

type UnlinkTrustDecisionsParams struct {
	AnonRef        string `json:"anon_ref"`
	ContributorRef string `json:"contributor_ref"`
}

func (q *Queries) UnlinkTrustDecisions(ctx context.Context, arg UnlinkTrustDecisionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, unlinkTrustDecisions, arg.AnonRef, arg.ContributorRef)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertCurrent = `-- name: UpsertCurrent :one
INSERT INTO trust_current (contributor_ref, tier, version, updated_at)
VALUES ($1, $2, 1, $3)
ON CONFLICT (contributor_ref) DO UPDATE SET
    tier = EXCLUDED.tier,
    version = trust_current.version + 1,
    updated_at = EXCLUDED.updated_at
RETURNING contributor_ref
`

type UpsertCurrentParams struct {
	ContributorRef string             `json:"contributor_ref"`
	Tier           string             `json:"tier"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) UpsertCurrent(ctx context.Context, arg UpsertCurrentParams) (string, error) {
	row := q.db.QueryRow(ctx, upsertCurrent, arg.ContributorRef, arg.Tier, arg.UpdatedAt)
	var contributor_ref string
	err := row.Scan(&contributor_ref)
	return contributor_ref, err
}
