// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: evidence.sql

package evidence

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimObjectBinding = `-- name: ClaimObjectBinding :execrows
UPDATE evidence_objects
SET bound_observation_id = $1
WHERE id = $2 AND (bound_observation_id IS NULL OR bound_observation_id = $1)
`

type ClaimObjectBindingParams struct {
	ObservationID pgtype.UUID `json:"observation_id"`
	ID            pgtype.UUID `json:"id"`
}

func (q *Queries) ClaimObjectBinding(ctx context.Context, arg ClaimObjectBindingParams) (int64, error) {
	result, err := q.db.Exec(ctx, claimObjectBinding, arg.ObservationID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const claimVerifying = `-- name: ClaimVerifying :execrows
UPDATE evidence_sessions
SET status = 'VERIFYING', updated_at = now()
WHERE id = $1 AND status = 'ISSUED'
`

func (q *Queries) ClaimVerifying(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, claimVerifying, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countSessionsSince = `-- name: CountSessionsSince :one
SELECT count(*) FROM evidence_sessions
WHERE contributor_ref = $1 AND created_at >= $2
`

type CountSessionsSinceParams struct {
	ContributorRef string             `json:"contributor_ref"`
	Since          pgtype.Timestamptz `json:"since"`
}

func (q *Queries) CountSessionsSince(ctx context.Context, arg CountSessionsSinceParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSessionsSince, arg.ContributorRef, arg.Since)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const expireIdleSessions = `-- name: ExpireIdleSessions :many

UPDATE evidence_sessions AS s
SET status = 'EXPIRED', updated_at = now()
WHERE s.id IN (
    SELECT inner_s.id FROM evidence_sessions AS inner_s
    WHERE inner_s.status = 'ISSUED' AND inner_s.expires_at <= $1
    ORDER BY inner_s.expires_at ASC
    LIMIT $2
)
RETURNING s.id, s.quarantine_key
`

type ExpireIdleSessionsParams struct {
	Now   pgtype.Timestamptz `json:"now"`
	Batch int32              `json:"batch"`
}

type ExpireIdleSessionsRow struct {
	ID            pgtype.UUID `json:"id"`
	QuarantineKey string      `json:"quarantine_key"`
}

// Sweep inventory (P05-T05). State transitions stay conditional; every
// deletion marker is set-if-unset so repeated runs converge. Postgres
// UPDATE takes no LIMIT, so batched transitions select their keys in a
// subquery instead.
func (q *Queries) ExpireIdleSessions(ctx context.Context, arg ExpireIdleSessionsParams) ([]ExpireIdleSessionsRow, error) {
	rows, err := q.db.Query(ctx, expireIdleSessions, arg.Now, arg.Batch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExpireIdleSessionsRow
	for rows.Next() {
		var i ExpireIdleSessionsRow
		if err := rows.Scan(&i.ID, &i.QuarantineKey); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const expireStuckSession = `-- name: ExpireStuckSession :execrows
UPDATE evidence_sessions
SET status = 'EXPIRED', updated_at = now()
WHERE id = $1 AND status = 'VERIFYING' AND created_at <= $2
`

type ExpireStuckSessionParams struct {
	ID     pgtype.UUID        `json:"id"`
	Cutoff pgtype.Timestamptz `json:"cutoff"`
}

func (q *Queries) ExpireStuckSession(ctx context.Context, arg ExpireStuckSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, expireStuckSession, arg.ID, arg.Cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findByDHash = `-- name: FindByDHash :many
SELECT id, session_id, final_key, dhash, created_at
FROM evidence_objects
WHERE dhash = $1 AND created_at >= $2
ORDER BY created_at ASC
`

type FindByDHashParams struct {
	Dhash int64              `json:"dhash"`
	Since pgtype.Timestamptz `json:"since"`
}

type FindByDHashRow struct {
	ID        pgtype.UUID        `json:"id"`
	SessionID pgtype.UUID        `json:"session_id"`
	FinalKey  string             `json:"final_key"`
	Dhash     int64              `json:"dhash"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) FindByDHash(ctx context.Context, arg FindByDHashParams) ([]FindByDHashRow, error) {
	rows, err := q.db.Query(ctx, findByDHash, arg.Dhash, arg.Since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindByDHashRow
	for rows.Next() {
		var i FindByDHashRow
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.FinalKey,
			&i.Dhash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getObject = `-- name: GetObject :one
SELECT o.id, o.session_id, o.final_key, o.source_sha256,
    o.sanitized_sha256, o.width, o.height, o.dhash,
    o.bound_observation_id, o.created_at, o.final_deleted_at,
    s.contributor_ref, s.status
FROM evidence_objects o
JOIN evidence_sessions s ON s.id = o.session_id
WHERE o.id = $1
`

type GetObjectRow struct {
	ID                 pgtype.UUID        `json:"id"`
	SessionID          pgtype.UUID        `json:"session_id"`
	FinalKey           string             `json:"final_key"`
	SourceSha256       string             `json:"source_sha256"`
	SanitizedSha256    string             `json:"sanitized_sha256"`
	Width              int32              `json:"width"`
	Height             int32              `json:"height"`
	Dhash              int64              `json:"dhash"`
	BoundObservationID pgtype.UUID        `json:"bound_observation_id"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	FinalDeletedAt     pgtype.Timestamptz `json:"final_deleted_at"`
	ContributorRef     string             `json:"contributor_ref"`
	Status             string             `json:"status"`
}

func (q *Queries) GetObject(ctx context.Context, id pgtype.UUID) (GetObjectRow, error) {
	row := q.db.QueryRow(ctx, getObject, id)
	var i GetObjectRow
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.FinalKey,
		&i.SourceSha256,
		&i.SanitizedSha256,
		&i.Width,
		&i.Height,
		&i.Dhash,
		&i.BoundObservationID,
		&i.CreatedAt,
		&i.FinalDeletedAt,
		&i.ContributorRef,
		&i.Status,
	)
	return i, err
}

const getObjectBySession = `-- name: GetObjectBySession :one
SELECT o.id, o.session_id, o.final_key, o.source_sha256,
    o.sanitized_sha256, o.width, o.height, o.dhash,
    o.bound_observation_id, o.created_at, o.final_deleted_at,
    s.contributor_ref, s.status
FROM evidence_objects o
JOIN evidence_sessions s ON s.id = o.session_id
WHERE o.session_id = $1
`

type GetObjectBySessionRow struct {
	ID                 pgtype.UUID        `json:"id"`
	SessionID          pgtype.UUID        `json:"session_id"`
	FinalKey           string             `json:"final_key"`
	SourceSha256       string             `json:"source_sha256"`
	SanitizedSha256    string             `json:"sanitized_sha256"`
	Width              int32              `json:"width"`
	Height             int32              `json:"height"`
	Dhash              int64              `json:"dhash"`
	BoundObservationID pgtype.UUID        `json:"bound_observation_id"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	FinalDeletedAt     pgtype.Timestamptz `json:"final_deleted_at"`
	ContributorRef     string             `json:"contributor_ref"`
	Status             string             `json:"status"`
}

func (q *Queries) GetObjectBySession(ctx context.Context, sessionID pgtype.UUID) (GetObjectBySessionRow, error) {
	row := q.db.QueryRow(ctx, getObjectBySession, sessionID)
	var i GetObjectBySessionRow
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.FinalKey,
		&i.SourceSha256,
		&i.SanitizedSha256,
		&i.Width,
		&i.Height,
		&i.Dhash,
		&i.BoundObservationID,
		&i.CreatedAt,
		&i.FinalDeletedAt,
		&i.ContributorRef,
		&i.Status,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
SELECT id, contributor_ref, client_session_id, mime, declared_bytes,
    claimed_sha256, quarantine_key, status, status_reason, created_at,
    expires_at, updated_at, policy_version
FROM evidence_sessions
WHERE id = $1
`

type GetSessionRow struct {
	ID              pgtype.UUID        `json:"id"`
	ContributorRef  string             `json:"contributor_ref"`
	ClientSessionID string             `json:"client_session_id"`
	Mime            string             `json:"mime"`
	DeclaredBytes   int64              `json:"declared_bytes"`
	ClaimedSha256   string             `json:"claimed_sha256"`
	QuarantineKey   string             `json:"quarantine_key"`
	Status          string             `json:"status"`
	StatusReason    []string           `json:"status_reason"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	PolicyVersion   string             `json:"policy_version"`
}

func (q *Queries) GetSession(ctx context.Context, id pgtype.UUID) (GetSessionRow, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i GetSessionRow
	err := row.Scan(
		&i.ID,
		&i.ContributorRef,
		&i.ClientSessionID,
		&i.Mime,
		&i.DeclaredBytes,
		&i.ClaimedSha256,
		&i.QuarantineKey,
		&i.Status,
		&i.StatusReason,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UpdatedAt,
		&i.PolicyVersion,
	)
	return i, err
}

const getSessionByNaturalKey = `-- name: GetSessionByNaturalKey :one
SELECT id, contributor_ref, client_session_id, mime, declared_bytes,
    claimed_sha256, quarantine_key, status, status_reason, created_at,
    expires_at, updated_at, policy_version
FROM evidence_sessions
WHERE contributor_ref = $1 AND client_session_id = $2
`

type GetSessionByNaturalKeyParams struct {
	ContributorRef  string `json:"contributor_ref"`
	ClientSessionID string `json:"client_session_id"`
}

type GetSessionByNaturalKeyRow struct {
	ID              pgtype.UUID        `json:"id"`
	ContributorRef  string             `json:"contributor_ref"`
	ClientSessionID string             `json:"client_session_id"`
	Mime            string             `json:"mime"`
	DeclaredBytes   int64              `json:"declared_bytes"`
	ClaimedSha256   string             `json:"claimed_sha256"`
	QuarantineKey   string             `json:"quarantine_key"`
	Status          string             `json:"status"`
	StatusReason    []string           `json:"status_reason"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	PolicyVersion   string             `json:"policy_version"`
}

func (q *Queries) GetSessionByNaturalKey(ctx context.Context, arg GetSessionByNaturalKeyParams) (GetSessionByNaturalKeyRow, error) {
	row := q.db.QueryRow(ctx, getSessionByNaturalKey, arg.ContributorRef, arg.ClientSessionID)
	var i GetSessionByNaturalKeyRow
	err := row.Scan(
		&i.ID,
		&i.ContributorRef,
		&i.ClientSessionID,
		&i.Mime,
		&i.DeclaredBytes,
		&i.ClaimedSha256,
		&i.QuarantineKey,
		&i.Status,
		&i.StatusReason,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.UpdatedAt,
		&i.PolicyVersion,
	)
	return i, err
}

const insertObject = `-- name: InsertObject :one
INSERT INTO evidence_objects
    (id, session_id, final_key, source_sha256, sanitized_sha256,
     width, height, dhash, created_at)
VALUES ($1, $2, $3, $4, $5,
    $6, $7, $8, $9)
RETURNING id
`

type InsertObjectParams struct {
	ID              pgtype.UUID        `json:"id"`
	SessionID       pgtype.UUID        `json:"session_id"`
	FinalKey        string             `json:"final_key"`
	SourceSha256    string             `json:"source_sha256"`
	SanitizedSha256 string             `json:"sanitized_sha256"`
	Width           int32              `json:"width"`
	Height          int32              `json:"height"`
	Dhash           int64              `json:"dhash"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertObject(ctx context.Context, arg InsertObjectParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertObject,
		arg.ID,
		arg.SessionID,
		arg.FinalKey,
		arg.SourceSha256,
		arg.SanitizedSha256,
		arg.Width,
		arg.Height,
		arg.Dhash,
		arg.CreatedAt,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const insertSession = `-- name: InsertSession :one

INSERT INTO evidence_sessions
    (id, contributor_ref, client_session_id, mime, declared_bytes,
     claimed_sha256, quarantine_key, status, created_at, expires_at,
     policy_version)
VALUES ($1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10,
    $11)
ON CONFLICT (contributor_ref, client_session_id) DO NOTHING
RETURNING id
`

type InsertSessionParams struct {
	ID              pgtype.UUID        `json:"id"`
	ContributorRef  string             `json:"contributor_ref"`
	ClientSessionID string             `json:"client_session_id"`
	Mime            string             `json:"mime"`
	DeclaredBytes   int64              `json:"declared_bytes"`
	ClaimedSha256   string             `json:"claimed_sha256"`
	QuarantineKey   string             `json:"quarantine_key"`
	Status          string             `json:"status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	ExpiresAt       pgtype.Timestamptz `json:"expires_at"`
	PolicyVersion   string             `json:"policy_version"`
}

// Owned by evidence. Sessions mutate only through guarded conditional
// updates on the expected state (callers reload and converge on zero
// matched rows); objects are insert-only, and binding claims exactly one
// observation with set-if-unbound-or-same semantics. No UPDATE or DELETE
// against evidence_objects except the single-column bind claim, and no
// DELETE anywhere in this file.
func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertSession,
		arg.ID,
		arg.ContributorRef,
		arg.ClientSessionID,
		arg.Mime,
		arg.DeclaredBytes,
		arg.ClaimedSha256,
		arg.QuarantineKey,
		arg.Status,
		arg.CreatedAt,
		arg.ExpiresAt,
		arg.PolicyVersion,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const listStuckVerifying = `-- name: ListStuckVerifying :many
SELECT id, quarantine_key, created_at FROM evidence_sessions
WHERE status = 'VERIFYING' AND created_at <= $1
ORDER BY created_at ASC
LIMIT $2
`

type ListStuckVerifyingParams struct {
	Cutoff pgtype.Timestamptz `json:"cutoff"`
	Batch  int32              `json:"batch"`
}

type ListStuckVerifyingRow struct {
	ID            pgtype.UUID        `json:"id"`
	QuarantineKey string             `json:"quarantine_key"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListStuckVerifying(ctx context.Context, arg ListStuckVerifyingParams) ([]ListStuckVerifyingRow, error) {
	rows, err := q.db.Query(ctx, listStuckVerifying, arg.Cutoff, arg.Batch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStuckVerifyingRow
	for rows.Next() {
		var i ListStuckVerifyingRow
		if err := rows.Scan(&i.ID, &i.QuarantineKey, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listYoungVerifying = `-- name: ListYoungVerifying :many
SELECT id, quarantine_key, created_at FROM evidence_sessions
WHERE status = 'VERIFYING' AND created_at > $1
ORDER BY created_at ASC
LIMIT $2
`

type ListYoungVerifyingParams struct {
	Cutoff pgtype.Timestamptz `json:"cutoff"`
	Batch  int32              `json:"batch"`
}

type ListYoungVerifyingRow struct {
	ID            pgtype.UUID        `json:"id"`
	QuarantineKey string             `json:"quarantine_key"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListYoungVerifying(ctx context.Context, arg ListYoungVerifyingParams) ([]ListYoungVerifyingRow, error) {
	rows, err := q.db.Query(ctx, listYoungVerifying, arg.Cutoff, arg.Batch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListYoungVerifyingRow
	for rows.Next() {
		var i ListYoungVerifyingRow
		if err := rows.Scan(&i.ID, &i.QuarantineKey, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markFinalDeleted = `-- name: MarkFinalDeleted :execrows
UPDATE evidence_objects
SET final_deleted_at = now()
WHERE id = $1 AND final_deleted_at IS NULL
`

func (q *Queries) MarkFinalDeleted(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markFinalDeleted, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markQuarantineDeleted = `-- name: MarkQuarantineDeleted :execrows
UPDATE evidence_sessions
SET quarantine_deleted_at = now()
WHERE id = $1 AND quarantine_deleted_at IS NULL
`

func (q *Queries) MarkQuarantineDeleted(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markQuarantineDeleted, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markSessionExpired = `-- name: MarkSessionExpired :execrows
UPDATE evidence_sessions
SET status = 'EXPIRED', updated_at = now()
WHERE id = $1 AND status = 'ISSUED'
`

func (q *Queries) MarkSessionExpired(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markSessionExpired, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markSessionReady = `-- name: MarkSessionReady :execrows
UPDATE evidence_sessions
SET status = 'READY', updated_at = now()
WHERE id = $1 AND status = 'VERIFYING'
`

func (q *Queries) MarkSessionReady(ctx context.Context, id pgtype.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, markSessionReady, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markSessionRejected = `-- name: MarkSessionRejected :execrows
UPDATE evidence_sessions
SET status = 'REJECTED', status_reason = $1, updated_at = now()
WHERE id = $2 AND status = 'VERIFYING'
`

type MarkSessionRejectedParams struct {
	ReasonCodes []string    `json:"reason_codes"`
	ID          pgtype.UUID `json:"id"`
}

func (q *Queries) MarkSessionRejected(ctx context.Context, arg MarkSessionRejectedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markSessionRejected, arg.ReasonCodes, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgeObjectsBefore = `-- name: PurgeObjectsBefore :execrows
DELETE FROM evidence_objects
WHERE created_at < $1
`

func (q *Queries) PurgeObjectsBefore(ctx context.Context, cutoff pgtype.Timestamptz) (int64, error) {
	result, err := q.db.Exec(ctx, purgeObjectsBefore, cutoff)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const quarantineCandidates = `-- name: QuarantineCandidates :many
SELECT id, quarantine_key, status, created_at FROM evidence_sessions
WHERE quarantine_deleted_at IS NULL
    AND (status IN ('READY', 'REJECTED', 'EXPIRED') OR created_at <= $1)
ORDER BY created_at ASC
LIMIT $2
`

type QuarantineCandidatesParams struct {
	OldCutoff pgtype.Timestamptz `json:"old_cutoff"`
	Batch     int32              `json:"batch"`
}

type QuarantineCandidatesRow struct {
	ID            pgtype.UUID        `json:"id"`
	QuarantineKey string             `json:"quarantine_key"`
	Status        string             `json:"status"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) QuarantineCandidates(ctx context.Context, arg QuarantineCandidatesParams) ([]QuarantineCandidatesRow, error) {
	rows, err := q.db.Query(ctx, quarantineCandidates, arg.OldCutoff, arg.Batch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []QuarantineCandidatesRow
	for rows.Next() {
		var i QuarantineCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.QuarantineKey,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const staleFinalCandidates = `-- name: StaleFinalCandidates :many
SELECT id, final_key, created_at, retention_extended_until
FROM evidence_objects
WHERE final_deleted_at IS NULL AND created_at <= $1
ORDER BY created_at ASC
LIMIT $2
`

type StaleFinalCandidatesParams struct {
	YoungCutoff pgtype.Timestamptz `json:"young_cutoff"`
	Batch       int32              `json:"batch"`
}

type StaleFinalCandidatesRow struct {
	ID                     pgtype.UUID        `json:"id"`
	FinalKey               string             `json:"final_key"`
	CreatedAt              pgtype.Timestamptz `json:"created_at"`
	RetentionExtendedUntil pgtype.Timestamptz `json:"retention_extended_until"`
}

func (q *Queries) StaleFinalCandidates(ctx context.Context, arg StaleFinalCandidatesParams) ([]StaleFinalCandidatesRow, error) {
	rows, err := q.db.Query(ctx, staleFinalCandidates, arg.YoungCutoff, arg.Batch)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StaleFinalCandidatesRow
	for rows.Next() {
		var i StaleFinalCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.FinalKey,
			&i.CreatedAt,
			&i.RetentionExtendedUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
