// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package evidence

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type EvidenceObject struct {
	ID                      pgtype.UUID        `json:"id"`
	SessionID               pgtype.UUID        `json:"session_id"`
	FinalKey                string             `json:"final_key"`
	SourceSha256            string             `json:"source_sha256"`
	SanitizedSha256         string             `json:"sanitized_sha256"`
	Width                   int32              `json:"width"`
	Height                  int32              `json:"height"`
	Dhash                   int64              `json:"dhash"`
	BoundObservationID      pgtype.UUID        `json:"bound_observation_id"`
	CreatedAt               pgtype.Timestamptz `json:"created_at"`
	BoundCaptureID          pgtype.UUID        `json:"bound_capture_id"`
	FinalDeletedAt          pgtype.Timestamptz `json:"final_deleted_at"`
	RetentionExtendedUntil  pgtype.Timestamptz `json:"retention_extended_until"`
	RetentionExtendedReason string             `json:"retention_extended_reason"`
	ReceivedAt              pgtype.Timestamptz `json:"received_at"`
}

type EvidenceSession struct {
	ID                  pgtype.UUID        `json:"id"`
	ContributorRef      string             `json:"contributor_ref"`
	ClientSessionID     string             `json:"client_session_id"`
	Mime                string             `json:"mime"`
	DeclaredBytes       int64              `json:"declared_bytes"`
	ClaimedSha256       string             `json:"claimed_sha256"`
	QuarantineKey       string             `json:"quarantine_key"`
	Status              string             `json:"status"`
	StatusReason        []string           `json:"status_reason"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	ExpiresAt           pgtype.Timestamptz `json:"expires_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	PolicyVersion       string             `json:"policy_version"`
	PhotoCaptureID      pgtype.UUID        `json:"photo_capture_id"`
	QuarantineDeletedAt pgtype.Timestamptz `json:"quarantine_deleted_at"`
}
