// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package moderation

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type ModerationAction struct {
	ID            pgtype.UUID        `json:"id"`
	CaseID        pgtype.UUID        `json:"case_id"`
	ActorID       string             `json:"actor_id"`
	Action        string             `json:"action"`
	Reason        string             `json:"reason"`
	OccurredAt    pgtype.Timestamptz `json:"occurred_at"`
	PolicyVersion string             `json:"policy_version"`
}

type ModerationCase struct {
	ID            pgtype.UUID        `json:"id"`
	TargetType    string             `json:"target_type"`
	TargetID      string             `json:"target_id"`
	Status        string             `json:"status"`
	Priority      string             `json:"priority"`
	Reason        string             `json:"reason"`
	Detail        string             `json:"detail"`
	EvidenceID    pgtype.UUID        `json:"evidence_id"`
	OpenedAt      pgtype.Timestamptz `json:"opened_at"`
	PolicyVersion string             `json:"policy_version"`
}
