// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: moderation.sql

package moderation

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAction = `-- name: GetAction :one
SELECT id, case_id, actor_id, action, reason, occurred_at, policy_version
FROM moderation_actions
WHERE id = $1
`

func (q *Queries) GetAction(ctx context.Context, id pgtype.UUID) (ModerationAction, error) {
	row := q.db.QueryRow(ctx, getAction, id)
	var i ModerationAction
	err := row.Scan(
		&i.ID,
		&i.CaseID,
		&i.ActorID,
		&i.Action,
		&i.Reason,
		&i.OccurredAt,
		&i.PolicyVersion,
	)
	return i, err
}

const getCase = `-- name: GetCase :one
SELECT id, target_type, target_id, status, priority, reason, detail,
    evidence_id, opened_at, policy_version
FROM moderation_cases
WHERE id = $1
`

func (q *Queries) GetCase(ctx context.Context, id pgtype.UUID) (ModerationCase, error) {
	row := q.db.QueryRow(ctx, getCase, id)
	var i ModerationCase
	err := row.Scan(
		&i.ID,
		&i.TargetType,
		&i.TargetID,
		&i.Status,
		&i.Priority,
		&i.Reason,
		&i.Detail,
		&i.EvidenceID,
		&i.OpenedAt,
		&i.PolicyVersion,
	)
	return i, err
}

const getOpenCase = `-- name: GetOpenCase :one
SELECT id, target_type, target_id, status, priority, reason, detail,
    evidence_id, opened_at, policy_version
FROM moderation_cases
WHERE target_type = $1 AND target_id = $2
    AND status IN ('OPEN', 'IN_REVIEW')
`

type GetOpenCaseParams struct {
	TargetType string `json:"target_type"`
	TargetID   string `json:"target_id"`
}

func (q *Queries) GetOpenCase(ctx context.Context, arg GetOpenCaseParams) (ModerationCase, error) {
	row := q.db.QueryRow(ctx, getOpenCase, arg.TargetType, arg.TargetID)
	var i ModerationCase
	err := row.Scan(
		&i.ID,
		&i.TargetType,
		&i.TargetID,
		&i.Status,
		&i.Priority,
		&i.Reason,
		&i.Detail,
		&i.EvidenceID,
		&i.OpenedAt,
		&i.PolicyVersion,
	)
	return i, err
}

const insertAction = `-- name: InsertAction :one

INSERT INTO moderation_actions
    (id, case_id, actor_id, action, reason, occurred_at, policy_version)
VALUES ($1, $2, $3, $4, $5, $6,
    $7)
RETURNING id
`

type InsertActionParams struct {
	ID            pgtype.UUID        `json:"id"`
	CaseID        pgtype.UUID        `json:"case_id"`
	ActorID       string             `json:"actor_id"`
	Action        string             `json:"action"`
	Reason        string             `json:"reason"`
	OccurredAt    pgtype.Timestamptz `json:"occurred_at"`
	PolicyVersion string             `json:"policy_version"`
}

// Actions are insert-only. The case status moves exactly once per
// action through TransitionCase below: the only UPDATE path in this
// file, guarded to actionable states so closed cases never reopen.
func (q *Queries) InsertAction(ctx context.Context, arg InsertActionParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertAction,
		arg.ID,
		arg.CaseID,
		arg.ActorID,
		arg.Action,
		arg.Reason,
		arg.OccurredAt,
		arg.PolicyVersion,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const insertCase = `-- name: InsertCase :one

INSERT INTO moderation_cases
    (id, target_type, target_id, status, priority, reason, detail,
     evidence_id, opened_at, policy_version)
VALUES ($1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10)
ON CONFLICT DO NOTHING
RETURNING id
`

type InsertCaseParams struct {
	ID            pgtype.UUID        `json:"id"`
	TargetType    string             `json:"target_type"`
	TargetID      string             `json:"target_id"`
	Status        string             `json:"status"`
	Priority      string             `json:"priority"`
	Reason        string             `json:"reason"`
	Detail        string             `json:"detail"`
	EvidenceID    pgtype.UUID        `json:"evidence_id"`
	OpenedAt      pgtype.Timestamptz `json:"opened_at"`
	PolicyVersion string             `json:"policy_version"`
}

// Owned by moderation. Cases are insert-only in T01: retries converge
// on the open target, duplicate reports return the open case, and the
// queue lists actionable cases by priority then age. No UPDATE or DELETE
// path exists in this file: status moves through audited actions in
// P07-T02, and history is never edited.
func (q *Queries) InsertCase(ctx context.Context, arg InsertCaseParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertCase,
		arg.ID,
		arg.TargetType,
		arg.TargetID,
		arg.Status,
		arg.Priority,
		arg.Reason,
		arg.Detail,
		arg.EvidenceID,
		arg.OpenedAt,
		arg.PolicyVersion,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const listActionsByCase = `-- name: ListActionsByCase :many
SELECT id, case_id, actor_id, action, reason, occurred_at, policy_version
FROM moderation_actions
WHERE case_id = $1
ORDER BY occurred_at ASC, id ASC
`

func (q *Queries) ListActionsByCase(ctx context.Context, caseID pgtype.UUID) ([]ModerationAction, error) {
	rows, err := q.db.Query(ctx, listActionsByCase, caseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ModerationAction
	for rows.Next() {
		var i ModerationAction
		if err := rows.Scan(
			&i.ID,
			&i.CaseID,
			&i.ActorID,
			&i.Action,
			&i.Reason,
			&i.OccurredAt,
			&i.PolicyVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenCases = `-- name: ListOpenCases :many
SELECT id, target_type, target_id, status, priority, reason, detail,
    evidence_id, opened_at, policy_version
FROM moderation_cases
WHERE status IN ('OPEN', 'IN_REVIEW')
    AND (
        CASE priority WHEN 'P1' THEN 0 WHEN 'P2' THEN 1 ELSE 2 END,
        opened_at, id
    ) > ($1::INT, $2::TIMESTAMPTZ, $3::UUID)
ORDER BY
    CASE priority WHEN 'P1' THEN 0 WHEN 'P2' THEN 1 ELSE 2 END ASC,
    opened_at ASC, id ASC
LIMIT $4
`

type ListOpenCasesParams struct {
	CursorRank     int32              `json:"cursor_rank"`
	CursorOpenedAt pgtype.Timestamptz `json:"cursor_opened_at"`
	CursorID       pgtype.UUID        `json:"cursor_id"`
	PageLimit      int32              `json:"page_limit"`
}

func (q *Queries) ListOpenCases(ctx context.Context, arg ListOpenCasesParams) ([]ModerationCase, error) {
	rows, err := q.db.Query(ctx, listOpenCases,
		arg.CursorRank,
		arg.CursorOpenedAt,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ModerationCase
	for rows.Next() {
		var i ModerationCase
		if err := rows.Scan(
			&i.ID,
			&i.TargetType,
			&i.TargetID,
			&i.Status,
			&i.Priority,
			&i.Reason,
			&i.Detail,
			&i.EvidenceID,
			&i.OpenedAt,
			&i.PolicyVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const oldestClosedCase = `-- name: OldestClosedCase :one

SELECT opened_at
FROM moderation_cases
WHERE status IN ('RESOLVED', 'REJECTED') AND opened_at < $1
ORDER BY opened_at ASC
LIMIT 1
`

// Retention (P07-T05): purge long-closed cases with their audit rows.
// Accountability retention is 12 months initially (SECURITY_PRIVACY):
// only RESOLVED/REJECTED cases older than the cutoff go, oldest first
// in bounded batches, audit rows before their cases.
func (q *Queries) OldestClosedCase(ctx context.Context, cutoff pgtype.Timestamptz) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, oldestClosedCase, cutoff)
	var opened_at pgtype.Timestamptz
	err := row.Scan(&opened_at)
	return opened_at, err
}

const purgeClosedCaseActions = `-- name: PurgeClosedCaseActions :execrows
DELETE FROM moderation_actions
WHERE case_id IN (
    SELECT old.id FROM moderation_cases AS old
    WHERE old.status IN ('RESOLVED', 'REJECTED') AND old.opened_at < $1
    ORDER BY old.opened_at ASC
    LIMIT $2
)
`

type PurgeClosedCaseActionsParams struct {
	Cutoff pgtype.Timestamptz `json:"cutoff"`
	Batch  int32              `json:"batch"`
}

func (q *Queries) PurgeClosedCaseActions(ctx context.Context, arg PurgeClosedCaseActionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, purgeClosedCaseActions, arg.Cutoff, arg.Batch)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const purgeClosedCases = `-- name: PurgeClosedCases :execrows
DELETE FROM moderation_cases AS gone
WHERE gone.id IN (
    SELECT old.id FROM moderation_cases AS old
    WHERE old.status IN ('RESOLVED', 'REJECTED') AND old.opened_at < $1
    ORDER BY old.opened_at ASC
    LIMIT $2
)
`

type PurgeClosedCasesParams struct {
	Cutoff pgtype.Timestamptz `json:"cutoff"`
	Batch  int32              `json:"batch"`
}

func (q *Queries) PurgeClosedCases(ctx context.Context, arg PurgeClosedCasesParams) (int64, error) {
	result, err := q.db.Exec(ctx, purgeClosedCases, arg.Cutoff, arg.Batch)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const transitionCase = `-- name: TransitionCase :one
UPDATE moderation_cases SET status = $1
WHERE id = $2 AND status IN ('OPEN', 'IN_REVIEW')
RETURNING id
`

type TransitionCaseParams struct {
	Status string      `json:"status"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) TransitionCase(ctx context.Context, arg TransitionCaseParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, transitionCase, arg.Status, arg.ID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}
