// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: moderation.sql

package moderation

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCase = `-- name: GetCase :one
SELECT id, target_type, target_id, status, priority, reason, detail,
    evidence_id, opened_at, policy_version
FROM moderation_cases
WHERE id = $1
`

func (q *Queries) GetCase(ctx context.Context, id pgtype.UUID) (ModerationCase, error) {
	row := q.db.QueryRow(ctx, getCase, id)
	var i ModerationCase
	err := row.Scan(
		&i.ID,
		&i.TargetType,
		&i.TargetID,
		&i.Status,
		&i.Priority,
		&i.Reason,
		&i.Detail,
		&i.EvidenceID,
		&i.OpenedAt,
		&i.PolicyVersion,
	)
	return i, err
}

const getOpenCase = `-- name: GetOpenCase :one
SELECT id, target_type, target_id, status, priority, reason, detail,
    evidence_id, opened_at, policy_version
FROM moderation_cases
WHERE target_type = $1 AND target_id = $2
    AND status IN ('OPEN', 'IN_REVIEW')
`

type GetOpenCaseParams struct {
	TargetType string `json:"target_type"`
	TargetID   string `json:"target_id"`
}

func (q *Queries) GetOpenCase(ctx context.Context, arg GetOpenCaseParams) (ModerationCase, error) {
	row := q.db.QueryRow(ctx, getOpenCase, arg.TargetType, arg.TargetID)
	var i ModerationCase
	err := row.Scan(
		&i.ID,
		&i.TargetType,
		&i.TargetID,
		&i.Status,
		&i.Priority,
		&i.Reason,
		&i.Detail,
		&i.EvidenceID,
		&i.OpenedAt,
		&i.PolicyVersion,
	)
	return i, err
}

const insertCase = `-- name: InsertCase :one

INSERT INTO moderation_cases
    (id, target_type, target_id, status, priority, reason, detail,
     evidence_id, opened_at, policy_version)
VALUES ($1, $2, $3, $4, $5, $6,
    $7, $8, $9, $10)
ON CONFLICT DO NOTHING
RETURNING id
`

type InsertCaseParams struct {
	ID            pgtype.UUID        `json:"id"`
	TargetType    string             `json:"target_type"`
	TargetID      string             `json:"target_id"`
	Status        string             `json:"status"`
	Priority      string             `json:"priority"`
	Reason        string             `json:"reason"`
	Detail        string             `json:"detail"`
	EvidenceID    pgtype.UUID        `json:"evidence_id"`
	OpenedAt      pgtype.Timestamptz `json:"opened_at"`
	PolicyVersion string             `json:"policy_version"`
}

// Owned by moderation. Cases are insert-only in T01: retries converge
// on the open target, duplicate reports return the open case, and the
// queue lists actionable cases by priority then age. No UPDATE or DELETE
// path exists in this file: status moves through audited actions in
// P07-T02, and history is never edited.
func (q *Queries) InsertCase(ctx context.Context, arg InsertCaseParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertCase,
		arg.ID,
		arg.TargetType,
		arg.TargetID,
		arg.Status,
		arg.Priority,
		arg.Reason,
		arg.Detail,
		arg.EvidenceID,
		arg.OpenedAt,
		arg.PolicyVersion,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const listOpenCases = `-- name: ListOpenCases :many
SELECT id, target_type, target_id, status, priority, reason, detail,
    evidence_id, opened_at, policy_version
FROM moderation_cases
WHERE status IN ('OPEN', 'IN_REVIEW')
    AND (
        CASE priority WHEN 'P1' THEN 0 WHEN 'P2' THEN 1 ELSE 2 END,
        opened_at, id
    ) > ($1::INT, $2::TIMESTAMPTZ, $3::UUID)
ORDER BY
    CASE priority WHEN 'P1' THEN 0 WHEN 'P2' THEN 1 ELSE 2 END ASC,
    opened_at ASC, id ASC
LIMIT $4
`

type ListOpenCasesParams struct {
	CursorRank     int32              `json:"cursor_rank"`
	CursorOpenedAt pgtype.Timestamptz `json:"cursor_opened_at"`
	CursorID       pgtype.UUID        `json:"cursor_id"`
	PageLimit      int32              `json:"page_limit"`
}

func (q *Queries) ListOpenCases(ctx context.Context, arg ListOpenCasesParams) ([]ModerationCase, error) {
	rows, err := q.db.Query(ctx, listOpenCases,
		arg.CursorRank,
		arg.CursorOpenedAt,
		arg.CursorID,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ModerationCase
	for rows.Next() {
		var i ModerationCase
		if err := rows.Scan(
			&i.ID,
			&i.TargetType,
			&i.TargetID,
			&i.Status,
			&i.Priority,
			&i.Reason,
			&i.Detail,
			&i.EvidenceID,
			&i.OpenedAt,
			&i.PolicyVersion,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
