// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: health.sql

package platform

import (
	"context"
)

const postGISVersion = `-- name: PostGISVersion :one

SELECT PostGIS_version()::text
`

// Owned by platform. Modules must not import another module's generated
// package; cross-module reads use owned queries documented in DATA_MODEL.
func (q *Queries) PostGISVersion(ctx context.Context) (string, error) {
	row := q.db.QueryRow(ctx, postGISVersion)
	var column_1 string
	err := row.Scan(&column_1)
	return column_1, err
}
