// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: jobs.sql

package platform

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const claimJob = `-- name: ClaimJob :one
UPDATE job_queue AS j SET
    status = 'leased',
    lease_token = j.lease_token + 1,
    lease_expires_at = now() + ($1::text)::interval,
    worker_id = $2,
    attempts = j.attempts + 1
WHERE j.id = (
    SELECT id FROM job_queue
    WHERE (status = 'queued' OR (status = 'leased' AND lease_expires_at < now()))
        AND not_before <= now()
        AND ($3 = '' OR kind = $3)
    ORDER BY created_at ASC, id ASC
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
RETURNING id, kind, payload, dedupe_key, status, attempts, max_attempts,
    lease_token, lease_expires_at, worker_id, not_before, last_error, created_at
`

type ClaimJobParams struct {
	LeaseTtl string      `json:"lease_ttl"`
	WorkerID string      `json:"worker_id"`
	Kind     interface{} `json:"kind"`
}

func (q *Queries) ClaimJob(ctx context.Context, arg ClaimJobParams) (JobQueue, error) {
	row := q.db.QueryRow(ctx, claimJob, arg.LeaseTtl, arg.WorkerID, arg.Kind)
	var i JobQueue
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Payload,
		&i.DedupeKey,
		&i.Status,
		&i.Attempts,
		&i.MaxAttempts,
		&i.LeaseToken,
		&i.LeaseExpiresAt,
		&i.WorkerID,
		&i.NotBefore,
		&i.LastError,
		&i.CreatedAt,
	)
	return i, err
}

const completeJob = `-- name: CompleteJob :execrows
UPDATE job_queue
SET status = 'done', lease_expires_at = NULL
WHERE id = $1 AND lease_token = $2 AND status = 'leased'
`

type CompleteJobParams struct {
	ID         pgtype.UUID `json:"id"`
	LeaseToken int64       `json:"lease_token"`
}

func (q *Queries) CompleteJob(ctx context.Context, arg CompleteJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeJob, arg.ID, arg.LeaseToken)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const enqueueJob = `-- name: EnqueueJob :one

INSERT INTO job_queue (id, kind, payload, dedupe_key, max_attempts, not_before)
VALUES ($1, $2, $3::jsonb, $4, $5, $6)
ON CONFLICT (dedupe_key) WHERE dedupe_key IS NOT NULL DO NOTHING
RETURNING id
`

type EnqueueJobParams struct {
	ID          pgtype.UUID        `json:"id"`
	Kind        string             `json:"kind"`
	Payload     []byte             `json:"payload"`
	DedupeKey   pgtype.Text        `json:"dedupe_key"`
	MaxAttempts int32              `json:"max_attempts"`
	NotBefore   pgtype.Timestamptz `json:"not_before"`
}

// Owned by platform (job queue). Claim paths use SKIP LOCKED so workers
// never block each other; completion paths bind the fencing token.
func (q *Queries) EnqueueJob(ctx context.Context, arg EnqueueJobParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, enqueueJob,
		arg.ID,
		arg.Kind,
		arg.Payload,
		arg.DedupeKey,
		arg.MaxAttempts,
		arg.NotBefore,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const failJob = `-- name: FailJob :one
UPDATE job_queue AS j SET
    status = CASE WHEN j.attempts >= j.max_attempts THEN 'dead' ELSE 'queued' END,
    lease_expires_at = NULL,
    worker_id = '',
    not_before = CASE WHEN j.attempts >= j.max_attempts THEN j.not_before ELSE now() + ($1::text)::interval END,
    last_error = $2
WHERE j.id = $3 AND j.lease_token = $4 AND j.status = 'leased'
RETURNING status
`

type FailJobParams struct {
	RetryDelay string      `json:"retry_delay"`
	LastError  string      `json:"last_error"`
	ID         pgtype.UUID `json:"id"`
	LeaseToken int64       `json:"lease_token"`
}

func (q *Queries) FailJob(ctx context.Context, arg FailJobParams) (string, error) {
	row := q.db.QueryRow(ctx, failJob,
		arg.RetryDelay,
		arg.LastError,
		arg.ID,
		arg.LeaseToken,
	)
	var status string
	err := row.Scan(&status)
	return status, err
}

const getJob = `-- name: GetJob :one
SELECT id, kind, payload, dedupe_key, status, attempts, max_attempts,
    lease_token, lease_expires_at, worker_id, not_before, last_error, created_at
FROM job_queue
WHERE id = $1
`

func (q *Queries) GetJob(ctx context.Context, id pgtype.UUID) (JobQueue, error) {
	row := q.db.QueryRow(ctx, getJob, id)
	var i JobQueue
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Payload,
		&i.DedupeKey,
		&i.Status,
		&i.Attempts,
		&i.MaxAttempts,
		&i.LeaseToken,
		&i.LeaseExpiresAt,
		&i.WorkerID,
		&i.NotBefore,
		&i.LastError,
		&i.CreatedAt,
	)
	return i, err
}

const getJobByDedupe = `-- name: GetJobByDedupe :one
SELECT id FROM job_queue WHERE dedupe_key = $1
`

func (q *Queries) GetJobByDedupe(ctx context.Context, dedupeKey pgtype.Text) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getJobByDedupe, dedupeKey)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const jobBacklog = `-- name: JobBacklog :one

SELECT COUNT(*) FILTER (WHERE status = 'queued') AS queued,
    COUNT(*) FILTER (WHERE status = 'dead') AS dead,
    MIN(created_at) FILTER (WHERE status = 'queued') AS oldest_queued
FROM job_queue
`

type JobBacklogRow struct {
	Queued       int64       `json:"queued"`
	Dead         int64       `json:"dead"`
	OldestQueued interface{} `json:"oldest_queued"`
}

// Monitoring (P08-T05): queue depth, dead-letter count and oldest
// queued job for backlog alerts. One indexed scan, no payload reads.
func (q *Queries) JobBacklog(ctx context.Context) (JobBacklogRow, error) {
	row := q.db.QueryRow(ctx, jobBacklog)
	var i JobBacklogRow
	err := row.Scan(&i.Queued, &i.Dead, &i.OldestQueued)
	return i, err
}

const replayDeadJob = `-- name: ReplayDeadJob :execrows
UPDATE job_queue
SET status = 'queued', attempts = 0, last_error = $1,
    not_before = now(), lease_expires_at = NULL, worker_id = ''
WHERE id = $2 AND status = 'dead'
`

type ReplayDeadJobParams struct {
	Reason string      `json:"reason"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) ReplayDeadJob(ctx context.Context, arg ReplayDeadJobParams) (int64, error) {
	result, err := q.db.Exec(ctx, replayDeadJob, arg.Reason, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
