// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package official

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type DirectoryIdentifier struct {
	ID               pgtype.UUID        `json:"id"`
	StationID        pgtype.UUID        `json:"station_id"`
	Kind             string             `json:"kind"`
	NormalizedValue  string             `json:"normalized_value"`
	ValidFrom        pgtype.Timestamptz `json:"valid_from"`
	ValidTo          pgtype.Timestamptz `json:"valid_to"`
	SourceRevisionID pgtype.Text        `json:"source_revision_id"`
}

type DirectoryLocationRevision struct {
	ID              pgtype.UUID        `json:"id"`
	StationID       pgtype.UUID        `json:"station_id"`
	Point           interface{}        `json:"point"`
	Quality         string             `json:"quality"`
	Provider        string             `json:"provider"`
	SourceReference string             `json:"source_reference"`
	ObtainedAt      pgtype.Timestamptz `json:"obtained_at"`
	SupersedesID    pgtype.UUID        `json:"supersedes_id"`
}

type DirectoryStation struct {
	ID                pgtype.UUID        `json:"id"`
	DisplayName       string             `json:"display_name"`
	Address           []byte             `json:"address"`
	MunicipalityCode  pgtype.Text        `json:"municipality_code"`
	State             pgtype.Text        `json:"state"`
	Status            string             `json:"status"`
	CurrentPoint      interface{}        `json:"current_point"`
	CurrentQuality    pgtype.Text        `json:"current_quality"`
	CurrentRevisionID pgtype.UUID        `json:"current_revision_id"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type OfficialCurrentRevision struct {
	SurveyStart pgtype.Date        `json:"survey_start"`
	SurveyEnd   pgtype.Date        `json:"survey_end"`
	RevisionID  pgtype.UUID        `json:"revision_id"`
	SwitchedAt  pgtype.Timestamptz `json:"switched_at"`
}

type OfficialImportRun struct {
	ID             pgtype.UUID        `json:"id"`
	SourceUrl      string             `json:"source_url"`
	SourceChecksum string             `json:"source_checksum"`
	ParserVersion  string             `json:"parser_version"`
	DiscoveredAt   pgtype.Timestamptz `json:"discovered_at"`
	Status         string             `json:"status"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	FinishedAt     pgtype.Timestamptz `json:"finished_at"`
	RowCounts      []byte             `json:"row_counts"`
	ErrorSummary   []byte             `json:"error_summary"`
}

type OfficialRevision struct {
	ID                   pgtype.UUID        `json:"id"`
	ImportRunID          pgtype.UUID        `json:"import_run_id"`
	SurveyStart          pgtype.Date        `json:"survey_start"`
	SurveyEnd            pgtype.Date        `json:"survey_end"`
	PublishedAt          pgtype.Timestamptz `json:"published_at"`
	SupersedesRevisionID pgtype.UUID        `json:"supersedes_revision_id"`
	Status               string             `json:"status"`
}

type OfficialStationPrice struct {
	ID             pgtype.UUID `json:"id"`
	RevisionID     pgtype.UUID `json:"revision_id"`
	StationID      pgtype.UUID `json:"station_id"`
	FuelProduct    string      `json:"fuel_product"`
	Unit           string      `json:"unit"`
	AmountMilliBrl int64       `json:"amount_milli_brl"`
	RawPriceText   string      `json:"raw_price_text"`
	CollectedOn    pgtype.Date `json:"collected_on"`
	SourceRow      int32       `json:"source_row"`
}

type OfficialSummaryPrice struct {
	ID           pgtype.UUID    `json:"id"`
	RevisionID   pgtype.UUID    `json:"revision_id"`
	Scope        string         `json:"scope"`
	LocationCode string         `json:"location_code"`
	FuelProduct  string         `json:"fuel_product"`
	Unit         string         `json:"unit"`
	Mean         pgtype.Numeric `json:"mean"`
	MinAmount    pgtype.Numeric `json:"min_amount"`
	MaxAmount    pgtype.Numeric `json:"max_amount"`
	StdDev       pgtype.Numeric `json:"std_dev"`
	StationCount pgtype.Int4    `json:"station_count"`
	RawFields    []byte         `json:"raw_fields"`
}
