// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: revisions.sql

package official

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countRevisionRows = `-- name: CountRevisionRows :one
SELECT count(*) FROM official_station_prices WHERE revision_id = $1
`

func (q *Queries) CountRevisionRows(ctx context.Context, revisionID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countRevisionRows, revisionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createImportRun = `-- name: CreateImportRun :one

INSERT INTO official_import_runs (id, source_url, source_checksum, parser_version)
VALUES ($1, $2, $3, $4)
RETURNING id
`

type CreateImportRunParams struct {
	ID             pgtype.UUID `json:"id"`
	SourceUrl      string      `json:"source_url"`
	SourceChecksum string      `json:"source_checksum"`
	ParserVersion  string      `json:"parser_version"`
}

// Owned by official. Modules must not import another module's generated
// package; cross-module reads use owned queries documented in DATA_MODEL.
func (q *Queries) CreateImportRun(ctx context.Context, arg CreateImportRunParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createImportRun,
		arg.ID,
		arg.SourceUrl,
		arg.SourceChecksum,
		arg.ParserVersion,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const createRevision = `-- name: CreateRevision :one
INSERT INTO official_revisions
    (id, import_run_id, survey_start, survey_end, supersedes_revision_id)
VALUES ($1, $2, $3, $4, $5)
RETURNING id
`

type CreateRevisionParams struct {
	ID                   pgtype.UUID `json:"id"`
	ImportRunID          pgtype.UUID `json:"import_run_id"`
	SurveyStart          pgtype.Date `json:"survey_start"`
	SurveyEnd            pgtype.Date `json:"survey_end"`
	SupersedesRevisionID pgtype.UUID `json:"supersedes_revision_id"`
}

func (q *Queries) CreateRevision(ctx context.Context, arg CreateRevisionParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, createRevision,
		arg.ID,
		arg.ImportRunID,
		arg.SurveyStart,
		arg.SurveyEnd,
		arg.SupersedesRevisionID,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const findConflictingStationPrice = `-- name: FindConflictingStationPrice :many
SELECT id, source_row, amount_milli_brl
FROM official_station_prices
WHERE revision_id = $1
    AND station_id = $2
    AND fuel_product = $3
    AND unit = $4
    AND collected_on = $5
    AND source_row <> $6
    AND amount_milli_brl <> $7
`

type FindConflictingStationPriceParams struct {
	RevisionID     pgtype.UUID `json:"revision_id"`
	StationID      pgtype.UUID `json:"station_id"`
	FuelProduct    string      `json:"fuel_product"`
	Unit           string      `json:"unit"`
	CollectedOn    pgtype.Date `json:"collected_on"`
	SourceRow      int32       `json:"source_row"`
	AmountMilliBrl int64       `json:"amount_milli_brl"`
}

type FindConflictingStationPriceRow struct {
	ID             pgtype.UUID `json:"id"`
	SourceRow      int32       `json:"source_row"`
	AmountMilliBrl int64       `json:"amount_milli_brl"`
}

func (q *Queries) FindConflictingStationPrice(ctx context.Context, arg FindConflictingStationPriceParams) ([]FindConflictingStationPriceRow, error) {
	rows, err := q.db.Query(ctx, findConflictingStationPrice,
		arg.RevisionID,
		arg.StationID,
		arg.FuelProduct,
		arg.Unit,
		arg.CollectedOn,
		arg.SourceRow,
		arg.AmountMilliBrl,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []FindConflictingStationPriceRow
	for rows.Next() {
		var i FindConflictingStationPriceRow
		if err := rows.Scan(&i.ID, &i.SourceRow, &i.AmountMilliBrl); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const finishImportRun = `-- name: FinishImportRun :exec
UPDATE official_import_runs
SET status = $1,
    row_counts = $2::jsonb,
    error_summary = $3::jsonb,
    finished_at = now()
WHERE id = $4
`

type FinishImportRunParams struct {
	Status       string      `json:"status"`
	RowCounts    []byte      `json:"row_counts"`
	ErrorSummary []byte      `json:"error_summary"`
	ID           pgtype.UUID `json:"id"`
}

func (q *Queries) FinishImportRun(ctx context.Context, arg FinishImportRunParams) error {
	_, err := q.db.Exec(ctx, finishImportRun,
		arg.Status,
		arg.RowCounts,
		arg.ErrorSummary,
		arg.ID,
	)
	return err
}

const getCurrentPointer = `-- name: GetCurrentPointer :one
SELECT revision_id FROM official_current_revisions
WHERE survey_start = $1 AND survey_end = $2
`

type GetCurrentPointerParams struct {
	SurveyStart pgtype.Date `json:"survey_start"`
	SurveyEnd   pgtype.Date `json:"survey_end"`
}

func (q *Queries) GetCurrentPointer(ctx context.Context, arg GetCurrentPointerParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getCurrentPointer, arg.SurveyStart, arg.SurveyEnd)
	var revision_id pgtype.UUID
	err := row.Scan(&revision_id)
	return revision_id, err
}

const getImportRunByIdentity = `-- name: GetImportRunByIdentity :one
SELECT id, source_url, source_checksum, parser_version, status,
    row_counts, error_summary, started_at, finished_at
FROM official_import_runs
WHERE source_url = $1
    AND source_checksum = $2
    AND parser_version = $3
`

type GetImportRunByIdentityParams struct {
	SourceUrl      string `json:"source_url"`
	SourceChecksum string `json:"source_checksum"`
	ParserVersion  string `json:"parser_version"`
}

type GetImportRunByIdentityRow struct {
	ID             pgtype.UUID        `json:"id"`
	SourceUrl      string             `json:"source_url"`
	SourceChecksum string             `json:"source_checksum"`
	ParserVersion  string             `json:"parser_version"`
	Status         string             `json:"status"`
	RowCounts      []byte             `json:"row_counts"`
	ErrorSummary   []byte             `json:"error_summary"`
	StartedAt      pgtype.Timestamptz `json:"started_at"`
	FinishedAt     pgtype.Timestamptz `json:"finished_at"`
}

func (q *Queries) GetImportRunByIdentity(ctx context.Context, arg GetImportRunByIdentityParams) (GetImportRunByIdentityRow, error) {
	row := q.db.QueryRow(ctx, getImportRunByIdentity, arg.SourceUrl, arg.SourceChecksum, arg.ParserVersion)
	var i GetImportRunByIdentityRow
	err := row.Scan(
		&i.ID,
		&i.SourceUrl,
		&i.SourceChecksum,
		&i.ParserVersion,
		&i.Status,
		&i.RowCounts,
		&i.ErrorSummary,
		&i.StartedAt,
		&i.FinishedAt,
	)
	return i, err
}

const getLatestPublishedRevision = `-- name: GetLatestPublishedRevision :one
SELECT id, import_run_id, survey_start, survey_end, published_at,
    supersedes_revision_id, status
FROM official_revisions
WHERE status = 'published'
ORDER BY published_at DESC, id DESC
LIMIT 1
`

func (q *Queries) GetLatestPublishedRevision(ctx context.Context) (OfficialRevision, error) {
	row := q.db.QueryRow(ctx, getLatestPublishedRevision)
	var i OfficialRevision
	err := row.Scan(
		&i.ID,
		&i.ImportRunID,
		&i.SurveyStart,
		&i.SurveyEnd,
		&i.PublishedAt,
		&i.SupersedesRevisionID,
		&i.Status,
	)
	return i, err
}

const getRevision = `-- name: GetRevision :one
SELECT id, import_run_id, survey_start, survey_end, published_at,
    supersedes_revision_id, status
FROM official_revisions
WHERE id = $1
`

func (q *Queries) GetRevision(ctx context.Context, id pgtype.UUID) (OfficialRevision, error) {
	row := q.db.QueryRow(ctx, getRevision, id)
	var i OfficialRevision
	err := row.Scan(
		&i.ID,
		&i.ImportRunID,
		&i.SurveyStart,
		&i.SurveyEnd,
		&i.PublishedAt,
		&i.SupersedesRevisionID,
		&i.Status,
	)
	return i, err
}

const setRevisionPublished = `-- name: SetRevisionPublished :exec
UPDATE official_revisions
SET status = 'published', published_at = now()
WHERE id = $1
`

func (q *Queries) SetRevisionPublished(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, setRevisionPublished, id)
	return err
}

const setRevisionStatus = `-- name: SetRevisionStatus :exec
UPDATE official_revisions
SET status = $1
WHERE id = $2
`

type SetRevisionStatusParams struct {
	Status string      `json:"status"`
	ID     pgtype.UUID `json:"id"`
}

func (q *Queries) SetRevisionStatus(ctx context.Context, arg SetRevisionStatusParams) error {
	_, err := q.db.Exec(ctx, setRevisionStatus, arg.Status, arg.ID)
	return err
}

const stageStationPrice = `-- name: StageStationPrice :one
INSERT INTO official_station_prices
    (id, revision_id, station_id, fuel_product, unit, amount_milli_brl,
     raw_price_text, collected_on, source_row)
VALUES ($1, $2, $3, $4, $5,
    $6, $7, $8, $9)
ON CONFLICT (revision_id, source_row) DO NOTHING
RETURNING id
`

type StageStationPriceParams struct {
	ID             pgtype.UUID `json:"id"`
	RevisionID     pgtype.UUID `json:"revision_id"`
	StationID      pgtype.UUID `json:"station_id"`
	FuelProduct    string      `json:"fuel_product"`
	Unit           string      `json:"unit"`
	AmountMilliBrl int64       `json:"amount_milli_brl"`
	RawPriceText   string      `json:"raw_price_text"`
	CollectedOn    pgtype.Date `json:"collected_on"`
	SourceRow      int32       `json:"source_row"`
}

func (q *Queries) StageStationPrice(ctx context.Context, arg StageStationPriceParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, stageStationPrice,
		arg.ID,
		arg.RevisionID,
		arg.StationID,
		arg.FuelProduct,
		arg.Unit,
		arg.AmountMilliBrl,
		arg.RawPriceText,
		arg.CollectedOn,
		arg.SourceRow,
	)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const upsertCurrentPointer = `-- name: UpsertCurrentPointer :exec
INSERT INTO official_current_revisions (survey_start, survey_end, revision_id)
VALUES ($1, $2, $3)
ON CONFLICT (survey_start, survey_end)
DO UPDATE SET revision_id = EXCLUDED.revision_id, switched_at = now()
`

type UpsertCurrentPointerParams struct {
	SurveyStart pgtype.Date `json:"survey_start"`
	SurveyEnd   pgtype.Date `json:"survey_end"`
	RevisionID  pgtype.UUID `json:"revision_id"`
}

func (q *Queries) UpsertCurrentPointer(ctx context.Context, arg UpsertCurrentPointerParams) error {
	_, err := q.db.Exec(ctx, upsertCurrentPointer, arg.SurveyStart, arg.SurveyEnd, arg.RevisionID)
	return err
}
